@startuml orcaflex_modal
scale 3
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Tomato

title OrcaFlex Modal Analysis

start

    note right
        Objective: To streamline (and automate) modal analysis.
    end note

    partition "FEA Model" {

        :Prepare yaml Model File (yml);

    }

    partition "Analysis" {
        :Load .YML file;
            note right
                TBA
            end note

        :Perform Static Analysis;
            note right
                TBA
            end note

        :Perform Modal Analysis;
            note right
                TBA
            end note

    }

    partition "Post-Processing" {
        :.csv and visualizations;
            note right
                Identify bending, axial modes
                Extract only axial mode data
            end note
    }

stop

footer
%date("yyyy.MM.dd' at 'HH:mm")
%filename()
end footer

@enduml
