# Input Parameters for Parametric Analysis
# Source: E01 Explicit geometry stinger.yml
# Generated: 2026-01-18 22:18:10

water_depth: 100
current_speed: 0.5
wind_speed: 0
water_density: 1.025
stage_durations:
- 6
- 150
wave_direction: 135

