# Input Parameters for Parametric Analysis
# Source: K02 10MW fixed-bottom OWT.yml
# Generated: 2026-01-18 21:52:10

current_speed: 0
water_density: 1.025
stage_durations:
- 100
- 100
wave_direction: 180

