# Input Parameters for Parametric Analysis
# Source: E02 Rigid hinged stinger with piggyback line.yml
# Generated: 2026-01-18 21:51:57

water_depth: 100
current_speed: 1
wind_speed: 0
water_density: 1.025
stage_durations:
- 10
- 100
wave_direction: 135

