# Input Parameters for Parametric Analysis
# Source: C10 Multiple statics.yml
# Generated: 2026-01-18 22:18:08

water_depth: 100
current_speed: 0
wind_speed: 0
water_density: 1.025
stage_durations:
- 8
- 16
hs: 7
tp: 8
wave_direction: 180

