"""Parametric padeye (lifting-lug) APDL template generator (digitalmodel #948).

Emits a complete ANSYS Mechanical APDL ``.inp`` for a first-pass **screening**
FE of a padeye main plate: a flat plate with a pin hole, loaded by a sling
bearing force on the loaded hole arc, fixed along its weld base, solved static-
structural, post-processed to peak von Mises stress and a unity check (UC)
against the allowable.

The generic ``apdl_generator`` building blocks cover materials/elements/mesh/BC
but NOT geometry primitives, so this module writes the plate-with-hole geometry
(PLANE182, plane stress with thickness) directly. The generated script runs on a
licensed MAPDL via the fail-closed ANSYS runner (#940); this module needs no
license (it only writes text).

Honesty: a 2-D plane-stress plate-with-hole is a screening idealisation (no cheek
plates, no out-of-plane/weld-throat checks, linear elastic). Use it to size and
rank; verify governing cases with a full 3-D model.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from pathlib import Path


@dataclass
class PadeyeGeometry:
    """Padeye main-plate geometry, load, and material (units: mm, N, MPa)."""

    plate_width_mm: float = 400.0
    plate_height_mm: float = 300.0
    thickness_mm: float = 40.0
    hole_diameter_mm: float = 80.0
    # Hole centre; default centred horizontally, high on the plate.
    hole_center_x_mm: float | None = None
    hole_center_y_mm: float | None = None
    sling_load_kn: float = 500.0
    sling_angle_deg: float = 0.0  # from vertical, toward +X
    youngs_modulus_mpa: float = 205_000.0
    poisson: float = 0.3
    yield_strength_mpa: float = 355.0
    design_factor: float = 1.67  # allowable = yield / design_factor (~0.6 Fy)
    element_size_mm: float = 10.0

    def resolved_center(self) -> tuple[float, float]:
        xc = self.hole_center_x_mm
        yc = self.hole_center_y_mm
        if xc is None:
            xc = self.plate_width_mm / 2.0
        if yc is None:
            # One hole-diameter of edge distance above the hole top, by default.
            yc = self.plate_height_mm - self.hole_diameter_mm
        return float(xc), float(yc)

    def validate(self) -> list[str]:
        issues: list[str] = []
        if min(self.plate_width_mm, self.plate_height_mm, self.thickness_mm) <= 0:
            issues.append("plate dimensions must be positive")
        if self.hole_diameter_mm <= 0:
            issues.append("hole diameter must be positive")
        xc, yc = self.resolved_center()
        r = self.hole_diameter_mm / 2.0
        if not (r < xc < self.plate_width_mm - r):
            issues.append("hole overruns the plate width (edge distance < radius)")
        if not (r < yc < self.plate_height_mm - r):
            issues.append("hole overruns the plate height (edge distance < radius)")
        if self.design_factor <= 0 or self.yield_strength_mpa <= 0:
            issues.append("yield strength and design factor must be positive")
        return issues


def generate_padeye_apdl(geom: PadeyeGeometry) -> str:
    """Return a complete MAPDL ``.inp`` script for the padeye screening FE."""
    issues = geom.validate()
    if issues:
        raise ValueError("invalid padeye geometry: " + "; ".join(issues))

    xc, yc = geom.resolved_center()
    r = geom.hole_diameter_mm / 2.0
    allowable = geom.yield_strength_mpa / geom.design_factor
    load_n = geom.sling_load_kn * 1000.0
    fx_total = load_n * math.sin(math.radians(geom.sling_angle_deg))
    fy_total = load_n * math.cos(math.radians(geom.sling_angle_deg))

    return f"""! Padeye (lifting-lug) screening FE — generated by digitalmodel.ansys.padeye
! Units: mm, N, MPa (plane stress with thickness)
FINISH
/CLEAR,NOSTART
/TITLE,Padeye screening: t={geom.thickness_mm}mm hole={geom.hole_diameter_mm}mm
/UNITS,MPA
/PREP7

! --- material (linear elastic steel) ---
MP,EX,1,{geom.youngs_modulus_mpa}
MP,PRXY,1,{geom.poisson}

! --- element: PLANE182, plane stress with thickness ---
ET,1,PLANE182
KEYOPT,1,3,3            ! plane stress with thickness
R,1,{geom.thickness_mm}  ! plate thickness (real constant)

! --- geometry: main plate minus pin hole ---
BLC4,0,0,{geom.plate_width_mm},{geom.plate_height_mm}   ! area 1 = plate
CYL4,{xc},{yc},{r}                                       ! area 2 = hole disk
ASBA,1,2               ! subtract hole -> plate-with-hole area

! --- mesh ---
TYPE,1
MAT,1
REAL,1
ESIZE,{geom.element_size_mm}
AMESH,ALL

! --- boundary conditions: fix the weld base (bottom edge y=0) ---
NSEL,S,LOC,Y,0
D,ALL,ALL,0
ALLSEL,ALL

! --- load: sling bearing force on the upper hole arc ---
LOCAL,11,1,{xc},{yc},0     ! cylindrical CS at hole centre
CSYS,11
NSEL,S,LOC,X,{r * 0.98},{r * 1.02}   ! nodes on the hole edge (radius ~ r)
NSEL,R,LOC,Y,0,180                    ! upper semicircle (loaded arc)
CSYS,0
*GET,nload,NODE,0,COUNT
fx_n = {fx_total} / nload
fy_n = {fy_total} / nload
F,ALL,FX,fx_n
F,ALL,FY,fy_n
ALLSEL,ALL

! --- solve (static structural) ---
/SOLU
ANTYPE,STATIC
SOLVE
FINISH

! --- post: peak von Mises + unity check ---
/POST1
SET,LAST
NSORT,S,EQV
*GET,smax,SORT,0,MAX
allow = {allowable}
uc = smax / allow
/COM,============================================================
/COM,PADEYE SCREENING RESULT
*MSG,INFO,smax,allow,uc
peak von Mises = %G MPa ; allowable = %G MPa ; UC = %G
/COM,============================================================
! numeric digest for the postprocessor (small, returnable)
*CFOPEN,padeye_result,csv
*VWRITE,smax,allow,uc
('max_seqv_mpa,',F12.4,',allowable_mpa,',F12.4,',uc,',F10.5)
*CFCLOS
FINISH
"""


def write_padeye_inp(geom: PadeyeGeometry, path: Path | str) -> Path:
    """Write the generated APDL script to ``path`` and return it."""
    out = Path(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(generate_padeye_apdl(geom))
    return out
