# ABOUTME: Visualisation decks for the #2157 weldolet crack models: the exact receipt deck
# ABOUTME: plus an appended MAPDL plotting block; renders host-free PNG figures and a manifest.
"""Model, mesh and result pictures of the #2157 weldolet FE states (P4 Rev B).

Each visualisation deck is the receipt deck of a declared FE state, regenerated by its
generator from the receipt spec and checked against the SHA-256 recorded in the receipt
(fail-closed), followed by a plotting block (``/SHOW,PNG``, ``/VIEW``, ``EPLOT``,
``PLNSOL``). The receipt decks, receipts and their hashes are not changed: the plotting
block exists only in the visualisation deck, which is solved in a scratch directory.

The PNG files are re-encoded without ancillary chunks (no text, time or physical-size
chunk), cropped to the drawing, and listed in ``figures.json`` with their SHA-256, the
state, level, generator and solver release. The report embeds them from that manifest.

Run (licensed host, one job at a time)::

    python -m digitalmodel.ansys.weldolet_figures --work <scratch-dir> \\
        --out examples/workflows/crack-fe-weldolet/figures
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import shutil
import struct
import time
import zlib
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

from digitalmodel.ansys import weldolet_crack as wc
from digitalmodel.ansys import weldolet_crotch as wcr

MANIFEST = "figures.json"
_PNG_SIG = b"\x89PNG\r\n\x1a\n"
_KEEP_CHUNKS = (b"IHDR", b"PLTE", b"IDAT", b"IEND")

# crack centre of the crotch flaw at a0 in the symmetry plane (y = 0): x = C/2 + a at the
# deepest point, z = R_o + v0 (v0 = 0.5 - a); used only to aim the views
_A0 = 2.35
_RW = 23.81 / 2.0
_RO = 168.3 / 2.0
_V0 = 0.5 - _A0
_Z0 = _RO + _V0


@dataclass(frozen=True)
class Run:
    """One visualisation solve: a declared state, its level and the plots appended."""

    state: str
    level: int
    generator: str
    plots: tuple[tuple[str, str], ...]  # (figure id, APDL lines ending in EPLOT/PLNSOL)
    views: tuple[tuple[str, str], ...]  # (figure id, one-line description of the view)


_HEADER = """! ---- visualisation block (digitalmodel.ansys.weldolet_figures) ----
! appended after the receipt deck; not part of any receipt
/POST1
SET,LAST
/GFILE,1600
/SHOW,PNG,,0
PNGR,COMP,1,-1
/RGB,INDEX,100,100,100,0
/RGB,INDEX,80,80,80,13
/RGB,INDEX,60,60,60,14
/RGB,INDEX,0,0,0,15
/PLOPTS,FRAME,0
/PLOPTS,TITLE,0
/PLOPTS,MINM,0
/PLOPTS,FILE,0
/PLOPTS,LOGO,0
/PLOPTS,WINS,1
/PLOPTS,WP,0
/PLOPTS,DATE,0
/TRIAD,OFF
/TYPE,1,6
/VUP,1,Z
"""

_MESH_ONLY = "/PLOPTS,INFO,0\n/EDGE,1,0\n/GLINE,1,0\n"
_GEOMETRY_ONLY = "/PLOPTS,INFO,0\n/EDGE,1,1,45\n/GLINE,1,-1\n"
_CONTOUR = ("/PLOPTS,INFO,3\n/PLOPTS,LEG1,1\n/PLOPTS,LEG2,0\n/PLOPTS,LEG3,1\n"
            "/EDGE,1,1,45\n/GLINE,1,-1\n")
_ISO = "/VIEW,1,1,-1.3,0.8\n/ANG,1,0\n"


def _box(x: tuple[float, float], y: tuple[float, float], z: tuple[float, float]) -> str:
    """Select the elements whose centroid lies in the box (and their nodes)."""
    return (f"ESEL,S,CENT,X,{x[0]!r},{x[1]!r}\nESEL,R,CENT,Y,{y[0]!r},{y[1]!r}\n"
            f"ESEL,R,CENT,Z,{z[0]!r},{z[1]!r}\nNSLE,S\n")


_FACE = "/VIEW,1,0,-1,0\n/ANG,1,0\n"
_PLAN = "/VUP,1,Y\n/VIEW,1,0,0,1\n/ANG,1,0\n"
_WELDOLET_BOX = _box((-45.0, 45.0), (-45.0, 45.0), (55.0, 135.0))
_CROTCH_SECTION_BOX = _box((4.0, 36.0), (0.0, 3.0), (74.0, 106.0))
_FLAW_BOX = _box((_RW - 3.0, _RW + 7.0), (0.0, 2.0), (_Z0 - 5.0, _Z0 + 4.5))
_TUBE_BOX = (f"CSYS,11\nNSEL,S,LOC,X,0.0,{_Z0 + 1.0e-6!r}\nESLN,S,1\nCSYS,0\n"
             f"ESEL,R,CENT,X,{_RW + _A0 - 0.9!r},{_RW + _A0 + 0.9!r}\n"
             "ESEL,R,CENT,Y,0.0,1.2\nNSLE,S\n")
_END = "ALLSEL,ALL\n/VUP,1,Z\n"

RUNS: dict[str, Run] = {
    "uncracked": Run(
        state="p0b_uncracked", level=0, generator="digitalmodel.ansys.weldolet_crack",
        plots=(
            ("model_iso", _GEOMETRY_ONLY + _ISO + "/AUTO,1\nEPLOT\n"),
            ("mesh_global", _MESH_ONLY + _ISO + "/AUTO,1\nEPLOT\n"),
            ("mesh_weldolet", _MESH_ONLY + _WELDOLET_BOX + _ISO + "/AUTO,1\nEPLOT\n" + _END),
            ("hoop_iso", _CONTOUR + "RSYS,11\n" + _WELDOLET_BOX + _ISO
             + "/AUTO,1\nPLNSOL,S,Y\n" + _END),
            ("hoop_section", _CONTOUR + "RSYS,11\n" + _CROTCH_SECTION_BOX + _FACE
             + "/AUTO,1\nPLNSOL,S,Y\n" + _END),
        ),
        views=(
            ("model_iso", "isometric view of the whole model, feature edges only"),
            ("mesh_global", "isometric view of the whole model with element edges"),
            ("mesh_weldolet", "isometric view of the weldolet region (elements with "
                              "centroid within 45 mm of the branch axis) with element edges"),
            ("hoop_iso", "hoop stress (cylindrical system about the run-pipe axis) on the "
                         "weldolet region, isometric view"),
            ("hoop_section", "hoop stress on the section y = 0 through the branch axis, "
                             "viewed from -y, +x crotch region (elements within 3 mm of "
                             "the section)"),
        ),
    ),
    "crotch": Run(
        state="p0b_crotch_a2p35", level=0, generator="digitalmodel.ansys.weldolet_crotch",
        plots=(
            ("crotch_mesh_global", _MESH_ONLY + _ISO + "/AUTO,1\nEPLOT\n"),
            ("crotch_mesh_face", _MESH_ONLY + _FLAW_BOX + _FACE + "/AUTO,1\nEPLOT\n" + _END),
            ("crotch_mesh_spider", _MESH_ONLY + _TUBE_BOX + _PLAN + "/AUTO,1\nEPLOT\n"
             + _END),
            ("crotch_sy_face", _CONTOUR + "RSYS,0\n/CONT,1,10,0,25,250\n" + _FLAW_BOX
             + _FACE + "/AUTO,1\nPLNSOL,S,Y\n/CONT,1,9,AUTO\n" + _END),
        ),
        views=(
            ("crotch_mesh_global", "isometric view of the half model (y >= 0) with "
                                   "element edges"),
            ("crotch_mesh_face", "symmetry plane y = 0 viewed from -y: crack face and "
                                 "crack block around the semicircular front"),
            ("crotch_mesh_spider", "elements below the surface through the deepest front "
                                   "point, viewed from +z: the spider-web crack tube"),
            ("crotch_sy_face", "stress normal to the crack plane (SY) on the symmetry "
                               "plane, viewed from -y; contour range 0 to 250 MPa"),
        ),
    ),
}

# --------------------------------------------------------------------------- #
# Decks
# --------------------------------------------------------------------------- #
def _receipt(state: str, fe_states: Path) -> dict:
    return json.loads((Path(fe_states) / f"{state}.receipt.json").read_text("utf-8"))


def receipt_deck(state: str, level: int, fe_states: Path) -> str:
    """The receipt deck of ``state`` at ``level``, regenerated and hash-checked."""
    rec = _receipt(state, fe_states)
    if rec["kind"] == "weldolet_uncracked" or "base" not in rec["spec"]:
        deck = wc.generate_weldolet_apdl(wc.spec_from_receipt(rec, level))
    else:
        deck = wcr.generate_crotch_apdl(wcr.spec_from_receipt(rec, level))
    want = next(m["deck_sha256"] for m in rec["meshes"] if m["level"] == level)
    got = wc.deck_sha256(deck)
    if got != want:
        raise ValueError(f"regenerated deck of {state} level {level} does not match the "
                         f"receipt deck digest ({got} != {want})")
    return deck


def visual_deck(run: str, fe_states: Path) -> str:
    """The receipt deck followed by the plotting block of ``run``."""
    spec = RUNS[run]
    body = "".join(lines for _, lines in spec.plots)
    return receipt_deck(spec.state, spec.level, fe_states) + _HEADER + body + "FINISH\n"


# --------------------------------------------------------------------------- #
# PNG hygiene
# --------------------------------------------------------------------------- #
def sanitise_png(blob: bytes) -> bytes:
    """``blob`` with only the critical chunks (IHDR, PLTE, IDAT, IEND) kept."""
    if not blob.startswith(_PNG_SIG):
        raise ValueError("not a PNG file")
    out, pos = [_PNG_SIG], 8
    while pos < len(blob):
        (n,) = struct.unpack(">I", blob[pos:pos + 4])
        kind = blob[pos + 4:pos + 8]
        data = blob[pos + 8:pos + 8 + n]
        if kind in _KEEP_CHUNKS:
            out.append(struct.pack(">I", n) + kind + data
                       + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF))
        pos += 12 + n
        if kind == b"IEND":
            break
    return b"".join(out)


def _crop(blob: bytes, margin: int = 16) -> bytes:
    """Crop to the non-white drawing and re-encode (Pillow writes no text chunks)."""
    from PIL import Image, ImageChops

    img = Image.open(io.BytesIO(blob)).convert("RGB")
    bg = Image.new("RGB", img.size, (255, 255, 255))
    box = ImageChops.difference(img, bg).getbbox()
    if box:
        left, t, r, b = box
        img = img.crop((max(left - margin, 0), max(t - margin, 0),
                        min(r + margin, img.width), min(b + margin, img.height)))
    if img.width > 1200:
        img = img.resize((1200, round(img.height * 1200 / img.width)), Image.BOX)
    buf = io.BytesIO()
    img.save(buf, format="PNG", optimize=True)
    return sanitise_png(buf.getvalue())


# --------------------------------------------------------------------------- #
# Rendering (licensed host)
# --------------------------------------------------------------------------- #
def render(work: Path, out: Path, fe_states: Path, runs: tuple[str, ...] = tuple(RUNS),
           runner: Callable | None = None) -> dict:
    """Solve each visualisation deck in ``work`` and write the figures to ``out``."""
    from digitalmodel.ansys.runner import ANSYSRunStatus, run_ansys

    runner = runner or run_ansys
    work, out = Path(work), Path(out)
    out.mkdir(parents=True, exist_ok=True)
    man_path = out / MANIFEST
    manifest = (json.loads(man_path.read_text("utf-8")) if man_path.is_file()
                else {"figures": {}})
    manifest["note"] = ("Visualisation decks: the receipt deck of each state (hash-checked) "
                        "plus an appended plotting block; receipts are unchanged.")
    timings = {}
    for name in runs:
        spec = RUNS[name]
        rec = _receipt(spec.state, fe_states)
        rundir = work / name
        if rundir.exists():
            shutil.rmtree(rundir)
        rundir.mkdir(parents=True)
        deck = visual_deck(name, fe_states)
        inp = rundir / f"{spec.state}_L{spec.level}_vis.inp"
        inp.write_bytes(deck.encode("utf-8"))
        t0 = time.monotonic()
        res = runner(inp, output_dir=rundir, timeout_seconds=7200,
                     extra_args=["-smp", "-np", "4"])
        timings[name] = time.monotonic() - t0
        if res.status != ANSYSRunStatus.COMPLETED:
            raise RuntimeError(f"visualisation run {name} failed: {res.error_message}")
        pngs = sorted(rundir.glob("*.png"))
        if len(pngs) != len(spec.plots):
            raise RuntimeError(f"{name}: expected {len(spec.plots)} PNG files, got {len(pngs)}")
        views = dict(spec.views)
        mesh = next(m for m in rec["meshes"] if m["level"] == spec.level)
        for (fid, _), png in zip(spec.plots, pngs):
            blob = _crop(png.read_bytes())
            fname = f"{fid}.png"
            (out / fname).write_bytes(blob)
            manifest["figures"][fid] = {
                "file": fname,
                "sha256": hashlib.sha256(blob).hexdigest(),
                "state": spec.state,
                "level": spec.level,
                "generator": spec.generator,
                "receipt_deck_sha256": mesh["deck_sha256"],
                "mapdl_release": rec["run"]["mapdl_release"],
                "mapdl_version": rec["run"]["mapdl_version"],
                "view": views[fid],
                "width_px": _png_size(blob)[0],
                "height_px": _png_size(blob)[1],
            }
    manifest["figures"] = dict(sorted(manifest["figures"].items()))
    man_path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", "utf-8")
    return timings


def _png_size(blob: bytes) -> tuple[int, int]:
    return struct.unpack(">II", blob[16:24])


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Render the #2157 weldolet figures (MAPDL).")
    ap.add_argument("--work", required=True, help="scratch directory for the solves")
    ap.add_argument("--out", default="examples/workflows/crack-fe-weldolet/figures")
    ap.add_argument("--fe-states", default="examples/workflows/crack-fe-weldolet/fe_states")
    ap.add_argument("--run", action="append", choices=sorted(RUNS))
    a = ap.parse_args(argv)
    timings = render(Path(a.work), Path(a.out), Path(a.fe_states),
                     tuple(a.run) if a.run else tuple(RUNS))
    for name, sec in timings.items():
        print(f"{name}: {sec:.1f} s")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
