#!/bin/bash
# daily_context_check.sh - Daily context health check and improvement
# Usage: ./daily_context_check.sh

set -e

WORKSPACE_ROOT="${WORKSPACE_ROOT:-D:/workspace-hub}"
SCRIPT_DIR="$(dirname "$0")"
REPORT_DIR="$WORKSPACE_ROOT/.claude/reports"
DATE=$(date '+%Y-%m-%d')
REPORT_FILE="$REPORT_DIR/context-health-$DATE.md"

mkdir -p "$REPORT_DIR"

echo "=========================================="
echo "Daily Context Health Check"
echo "Date: $DATE"
echo "=========================================="
echo ""

# Start report
cat > "$REPORT_FILE" << EOF
# Context Health Report

**Date**: $DATE
**Generated**: $(date '+%Y-%m-%d %H:%M:%S')

---

## Size Validation

EOF

# Run validation
echo "Running size validation..."
"$SCRIPT_DIR/validate_context.sh" >> "$REPORT_FILE" 2>&1 || true

cat >> "$REPORT_FILE" << EOF

---

## Pattern Analysis

EOF

# Run pattern analysis
echo "Running pattern analysis..."
"$SCRIPT_DIR/analyze_patterns.sh" 7 >> "$REPORT_FILE" 2>&1 || true

cat >> "$REPORT_FILE" << EOF

---

## Improvement Suggestions

EOF

# Generate improvement suggestions
echo "Generating improvements..."
"$SCRIPT_DIR/improve_context.sh" --dry-run >> "$REPORT_FILE" 2>&1 || true

cat >> "$REPORT_FILE" << EOF

---

## Repository Status

| Repository | CLAUDE.md Size | Status |
|------------|----------------|--------|
EOF

# Generate repo status table
for repo_path in "$WORKSPACE_ROOT"/*/; do
    repo=$(basename "$repo_path")
    claude_file="$repo_path/CLAUDE.md"

    if [ -f "$claude_file" ]; then
        size=$(wc -c < "$claude_file")
        if [ "$size" -gt 8192 ]; then
            status="🔴 Over limit"
        elif [ "$size" -gt 6554 ]; then
            status="🟡 Warning"
        else
            status="🟢 OK"
        fi
        echo "| $repo | ${size} bytes | $status |" >> "$REPORT_FILE"
    fi
done

cat >> "$REPORT_FILE" << EOF

---

## Recommendations

Based on today's analysis:

1. **Size Optimization**: Review any files marked as over limit
2. **Pattern Review**: Check context-patterns.yaml for redundancy
3. **Reference Docs**: Ensure .claude/docs/ exists in all repos

---

*Report generated by context-management skill v2.0.0*
EOF

echo ""
echo "=========================================="
echo "Report generated: $REPORT_FILE"
echo "=========================================="

# Output summary
echo ""
echo "Quick Summary:"
grep -E "^(Violations|Warnings|OK):" "$REPORT_FILE" 2>/dev/null || echo "See report for details"
