@startuml ffs_scope

scale 2
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Tomato

title API579 FFS Assessment | pyintegrity Scope \n Corrosion/Erosion

package "Damage Classes" as dc {
component "Brittle Fracture" as brittle
component "Corrosion/Erosion" as corrosion
component "Crack-Like Flaws" as crack
component "Fire Damage" as fire
component "Creep Damage" as creep
component "Mechanical Damage" as mechanical
component "Fatigue Damage" as Fatigue
}

package "Corrosion/Erosion" as ce {
    package "pyintegrity Scope" as pyintegrityscope {
    agent "Part4 \n Assessment of General Metal Loss" as corrosion_part4
    agent "Part5 \n Assessment of Localized Metal Loss" as corrosion_part5
    }
agent "Part6 \n Assessment of Pitting Damage" as corrosion_part6
agent "Part7 \n Assessment of Blisters" as corrosion_part7
}

corrosion --> corrosion_part4
corrosion_part4 --> corrosion_part5
corrosion_part5 --> corrosion_part6
corrosion_part6 --> corrosion_part7

footer
%date("yyyy.MM.dd' at 'HH:mm")
%filename()
end footer

@enduml