@startuml ffs_methodology_general_metal
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Tomato

title FFS Methodology \n Corrosion/Erosion  \n General Metal Loss

(*) --> Review Design Data
        note right
            Pipe data 
            Operating Pressure
            Design Code, tmin
                See pyprespipe library
            FCA (Future Corrosion Allowance)
            etc.
        end note

    --> Review Measured Wall Thickness Data
        note right
            Methods used
            Critical thickness profile
            Data resolution
            Data accuracy
            etc.            
        end note

    --> Perform Level 1, Part 4
        if "not Acceptable" then
        --> Perform Level 2, Part 4
        if "not Acceptable" then
            --> Perform Level 3, Part 4

    --> Analysis Results
        note right
            Future Corrosion Allowance (FCA)
            Recommendations: 
                Repairs and remediations
                Next inspection
                Future monitoring requirements
        end note

footer
%date("yyyy.MM.dd' at 'HH:mm")
%filename()
end footer

@enduml