# =============================================================================
# Digital Model — Local Legal Deny List
# =============================================================================
# Extends the global workspace-hub deny list.
# Contains patterns specific to sanitized OrcaFlex model sources (s7).
#
# Severity levels:
#   block — fail the scan, PR cannot proceed
#   warn  — flag but allow to proceed
# =============================================================================

version: "1.1"
updated: "2026-02-20"

# Client project names and codenames
client_references:
  - pattern: "Ballymore"
    case_sensitive: false
    severity: block
    description: "Client deepwater project name"
  - pattern: "Candies"
    case_sensitive: true
    severity: block
    description: "Installation vessel name"
  - pattern: "WyatteCandies"
    case_sensitive: false
    severity: block
    description: "Vessel type identifier"
  - pattern: "WyattCandies"
    case_sensitive: false
    severity: block
    description: "Vessel type identifier variant"
  - pattern: "Seven Arctic"
    case_sensitive: false
    severity: block
    description: "Installation vessel name"
  - pattern: "7arctic"
    case_sensitive: false
    severity: block
    description: "Vessel shorthand"
  - pattern: "Shell Perdido"
    case_sensitive: false
    severity: block
    description: "Client project name"
  - pattern: "Perdido South"
    case_sensitive: false
    severity: block
    description: "Client project location"
  - pattern: "Talos Venice"
    case_sensitive: false
    severity: block
    description: "Client project name"
  - pattern: "talos_venice"
    case_sensitive: false
    severity: block
    description: "Client project name (snake_case)"
  - pattern: "BP_MD2"
    case_sensitive: true
    severity: block
    description: "Client project code"
  - pattern: "ONGC"
    case_sensitive: true
    severity: block
    description: "Client operator name"
  - pattern: "Limerock"
    case_sensitive: false
    severity: block
    description: "Client pipeline route name"
  - pattern: "SS7A2365"
    case_sensitive: false
    severity: block
    description: "User/machine identifier"
  - pattern: "USNGL23LR3"
    case_sensitive: false
    severity: block
    description: "User/machine identifier"
  - pattern: "Marco Polo"
    case_sensitive: false
    severity: block
    description: "Offshore TLP platform name"
  - pattern: "Caesar Tonga"
    case_sensitive: false
    severity: block
    description: "Subsea tieback project name"
  - pattern: "Lucius"
    case_sensitive: false
    severity: block
    description: "Offshore spar platform name"
  - pattern: "GC.?518"
    case_sensitive: false
    severity: block
    description: "Gulf of Mexico lease block identifier"
  - pattern: "K2 West"
    case_sensitive: false
    severity: block
    description: "Pipeline/flowline name"

  # --- Saipem Yellowtail (GYYT) CP calculation sources ---
  - pattern: "Yellowtail"
    case_sensitive: false
    severity: block
    description: "Client deepwater field name (Guyana Yellowtail)"
  - pattern: "GYYT"
    case_sensitive: true
    severity: block
    description: "Project document prefix — Guyana Yellowtail"
  - pattern: "GYFI"
    case_sensitive: true
    severity: block
    description: "Project document prefix — Guyana Fifteen field"
  - pattern: "TQ-YT"
    case_sensitive: false
    severity: block
    description: "Technical query prefix — Yellowtail project"
  - pattern: "ExxonMobil"
    case_sensitive: false
    severity: block
    description: "Client operator name"
  - pattern: "SBM Offshore"
    case_sensitive: false
    severity: block
    description: "FPSO owner/operator name"

  # --- ACMA B1522 (Woodfiber LNG / SLHR) CP calculation sources ---
  - pattern: "Woodfiber"
    case_sensitive: false
    severity: block
    description: "Client LNG project name"
  - pattern: "WoodFiber"
    case_sensitive: false
    severity: block
    description: "Client LNG project name variant"
  - pattern: "WLNG"
    case_sensitive: true
    severity: block
    description: "Project abbreviation — Woodfiber LNG"
  - pattern: "350106"
    case_sensitive: false
    severity: block
    description: "Client project document number prefix (B1522)"
  - pattern: "B1522"
    case_sensitive: true
    severity: block
    description: "ACMA internal project reference number"

# Files/paths excluded from scanning (glob patterns)
exclusions:
  - ".legal-deny-list.yaml"
  - ".git/"
  - "*.lock"
  - "__pycache__/"
  - "sanitization_audit.json"
  - "scripts/sanitize_s7_models.py"
  - "scripts/extract_s7_specs.py"
  - "specs/modules/"
  - ".claude/skills/"

default_severity: "block"
