# UV Configuration for DigitalModel

# Python version preference
python-preference = "managed"

# Package resolution settings
resolution = "highest"
prerelease = "if-necessary"

# Index configuration
index-url = "https://pypi.org/simple"
index-strategy = "first-index"

# Build settings
compile-bytecode = true

# Cache settings
no-cache = false

# Installation settings
link-mode = "copy"
reinstall = false

# Performance settings
concurrent-downloads = 50
concurrent-builds = 5
concurrent-installs = 5