@startuml aqwa_runs_automation
scale 3
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Tomato

title AQWA Runs \nAutomation

start

    note right
        **(IN PROGRESS)**
        Objective: modular file management and 
        analysis for easy updates/maintenance/reruns
    end note

    note right
        All files in ascii (.dat) format as much as possible
        - Single source of truth
        - Helps in  version control
    end note

    partition "Preprocess: Model Setup" {

        :Generate Decks for .dat files;
            note right
            Pros:
            - Easy to wire data: Single source of truth data source
            - Programming (Python, Fortran etc.) or MS DOS Batch 
            - License independent
            Cons:
            - ASCII format and picky to run: 
                i.e. manual edits, additional spaces etc. can cause it not run
            - Format archiac as opposed to advanced programming formatse 
                - eg yml format (eg: OrcaFlex)
            end note

        :Workbench UI;
            note right
             Manual operations to extract & plot
             Pros:
            - Good for beginners and adding new features
            - Parameter Sets to automate across programs and geometry
             Cons:
            - License dependency
            - Limited data definitions
                - eg: data given in .csv files can not be parametrized by filename
            - Manual operations
            - Slow to open and work in
            - Difficult to wire : Single source of truth data source
            end note

    }

    partition "Run" {
            note right
                Tools:
                 - Workbench
                 - AQWA.exe with .dat files
                 - MS DOS
                 - Python
            end note

        :Run AQWA;
            note right
                run_filename: *.dat
                - Noload: NOLD_*.dat
                - stability/equilibrium: STAB_*.dat
                - Dynamic: DYNA_*.dat
                run_script: aqwa_*.bat
                - Python External Force server: aqwa_efs_*.bat
                - Python cmd runs: aqwa_cmd_*.bat

            end note


    }

    partition "Postprocess" {
            note right
                Tools:
                 - MS DOS
                 - Programming (Python) for .LIS files
            end note

        :AQWAReader;
            note right
                Tools:
                 - AQWAReader (.csv files)
                    - Pros: Official support
                    - Cons: Too many csv files
            end note

        :AQWA output file (.LIS);
            note right
             Reading/Programming from .LIS files
             Pros:
                - Programming to get single shot at complete data 
             Cons:
                - multiple tables for single set of data
                    - Headers are repeated
                    - White Space between sets of each data
                - file format may change?
            end note


        :AQL - Excel Interface;
            note right
             Manual operations to extract & plot
            end note

        :Workbench - UI;
            note right
             Manual operations to extract & plot
             Pros:
                - Good/killer graphics and 3D plots etc 
             Cons:
                - Limited 
                    - Headers are repeated
                    - White Space between sets of each data
                - file format may change?
                - Many manual operations to extract outputs
            end note

        :Py - Python;
            note right
             scripts:
             - post_dm
             - post_au
            end note

    }

stop

footer
%date("yyyy.MM.dd' at 'HH:mm")
%filename()
end footer

@enduml
