# Input Parameters for Parametric Analysis
# Source: A03 Jumper to high tower.yml
# Generated: 2026-01-18 22:18:00

wind_speed: 0
water_density: 1.025
stage_durations:
- 16
- 144
hs: 7.5
tp: 16
wave_direction: 270

