library: digitalmodel
basename: orcaflex_post_process
default:
  log_level: INFO
  config:
    overwrite:
      output: true
parallel_processing:
  enabled: true
  max_workers: auto

... [truncated] ...
