# Basic Comparative Analysis Configuration
# Use this template for standard mooring comparative analysis

# File management configuration
file_management:
  # Directory containing CSV analysis files (relative to config file)
  input_directory: ../output/.csv
  
  # Base output directory for results (relative to config file)
  output_directory: ../output

# Analysis settings
analysis:
  # File pattern for CSV files
  pattern: "*.csv"
  
  # Analysis components to include
  components:
    pretension: true
    stiffness: true
    line_groups: true
    fender_forces: true

# Output configuration
output:
  # Report output path (relative to config file or absolute)
  report: ../output/report/analysis_report.md
  
  # Visualizations directory (relative to config file or absolute)
  visualizations: ../output/comparative_analysis
  
  # Report settings
  report_settings:
    include_executive_summary: true
    include_recommendations: true
    include_visualizations: true

# Visualization settings
visualization:
  # Figure size in inches (width, height)
  figure_size: [12, 8]
  
  # DPI for saved figures
  dpi: 100
  
  # Style (matplotlib styles: default, seaborn, ggplot, etc.)
  style: seaborn-v0_8-darkgrid