# Quick Analysis Configuration
# Minimal configuration for fast comparative analysis

# Simple file management
input_directory: ./.csv
output_directory: ./analysis_output

# Use all CSV files
pattern: "*.csv"

# Quick output
output:
  report: ./analysis_report.md
  visualizations: ./plots