# Input Parameters for Parametric Analysis
# Source: Pipeline spanning (lay to rough seabed).yml
# Generated: 2026-01-18 21:51:41

current_speed: 0
wind_speed: 0
water_density: 1.025
stage_durations:
- 10
- 500
hs: 0
tp: 8
wave_direction: 180

