# Input Parameters for Parametric Analysis
# Source: A05 Catenary with semisub.yml
# Generated: 2026-01-18 21:50:53

water_depth: 6560
wind_speed: 0
water_density: 63.9886595905483
stage_durations:
- 14
- 70
hs: 25
tp: 14
wave_direction: 180

