# Input Parameters for Parametric Analysis
# Source: C09 Fenders.yml
# Generated: 2026-01-18 22:18:07

water_depth: 50
wind_speed: 0
water_density: 1.025
stage_durations:
- 20
- 300
wave_direction: 180

