# Input Parameters for Parametric Analysis
# Source: H01 Chinese lantern.yml
# Generated: 2026-01-18 21:52:06

water_depth: 28
current_speed: 0.75
wind_speed: 0
water_density: 1.024
stage_durations:
- 10
- 30
hs: 8
tp: 10
wave_direction: 350

