# Input Parameters for Parametric Analysis
# Source: D03 Lay on tower.yml
# Generated: 2026-01-18 22:18:09

water_depth: 300
current_speed: 0
wind_speed: 0
water_density: 1.025
stage_durations:
- 8
- 16
- 16
- 16
- 16
hs: 0
tp: 10
wave_direction: 180

