@startwbs work_etiquette

scale 2
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Tomato

title Engineering \n Work Etiquette

* Engineering 

** Data : Github
*** rep: digitalmodel \ndes:engineering tools \ndir: docs, src(or code)
*** rep: assetutilities \ndes: general tools \ndir: docs, src(or code)
*** rep: company-repo \ndes:Company/project data \ndir: project \ntypically private repo



footer
%date("yyyy.MM.dd' at 'HH:mm")
%filename()
end footer

@endwbs
