@startuml modular_analysis
scale 3
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Tomato

title Modular Model Building \n OrcaFlex

start

    note right
        Objective: modular analysis for 
        easy updates/maintenance/reruns
    end note

    note right
        All files in .YML format
        Each partition box is a unique .yml file
    end note

    partition "Analysis Parameters" {

        :Analysis Parameters;
            note right
                Simulation time, time step, etc.
            end note

    }

    partition "Environment" {

        :Environment;
            note right
                Water Depth, others?
            end note

    }

    partition "Vessel Data" {

        :Vessel Data;
            note right
                Vessel Data
            end note

        :Vessel Settings;
            note right
                Draft, Type of solution, etc.
            end note


    }

    partition "Structure - Vessel Assets" {
        :Basic Structure;
            note right
                TBA
            end note

        :Variations & Parameters;
            note right
                TBA
            end note

        :Interface Data;
            note right
                Attachment relative to vessel
            end note

    }


    partition "Structure - Assets" {
        :Basic Structures:
        - Risers
        - Umbilical/UTH/Pots etc.;
            note right
                TBA
            end note

        :Variations & Parameters;
            note right
                TBA
            end note

    }


    partition "Interfaces" {
        :Structure to Vessel;
            note right
                Rigging, Chutes, Tensioners etc.
            end note

        :Other interfaces;
            note right
                For modelling etc.
            end note

    }

stop

footer
%date("yyyy.MM.dd' at 'HH:mm")
%filename()
end footer

@enduml
