@startuml yaml_edit_save_in_orcaflex
scale 3
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Tomato

title Edit and Save .YML Files\n OrcaFlex

    participant "analysis \nparameters" as analysis_params
    participant "vessel \ndata" as vessel_data
    participant "structure \neg: riser, Mudmat etc" as structure
    participant Environment
    participant "save as \n.dat" as save_dat
    participant "Parametric \nAnalysis" as parametric_analysis
    participant "run as \nyml" as run_yml
    participant "run as \ndat" as run_dat
    
    activate analysis_params
    activate vessel_data
    activate structure
    activate Environment

    alt .dat & (>1) .yml run
    
        analysis_params-> vessel_data:.dat
        vessel_data-> structure:.yml
        structure-> Environment:.yml
        Environment-> run_yml:.yml
        note over run_yml
        - modular to great extent
        - all .yml files can be modified in NotePad++
        - OrcaFlex license required to edit .dat files
        end note

        note over structure: (or)
        analysis_params-> vessel_data:.dat
        vessel_data-> structure:.yml
        structure-> Environment:.yml
        Environment-> save_dat:.yml
        save_dat-> run_dat:.dat

        note over run_dat
            - OrcaFlex license required to edit .dat files
            - Save as .dat in last stage 
              breaks connections 
              with all previous input files
        end note

    end group


    alt .yml: all yml run
   
        analysis_params-> vessel_data:.yml
        vessel_data-> structure:.yml
        structure-> Environment:.yml
        Environment-> run_yml:.yml

        note over run_yml
            <b>Advantages:</b> modular design
            - individual files can be modified in NotePad++
            - no OrcaFlex license required
            - compare each .yml in NotePad++ 
              to review changes
        end note


        note over structure: (or)
        analysis_params-> vessel_data:.yml
        vessel_data-> structure:.yml
        structure-> Environment:.yml
        Environment-> parametric_analysis:.yml
        note over parametric_analysis
            <b>Advantages:</b>
            - For sensitivity analysis
            - Ability to inject parameters 
              eg. Drag sensitivity etc.
        end note

        parametric_analysis-> run_yml:.yml


    end group

footer
%date("yyyy.MM.dd' at 'HH:mm")
%filename()
end footer

@enduml