@startuml yaml_runs_in_orcaflex
scale 3
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Tomato

title Run .DAT and/or .YML \n OrcaFlex

    participant "analysis \nparameters" as analysis_params
    participant "vessel \ndata" as vessel_data
    participant "structure \neg: riser, Mudmat etc" as structure
    participant Environment
    participant "save as \n.dat" as save_dat
    participant "run as \nyml" as run_yml
    participant "run as \ndat" as run_dat
    
    activate analysis_params
    activate vessel_data
    activate structure
    activate Environment
    activate run_yml

    alt one(1) .dat run

        analysis_params-> run_dat:all_data.dat
        note over run_yml
            - typical test runs
            - OrcaFlex license required to edit .dat files
        end note

   
    end group

    alt .dat & .yml run

        analysis_params-> Environment:all_data.dat
        Environment-> run_yml:.yml
        note over run_yml 
            - typical runs on servers
            - environment data in .yml overrides \n .dat file
        end note

    end group

    alt .dat & (>1) .yml run

        analysis_params-> vessel_data:.dat
        vessel_data-> structure:.yml
        structure-> Environment:.yml
        Environment-> run_yml:.yml
        note over run_yml: Run the last .yml file

        note over structure: (or)
        analysis_params-> vessel_data:.dat
        vessel_data-> structure:.yml
        structure-> Environment:.yml
        Environment-> save_dat:.yml
        save_dat-> run_dat:.dat

        note over run_dat: Save as .dat at final stage to run
    
    end group


    alt .yml: all yml run
   
        analysis_params-> vessel_data:.yml
        vessel_data-> structure:.yml
        structure-> Environment:.yml
        Environment-> run_yml:.yml

        note over run_yml: Run the last .yml file

    end group



footer
%date("yyyy.MM.dd' at 'HH:mm")
%filename()
end footer

@enduml