# OrcaWave Diffraction Analysis - Base Configuration Template
# This is a generic template for any vessel diffraction analysis
# Copy and modify for specific vessels

analysis:
  name: "Sea Cypress_Diffraction"
  type: "diffraction"
  description: "Hydrodynamic diffraction analysis"
  vessel:
    name: "Sea Cypress"
    geometry: "Sea Cypress_0.25 Mesh_Binary.stl"
    geometry_path: "specs/modules/orcawave/sea-cypress-diffraction-analysis/inputs/geometry"
    
environment:
  water_depth: 100.0        # meters - deep water assumption
  water_density: 1025.0     # kg/m³ - seawater
  gravity: 9.81            # m/s²
  kinematic_viscosity: 1.19e-6  # m²/s at 15°C
  
mesh_settings:
  panel_size: 0.25         # meters - typical panel size
  max_aspect_ratio: 3.0    # maximum panel aspect ratio
  min_panel_area: 0.01     # m² - minimum panel area
  waterline_refinement: true
  convergence_check: true
  refinement_zones: []     # Can add specific zones if needed
  
frequency_range:
  start: 0.01             # rad/s - low frequency for drift forces
  end: 3.0                # rad/s - high frequency cutoff
  steps: 100              # number of frequency points
  distribution: "logarithmic"  # logarithmic or linear
  
wave_directions:
  start: 0                # degrees - head seas
  end: 180               # degrees - following seas
  increment: 15          # degrees - increment
  reference: "vessel_heading"  # reference frame
  symmetry: true         # exploit port/starboard symmetry
  
analysis_options:
  radiation_analysis: true      # compute added mass and damping
  diffraction_analysis: true    # compute wave excitation forces
  qtf_calculation: false        # quadratic transfer functions
  remove_irregular_frequencies: true
  irregular_frequency_method: "extended_boundary"
  
solver_settings:
  method: "direct"              # direct or iterative
  precision: "double"           # single or double
  tolerance: 1.0e-6            # convergence tolerance
  max_iterations: 1000         # for iterative solver
  preconditioner: "diagonal"    # diagonal, ilu, or none
  
outputs:
  formats:
    - type: "spreadsheet"
      format: "xlsx"
      include_plots: true
      filename: "Sea Cypress_hydrodynamics.xlsx"
      
    - type: "csv"
      separate_files: true
      directory: "./csv_outputs/"
      
    - type: "database"
      format: "hdf5"
      compression: true
      filename: "Sea Cypress.h5"
      
    - type: "orcaflex"
      format: "yml"
      vessel_type: true
      filename: "Sea Cypress_vessel_type.yml"
      
  directory: "./results/"
  create_subdirectories: true
  timestamp_outputs: true
  
  result_components:
    - added_mass_matrix         # 6x6 frequency dependent
    - damping_matrix            # 6x6 frequency dependent
    - excitation_forces         # 6 DOF complex forces
    - excitation_moments        # 6 DOF complex moments
    - response_amplitude_operators  # if vessel mass defined
    - mean_drift_forces         # if QTF enabled
    - pressure_distribution     # panel pressures
    - wave_elevation           # free surface elevation
    
computation:
  parallel_workers: 4          # number of parallel processes
  memory_limit: "16GB"         # maximum memory usage
  disk_cache: true            # use disk caching for large problems
  cache_directory: "./cache/"
  gpu_acceleration: false      # use GPU if available
  
  resource_management:
    priority: "normal"         # low, normal, high
    cpu_affinity: "auto"       # auto or specific cores
    memory_allocation: "adaptive"  # fixed or adaptive
    
quality_checks:
  mesh_quality:
    check_closure: true        # verify watertight mesh
    check_normals: true        # verify outward normals
    check_duplicates: true     # remove duplicate panels
    check_aspect_ratio: true   # warn on high aspect ratios
    
  physics_validation:
    check_displacement: true   # verify displaced volume
    check_waterplane: true     # verify waterplane area
    check_symmetry: true       # check geometric symmetry
    check_stability: true      # basic stability check
    
  results_validation:
    check_reciprocity: true    # radiation-diffraction reciprocity
    check_energy: true         # energy conservation
    check_asymptotes: true     # high/low frequency limits
    benchmark_comparison: false  # compare with reference
    
logging:
  level: "INFO"               # DEBUG, INFO, WARNING, ERROR
  file: "orcawave_analysis.log"
  console: true
  detailed_progress: true
  performance_metrics: true
  
metadata:
  project: "B1512 Sea Cypress Analysis"
  author: "OrcaWave Module Agent"
  version: "1.0.0"
  created: "2025-09-02"
  description: "Diffraction analysis configuration"
  tags:
    - "diffraction"
    - "hydrodynamics"
    - "orcaflex_integration"