# Rainflow Analysis with Visualization Configuration
# Signal Analysis Module for Fatigue Assessment
# Created: 2025-01-23
# Version: 1.0.0

# ============================================================================
# PROJECT IDENTIFICATION
# ============================================================================
project:
  name: "Rainflow Counting and Signal Analysis"
  description: "Rainflow cycle counting with FFT analysis and visualization"
  analysis_type: "rainflow-with-visualization"
  project_id: "RF-VIS-001"
  version: "1.0.0"
  date: "2025-01-23"
  
# ============================================================================
# INPUT DATA CONFIGURATION
# ============================================================================
input_data:
  # Time trace data configuration
  timetrace:
    # Folder containing input CSV files with time trace data
    data_folder: "timetrace"
    
    # Input file format
    file_format: "csv"
    name_pattern: "{config}_FC{fc_number:03d}_Strut{strut_number}_scaled_tension.csv"
    filter_pattern: "*_scaled_tension.csv"

    # Column containing the tension data
    data_column: "Scaled Tension (kN)"
    
    # Time column (if present)
    time_column: "time"
    
    # Sampling parameters
    sampling:
      dt: 0.1  # Time step in seconds
      auto_detect: true  # Auto-detect from time column if available
    
  # Data preprocessing options
  preprocessing:
    # Remove mean (detrend)
    remove_mean: false
    
    # Apply filtering
    filter:
      enabled: false
      type: "butterworth"
      cutoff_freq: 10.0  # Hz
      order: 4
      
# ============================================================================
# RAINFLOW COUNTING METHOD
# ============================================================================
rainflow_counting:
  # Counting method configuration
  method:
    # Algorithm type
    algorithm: "ASTM E1049"  # Standard rainflow counting algorithm
    
    # Determine time trace length from data
    auto_detect_length: true
    
  # Binning parameters for tension RANGE (always positive)
  binning:
    # Number of bins for cycle counting
    num_bins: 50
    
    # Binning method
    method: "linear"  # Linear binning for tension range
    
    # Minimum bin value for RANGE (always positive)
    min_range: 0.0  # Tension range starts from zero
    
    # Maximum bin value for RANGE
    max_range: 1000  # Maximum expected tension range in kN
    
    # Binning for MEAN values (can be negative)
    mean_binning:
      enabled: true
      min_mean: -500  # Minimum mean tension (can be negative/compression)
      max_mean: 500   # Maximum mean tension (positive/tension)
    
  # Cycle extraction parameters
  cycle_extraction:
    # Half-cycle or full-cycle counting
    count_type: "full-cycles"  # Changed to full cycles (2, 2.5, 5.5 etc.)
    
    # Minimum range threshold (cycles below this are ignored)
    min_range_threshold: 0.0
    
    # Residue handling
    handle_residue: true
    
  # Cycle scaling parameters
  cycle_scaling:
    # Output cycle counts for time trace duration
    timetrace_cycles: true
    
    # Scale to annual cycles based on time trace length
    annual_cycles: true
    scaling_method: "simple"  # annual_cycles = timetrace_cycles * (8760 / timetrace_hours)
    
    # Annual duration (hours)
    annual_hours: 8760  # 365 days * 24 hours
    
    # Use actual time trace duration from data
    use_actual_duration: true
    
# ============================================================================
# FFT ANALYSIS CONFIGURATION
# ============================================================================
fft_analysis:
  # Window configuration
  window:
    # Window type for FFT
    type: "hanning"  # Options: hanning, hamming, blackman, bartlett, rectangular
    
    # Window length in seconds
    length_seconds: 500
    
    # Overlap percentage between windows
    overlap_percent: 50
    
  # FFT parameters
  parameters:
    # Sampling frequency (Hz) - auto-detect from data if not specified
    sampling_frequency: "auto"  # Will detect from time column (expected 0.1s = 10 Hz)
    expected_dt: 0.1  # Expected time step in seconds
    
    # Number of FFT points (power of 2)
    nfft: "auto"  # Will use next power of 2 from window length
    
    # Frequency range for plotting (Hz)
    freq_range:
      min: 0.0
      max: 5.0  # Typical for structural dynamics
      
  # Spectral analysis options
  spectral:
    # Type of spectrum to compute
    spectrum_type: "power"  # Options: power, amplitude, psd
    
    # Scaling
    scaling: "density"  # Options: density, spectrum
    
    # Detrend before FFT
    detrend: "constant"  # Options: constant, linear, none
    
# ============================================================================
# OUTPUT CONFIGURATION
# ============================================================================
output:
  # Output folder structure
  folders:
    # Base output folder
    base: "specs/modules/signal-analysis/rainflow_with_visualization"
    
    # Rainflow results folder
    rainflow_results: "output"
    
    # Visualization folder
    visualizations: "visualization"
    
  # File naming pattern
  file_naming:
    # Pattern for output files
    pattern: "{config}_FC{fc_number:03d}_Strut{strut_number}_{type}"
    
    # File types
    types:
      rainflow: "rainflow"
      fft: "fft"
      summary: "summary"
      
  # Output file formats
  formats:
    # Rainflow counting results
    rainflow_output:
      format: "csv"
      include_headers: true
      columns:
        - "Range (kN)"  # Always positive (magnitude of tension cycle)
        - "Mean (kN)"   # Can be positive or negative
        - "Cycles_TimeTrace"
        - "Cycles_Annual"
        - "Bin_Number"
        - "Damage_Contribution"
        
    # Summary statistics
    summary_output:
      format: "csv"
      include_metadata: true
      
    # Individual file outputs
    individual_outputs: true
      
    # Aggregate summary report
    aggregate_summary:
      enabled: true
      filename: "rainflow_analysis_summary.csv"
      include_statistics: true
      statistics:
        - "total_cycles"
        - "max_range"
        - "mean_range"
        - "damage_sum"
        - "fatigue_life_estimate"
      
# ============================================================================
# VISUALIZATION CONFIGURATION
# ============================================================================
visualization:
  # FFT visualization
  fft_plot:
    # Enable FFT plot generation
    enabled: true
    
    # Output format
    format: "png"
    
    # Plot settings
    settings:
      figure_size: [12, 8]
      dpi: 150
      grid: true
      log_scale_y: true
      
    # Plot components
    components:
      - "magnitude_spectrum"
      - "phase_spectrum"
      - "power_spectral_density"
      
  # Rainflow visualization
  rainflow_plot:
    # Enable rainflow visualization
    enabled: true
    
    # Output format
    format: "png"
    
    # Plot type (reference to existing visualization)
    reference_style: "specs/modules/fatigue-analysis/reference-seastate-scaling-fatigue/rev_0/core/output/verification/step_by_step/figures/rainflow_visualization.png"
    
    # Plot settings
    settings:
      figure_size: [14, 10]
      dpi: 150
      
    # 3D Rainflow Matrix Plot Customization
    rainflow_3d_plot:
      # Main plot title
      title: "Rainflow Matrix - 3D Scatter Plot"
      
      # Subplot titles
      subplot_titles:
        scatter_3d: "Rainflow Matrix - 3D Scatter Plot"
        projection_2d: "Rainflow Matrix - Top View"
      
      # Axis labels
      axes_labels:
        x_axis: "Tension Range (kN)"  # X-axis: Range (always positive)
        y_axis: "Mean Tension (kN)"   # Y-axis: Mean (can be negative)
        z_axis: "Cycle Count"        # Z-axis: Count
        colorbar: "Cycle Count"      # Colorbar label
      
      # Viewing angle for 3D plot
      view_angle:
        elevation: 20  # Elevation angle in degrees
        azimuth: 45   # Azimuth angle in degrees
      
      # Color scheme
      colormap: "viridis"  # Options: viridis, plasma, inferno, magma, cividis, Blues, Greens
      
      # Marker style
      marker:
        style: "o"  # Marker style: o (circle), s (square), ^ (triangle), etc.
        alpha: 0.7  # Transparency (0-1)
        edge_color: "black"  # Edge color for markers
        edge_width: 0.3  # Edge width
      
      # Statistics box
      show_statistics: true  # Show statistics box on 2D projection
      statistics_position: [0.02, 0.98]  # Position (x, y) in axes coordinates
      
    # Plot components (in priority order)
    components:
      - "time_trace_with_cycles"  # Time trace with identified peaks/valleys/cycles
      - "rainflow_matrix"  # 3D matrix plot (Range vs Mean vs Count)
      - "cycle_histogram"  # Cycle count histogram by tension range
      - "range_mean_scatter"  # Range-mean scatter plot
      - "cumulative_damage"  # Cumulative damage plot
      
  # Time series visualization
  timeseries_plot:
    # Enable time series plot
    enabled: true
    
    # Plot settings
    settings:
      figure_size: [14, 6]
      show_peaks: true
      show_valleys: true
      highlight_cycles: false
      
  # Combined report
  combined_report:
    # Generate combined PDF report
    enabled: true
    format: "pdf"
    include_tables: true
    include_statistics: true
    
# ============================================================================
# PROCESSING OPTIONS
# ============================================================================
processing:
  # Parallel processing
  parallel:
    enabled: true
    num_workers: 4
    
  # Batch processing
  batch:
    # Process multiple files
    process_all_files: true
    
    # Continue on error
    continue_on_error: true
    
  # Memory management
  memory:
    # Maximum memory usage (GB)
    max_memory_gb: 8
    
    # Use memory mapping for large files
    use_mmap: true
    
# ============================================================================
# VALIDATION AND QUALITY CONTROL
# ============================================================================
validation:
  # Input validation
  input_checks:
    # Check for data completeness
    check_completeness: true
    
    # Maximum allowed missing data (%)
    max_missing_percent: 5.0
    
    # Check for outliers
    check_outliers: true
    outlier_threshold: 6.0  # Standard deviations
    
  # Output validation
  output_checks:
    # Verify rainflow sum equals input cycles
    verify_cycle_count: true
    
    # Check for negative ranges
    check_negative_ranges: true
    
    # Validate FFT results
    validate_fft: true
    
  # Quality metrics
  quality_metrics:
    # Calculate signal-to-noise ratio
    calculate_snr: true
    
    # Calculate statistical moments
    calculate_moments: true
    
    # Generate quality report
    generate_qc_report: true
    
# ============================================================================
# LOGGING AND DEBUGGING
# ============================================================================
logging:
  # Logging level
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR, CRITICAL
  
  # Log file location
  log_file: "rainflow_analysis.log"
  
  # Console output
  console_output: true
  
  # Include timestamps
  include_timestamps: true
  
  # Performance logging
  log_performance: true
  
# ============================================================================
# EXECUTION SETTINGS
# ============================================================================
execution:
  # Error handling
  error_handling:
    # Stop on first error
    stop_on_error: false
    
    # Save error log
    save_error_log: true
    
    # Error log location
    error_log_file: "errors.log"
    
  # Progress tracking
  progress:
    # Show progress bar
    show_progress: true
    
    # Update interval (seconds)
    update_interval: 1.0
    
  # Resource limits
  limits:
    # Maximum execution time (seconds)
    max_execution_time: 3600
    
    # Maximum file size (MB)
    max_file_size_mb: 1000
    
# ============================================================================
# METADATA
# ============================================================================
metadata:
  # Configuration metadata
  created_date: "2025-01-23"
  created_by: "Signal Analysis Configuration Tool"
  last_modified: "2025-01-23"
  config_version: "1.0.0"
  
  # Analysis description
  notes: |
    This configuration file defines parameters for rainflow cycle counting
    and FFT analysis with visualization. The analysis pipeline includes:
    
    1. Load time trace data from CSV files (tension can be positive/negative)
    2. Perform rainflow cycle counting with specified binning
       - Tension RANGE is always positive (magnitude of cycle)
       - Tension MEAN can be positive (tension) or negative (compression)
    3. Execute FFT analysis with windowing
    4. Generate visualizations (rainflow matrix, FFT plots)
    5. Export results in CSV format
    
    The configuration follows the repository standard format and integrates
    with the existing fatigue analysis modules.
    
    Important: The tension time series can contain both positive (tension) and 
    negative (compression) values. The rainflow counting produces:
    - Range values: Always positive (|max - min| of each cycle)
    - Mean values: Can be positive or negative ((max + min)/2)
    
  # References
  references:
    - "ASTM E1049-85: Standard Practices for Cycle Counting in Fatigue Analysis"
    - "Downing, S. D., Socie, D. F. (1982). Simple rainflow counting algorithms"
    - "Repository fatigue analysis module documentation"