# Input Parameters for Parametric Analysis
# Source: F04 Payload transfer.yml
# Generated: 2026-01-18 22:18:19

water_depth: 100
current_speed: 0
wind_speed: 0
water_density: 1.025
stage_durations:
- 10
- 140
wave_direction: 270

