#!/usr/bin/env bash
# Human-gated restore of recovered issue bodies. Review each file first.
# Generated by recover_issue_bodies.py — NOT run automatically.
set -euo pipefail

gh issue edit 13 --repo vamseeachanta/digitalmodel --body-file docs/issue-body-recovery/issue-13.md  # OrcaFlex | Installation | Modal Analysis
gh issue edit 18 --repo vamseeachanta/digitalmodel --body-file docs/issue-body-recovery/issue-18.md  # OrcaFlex | SeastateRAOs | Filtering for analysis
gh issue edit 19 --repo vamseeachanta/digitalmodel --body-file docs/issue-body-recovery/issue-19.md  # OrcaFlex | Postprocess | Visualizations | For a/ QA and b/ Report
gh issue edit 20 --repo vamseeachanta/digitalmodel --body-file docs/issue-body-recovery/issue-20.md  # code_dnvrph103 | If CoV is same as CoG, leave it null
gh issue edit 23 --repo vamseeachanta/digitalmodel --body-file docs/issue-body-recovery/issue-23.md  # dnvrph103 | Create common functions from rectangular and circular files
gh issue edit 28 --repo vamseeachanta/digitalmodel --body-file docs/issue-body-recovery/issue-28.md  # engg debt | Fatigue | ship design | spectral-based fatigue analysis
gh issue edit 29 --repo vamseeachanta/digitalmodel --body-file docs/issue-body-recovery/issue-29.md  # engg debt | fatigue | SN Curve module
