# Master Input Configuration - Production Template
# Fatigue Analysis Pipeline Configuration
# This file consolidates all input parameters and file references for production analysis

default:
  # Analysis identification
  analysis_name: "Production Fatigue Analysis"
  analysis_type: "reference-seastate-scaling"
  project_id: "PROD-XXX"  # Update with actual project ID
  structure: "StructureName"  # Update with actual structure name
  location: "Field Name"  # Update with field location
  water_depth_m: 1500  # Update with actual water depth
  
  # Analysis parameters
  parameters:
    sample_duration_seconds: 10800  # 3 hours typical for production
    time_step_seconds: 0.1          # OrcaFlex typical output step
    sample_points: 108000            # Duration / time_step
    seconds_per_year: 31557600      # 365.25 * 24 * 3600
    design_life_years: 25           # Typical offshore design life
    safety_factor: 10               # FLS safety factor per standards
    
  # File paths - Reference conditions
  reference_files:
    base_directory: "path/to/reference/data"  # Update path
    file_pattern: "*_ref_*.csv"
    files:  # List all reference condition files
      - "reference_surge.csv"
      - "reference_sway.csv"
      - "reference_heave.csv"
      - "reference_roll.csv"
      - "reference_pitch.csv"
      - "reference_yaw.csv"
    column_name: "Effective Tension (kN)"  # Update if different
    
  # File paths - Sea state conditions  
  seastate_files:
    base_directory: "path/to/seastate/data"  # Update path
    file_pattern: "*_FC*_*.csv"
    # Map fatigue condition IDs to actual file names
    files:
      FC001: "seastate_FC001_operational.csv"
      FC002: "seastate_FC002_operational.csv"
      FC003: "seastate_FC003_moderate.csv"
      FC004: "seastate_FC004_severe.csv"
      # Add all fatigue conditions...
    column_name: "Effective Tension (kN)"  # Update if different
    
  # Fatigue conditions (site-specific metocean data)
  fatigue_conditions:
    file: "path/to/metocean/scatter_diagram.csv"  # Update path
    # Production data from site-specific metocean analysis
    data:
      # Update with actual metocean scatter diagram
      # Ensure occurrence percentages sum to 100%
      FC001:
        wind_speed_mps: 0  # Update
        wind_dir_deg: 0    # Update
        hs_m: 0.0          # Update
        tp_s: 0.0          # Update
        wave_dir_deg: 0    # Update
        occurrence_pct: 0  # Update
      # Add all fatigue conditions from scatter diagram...
        
  # Scaling factors (project-specific)
  scaling_factors:
    wind:
      reference_speed_mps: 10  # Verify with project specs
      exponent: 2               # API/DNV recommended
      formula: "(V/Vref)^2"
      min_scale: 0.01          # Minimum scaling factor
      max_scale: 10.0          # Maximum scaling factor
    wave:
      reference_hs_m: 2.0      # Update based on site
      exponent: 1              # Linear scaling typical
      formula: "Hs/Hsref"
      min_scale: 0.01
      max_scale: 10.0
      
  # Tension to stress conversion (structure-specific)
  tension_to_stress:
    file: "path/to/structural/tension_stress_calibration.csv"  # Update
    method: "linear_interpolation"
    # Project-specific calibration including:
    # - Cross-sectional area
    # - Stress concentration factors (SCF)
    # - Joint classification factors
    conversion_table:  # Update with actual calibration
      - tension_kN: 0
        stress_MPa: 0.0
      - tension_kN: 1000
        stress_MPa: 50.0  # Example - update with actual
      # Add complete calibration table...
    conversion_factor: null  # Will be derived from table
    includes_scf: true       # Confirm if SCF included
    scf_value: 2.5          # Document SCF if separate
    cross_section_m2: 0.01  # Document if needed
    
  # S-N curve parameters (material-specific)
  sn_curve:
    curve_type: "DNV-C"  # Or API, BS, etc.
    description: "Steel in seawater with cathodic protection"
    formula: "N = a * S^(-m)"
    parameters:
      a: 6.0e11  # Update based on:
      m: 3.0     # - Material (steel grade)
                 # - Environment (air/seawater/CP)
                 # - Joint classification
    stress_units: "MPa"
    thickness_correction: true  # Apply if t > 25mm
    thickness_mm: 50           # Actual thickness
    thickness_exponent: 0.25   # Per design code

    # Alternative curves if needed
    alternative_curves:
      high_stress:  # For stress > transition
        a: 1.0e12
        m: 5.0
        transition_mpa: 100
      mean_stress_correction: "Goodman"  # If applicable
    
  # Rainflow counting settings
  rainflow:
    method: "ASTM_E1049"       # Industry standard
    normalize_yearly: true      # Always true for FLS
    min_range_kN: 1.0          # Filter noise
    half_cycle_counting: true   # Include half cycles
    
  # Output settings
  output:
    base_directory: "output/production/${project_id}"  # Organized by project
    save_intermediate: true
    intermediate_files:
      step6_scaled: "01_scaled_tensions"
      step7_rainflow: "02_rainflow_counts"
      step8_stress: "03_stress_ranges"
      step9_sn: "04_cycles_to_failure"
      step10_damage: "05_damage_per_fc"
      step11_total: "06_total_damage"
      step12_life: "07_fatigue_life"
    final_results: "fatigue_assessment_results.yml"
    generate_report: true
    report_format: "docx"  # Word report for client
    generate_plots: true
    plot_formats: ["png", "pdf", "svg"]
    
  # Validation thresholds (per design codes)
  validation:
    min_fatigue_life_years: 25     # Design requirement
    max_damage_per_year: 0.04      # 1/25
    occurrence_sum_tolerance: 0.01
    min_cycles_for_analysis: 100   # Minimum cycles to include
    stress_range_cutoff_mpa: 1.0   # Ignore below this
    
  # Quality checks
  quality_checks:
    check_occurrence_sum: true     # Must sum to ~100%
    check_file_continuity: true    # No gaps in time series
    check_tension_bounds: true     # Realistic tension ranges
    max_tension_kN: 10000          # Flag if exceeded
    min_tension_kN: -1000          # Flag compression
    
  # Processing options
  processing:
    parallel_processing: true
    num_workers: 8              # For production runs
    chunk_size: 10000          # Points per chunk
    memory_limit_gb: 16       # Memory management
    verbose: false             # Less output for production
    debug_mode: false
    save_checkpoint: true      # Recovery from interruption
    checkpoint_interval: 10   # Save every N conditions
    
  # Compliance and standards
  compliance:
    design_code: "DNV-OS-E301"  # Or API-RP-2A, ISO 19902
    safety_class: "High"        # Safety classification
    inspection_level: "Annual"  # Affects FLS factors
    redundancy: "Non-redundant" # Affects safety factors
    
# Additional metadata
metadata:
  created_date: "2025-01-22"
  created_by: "Engineering Team"
  reviewed_by: "Lead Engineer"  # Update
  approved_by: "Project Manager" # Update
  version: "1.0.0"
  last_modified: "2025-01-22"
  
  # Project information
  project:
    client: "Client Name"
    contractor: "Contractor Name"
    classification_society: "DNV"  # Or ABS, BV, LR
    field_development: "Field Name Development"
    
  # Document control
  document_control:
    document_number: "DOC-XXX-XXX"
    revision: "A"
    status: "For Review"  # Draft/For Review/Approved
    
  notes: |
    Production configuration template for fatigue analysis.
    Update all placeholder values with project-specific data.
    Ensure all file paths are correct before running analysis.
    Validate metocean data sums to 100% occurrence.
    Review S-N curve selection with materials engineer.
    Confirm SCF values with structural analysis team.