# Input Parameters for Parametric Analysis
# Source: A02 Lazy S simple.yml
# Generated: 2026-01-18 22:17:58

water_depth: 100
current_speed: 1
wind_speed: 0
water_density: 1.025
stage_durations:
- 12
- 60
hs: 7
tp: 12
wave_direction: 315

