# Input Parameters for Parametric Analysis
# Source: B06 Running BOP.yml
# Generated: 2026-01-18 22:18:02

water_depth: 234
current_speed: 0
wind_speed: 0
water_density: 1.025
stage_durations:
- 25
- 150
wave_direction: 180

