# Input Parameters for Parametric Analysis
# Source: A04 Disconnecting turret system.yml
# Generated: 2026-01-18 21:50:45

water_depth: 200
current_speed: 1
wind_speed: 0
water_density: 1.025
stage_durations:
- 17.5
- 17.5
- 5
- 47.5
hs: 14.2
tp: 17.5
wave_direction: 0

