# Input Parameters for Parametric Analysis
# Source: F02 Passive compensation.yml
# Generated: 2026-01-18 22:18:18

water_depth: 100
current_speed: 0
wind_speed: 0
water_density: 1.025
stage_durations:
- 10
- 100
wave_direction: 180

