@startuml epic_seo_theory_backlinks
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Tomato

title SEO Theory \n Content

@startwbs
<style>
wbsDiagram {
  .greenyellow {
      BackgroundColor GreenYellow
  }
}
</style>
* Functional Website <<greenyellow>>
** Basic Checks


@endwbs

footer
%date("yyyy.MM.dd' at 'HH:mm")
%filename()
end footer
