%YAML 1.1
# OrcaWave Config using test_box.gdf
---
UnitsSystem: SI
SolveType: Potential formulation only
LoadRAOCalculationMethod: Both
PreferredLoadRAOCalculationMethod: Haskind
WaterDepth: 200
WaterDensity: 1.025
WavesReferredToBy: period (s)
ValidatePanelArrangement: false
PeriodOrFrequency:
- 6
- 8
- 10
- 12
- 15
WaveHeading:
- 0
- 45
- 90
- 135
- 180
Bodies:
- BodyName: TestBox
  BodyMeshFileName: test_box.gdf
  BodyMeshFormat: Wamit gdf
  BodyMeshLengthUnits: m
  BodyMeshPosition:
  - 0
  - 0
  - 0
  BodyMeshAttitude:
  - 0
  - 0
  - 0
  BodyIncludedInAnalysis: true
  BodyMeshSymmetry: None
  BodyInertiaSpecifiedBy: Radii of gyration (for a free-floating body)
  BodyCentreOfMass:
  - 0
  - 0
  - -5
  BodyRadiiOfGyrationRx, BodyRadiiOfGyrationRy, BodyRadiiOfGyrationRz:
  - - 10.0
    - 0
    - 0
  - - 0
    - 15.0
    - 0
  - - 0
    - 0
    - 15.0
  BodyRadiiOfGyrationOriginType: Body origin
  BodyConnectionParent: Free
  BodyFixedDOFx: false
  BodyFixedDOFy: false
  BodyFixedDOFz: false
  BodyFixedDOFRx: false
  BodyFixedDOFRy: false
  BodyFixedDOFRz: false
