# Input Parameters for Parametric Analysis
# Source: CALMBuoy_100YR_FM_R2_D1.yml
# Generated: 2026-01-18 21:53:32

water_depth: 32.8
current_speed: 1
wind_speed: 22.7
water_density: 1.025
stage_durations:
- 10
- 100
hs: 7.4
tp: 8.1
wave_direction: 0

