# Metocean Data Procurement Configuration Example
# Version: 1.0.0
# Reference: @specs/modules/data-procurement/metocean-data/spec.md

version: "1.0"

# Reference common components framework
# extends: "@specs/modules/data-procurement/common-components/spec.md"  # Documentation reference only

# Data source category
data_source:
  category: "metocean"
  description: "Meteorological and oceanographic data for offshore engineering"

# API provider configuration
apis:
  # Primary data source (highest quality, complete historical)
  primary: "ERA5"

  # Fallback sources (if primary unavailable)
  fallback:
    - "NOAA"
    - "Open-Meteo"

  # Specific API configurations
  ERA5:
    base_url: "https://cds.climate.copernicus.eu/api/v2"
    authentication:
      method: "api_key"
      key: "${ERA5_API_KEY}"  # Environment variable
    rate_limit:
      requests_per_minute: null  # Unlimited (fair use)
      burst_capacity: null
    data_format: "netcdf"

  NOAA:
    base_url: "https://www.ndbc.noaa.gov/data/realtime2/"
    authentication:
      method: "none"  # Public data
    rate_limit:
      requests_per_day: 1000  # Free tier
    data_format: "text/plain"

  Open-Meteo:
    base_url: "https://api.open-meteo.com/v1"
    authentication:
      method: "none"
    rate_limit:
      requests_per_minute: null  # Unlimited
    data_format: "json"

# Geographic location
location:
  # Option 1: Single point
  latitude: 29.5
  longitude: -88.5
  name: "Gulf of Mexico - Mississippi Canyon"

  # Option 2: Bounding box (for grid data)
  # bbox:
  #   north: 30.0
  #   south: 29.0
  #   east: -88.0
  #   west: -89.0

  # Water depth (for validation)
  water_depth: 1200  # meters

# Metocean parameters to retrieve
parameters:
  wave:
    - significant_wave_height  # Hs (m)
    - peak_period              # Tp (s)
    - mean_zero_crossing_period  # Tz (s)
    - wave_direction           # degrees (from)
    - wave_spectrum            # for detailed analysis

  wind:
    - wind_speed_10m           # m/s at 10m height
    - wind_direction_10m       # degrees (from)
    - wind_gust_10m            # m/s
    - wind_speed_100m          # m/s at 100m (for offshore wind)

  current:
    - surface_current_speed    # m/s
    - surface_current_direction  # degrees (to)
    - current_profile          # speed vs depth

  environmental:
    - water_temperature        # °C
    - air_temperature          # °C
    - air_pressure             # hPa
    - water_level              # m (tide + surge)

# Time range for data retrieval
time_range:
  # Option 1: Historical period
  start: "2000-01-01"
  end: "2023-12-31"
  resolution: "hourly"  # hourly, 3hourly, daily

  # Option 2: Recent/forecast
  # mode: "recent"
  # days_back: 30
  # forecast_days: 16

# Output configuration
output:
  format: "netcdf"  # netcdf, csv, json, parquet, orcaflex, aqwa
  path: "./data/metocean/"
  filename_pattern: "metocean_{location}_{start}_{end}.nc"

  # Unit system
  units: "SI"  # or "Imperial"

  # Coordinate system
  coordinate_system: "WGS84"  # or "UTM"

  # Include metadata
  include_metadata: true
  metadata:
    project: "Offshore Platform Design"
    analyst: "Engineering Team"
    purpose: "Environmental design loads"

# Caching configuration
caching:
  enabled: true
  ttl_days: 30  # Time to live for cached data
  tier: "L2"    # L1 (memory), L2 (Redis), L3 (disk)
  cache_directory: "./cache/metocean/"
  max_cache_size_gb: 10

# Quality control
quality_control:
  enabled: true

  # Range checks (reject unrealistic values)
  limits:
    wave_height:
      min: 0.0
      max: 30.0  # m (reject higher values as errors)
    wind_speed:
      min: 0.0
      max: 80.0  # m/s
    water_temperature:
      min: -2.0
      max: 35.0  # °C

  # Gap filling
  fill_gaps:
    enabled: true
    method: "linear"  # linear, spline, climatology
    max_gap_hours: 6  # Maximum gap size to fill

  # Outlier detection
  outlier_detection:
    enabled: true
    method: "iqr"  # iqr (interquartile range) or zscore
    threshold: 3.0

# Data processing
processing:
  # Spatial interpolation (if needed)
  interpolation:
    enabled: false
    method: "bilinear"  # bilinear, cubic, nearest

  # Temporal aggregation
  aggregation:
    enabled: false
    method: "mean"  # mean, max, min, percentile
    window: "1D"    # pandas frequency string

  # Extreme value analysis
  extremes:
    enabled: false
    return_periods: [1, 10, 50, 100]  # years
    distribution: "gumbel"  # gumbel, weibull, gev

# Analysis-specific settings
analysis:
  # OrcaFlex export settings
  orcaflex:
    wave_spectrum_type: "JONSWAP"
    current_profile_points: 10  # Number of depth points
    wind_profile_points: 5

  # AQWA export settings
  aqwa:
    wave_directions: [0, 15, 30, 45, 60, 90, 120, 135, 150, 165, 180]
    frequency_range:
      min: 0.1  # rad/s
      max: 2.0
      step: 0.05

# Validation against design standards
standards:
  check_compliance: true
  codes:
    - "API RP 2A-WSD"
    - "DNV-RP-C205"

  # Design criteria
  design_criteria:
    operating:
      max_wave_height: 5.0  # m
      max_wind_speed: 25.0  # m/s (50 knots)
    survival:
      return_period: 100  # years
      design_life: 25     # years

# Logging and monitoring
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  format: "json"  # json or text
  output:
    - type: "file"
      path: "./logs/metocean.log"
    - type: "console"

# Performance settings
performance:
  parallel_downloads: true
  max_workers: 4
  chunk_size: 1000  # Records per chunk for large datasets
  timeout_seconds: 300

# Notification settings
notifications:
  enabled: false
  # email:
  #   to: ["engineer@company.com"]
  #   on_completion: true
  #   on_error: true
