@startuml plate-buckling
skinparam titleBorderRoundCorner 14
skinparam titleBorderThickness 1
skinparam titleBorderColor black
skinparam titleBackgroundColor white

title plate buckling structure

start

:Input - Dimensions;
:Input - Loads;
:Calculation - Stress;
:Buckling Checks;

if (Acceptable) then
    ->Yes;
    :Proceed to Next Step;
else
    ->No;
    :Revise Inputs;
endif

stop


footer


%date("yyyy.MM.dd' at 'HH:mm")
%filename()
end footer

@enduml


