# content-hash: d7ac2b65d82307b7d3aaba03438a9fc0258c61d146ab2a505463b6fa3c8c3e2d
"""
Naval Architecture Constants

Auto-generated by doc-intelligence constants promoter.
Do not edit manually — re-run the promoter to update.
"""

# =============================================================================
# NAVAL ARCHITECTURE
# =============================================================================

WHERE_A_CROSSSECTIONAL_AREA_OF_STIFFENER_B = 0
"""where A = cross-sectional area of stiffener, B = 0 if uy is less than the elastic buckling stress
in the transverse direction in the absence of the stiffener, otherwise B is a function of the
stress level (see DNV CN 30.1). a= 1 for uniform ob,< 1 otherwise, and C= function of
critical shear stress, simplified, = 11s.
Girder Buckling
Girders are connected to the plate and may fail by plate induced failure or flange induced
failure. Plate induced failure results in the girder deflecting away from the plate with
yielding in compression at the connection between the girder and the plate. Flange induced
failure is caused by torsional buckling (see above) and is typically mitigated by the addition
of tripping brackets so that the unsupported length does not exceed the value STo given by
(DNV CN 30.1):
(7.104)
where b =flange width, C= 0.55 for symmetric flanges, = 1.10 for one sided flanges.
Buckling Strength of Longitudinal Hull Girders
Specific buckling criteria for FPSOs are included in the ship design rules, e.g. the ABS Steel
Vessel Rules. The critical area is the main deck and longitudinals when subjected to
a hogging moment. The plate buckling was covered above (see Equations 7.97-7.103).
The following is the critical elastic buckling stress for the longitudinal frames for buckling
perpendicular to the plane of the plating.
(7.105)
where I, = moment of inertia, in cm4, of longitudinal including plate flange, A =Cross-
sectional area of longitudinal including plate flange, 1 = span, in m, of longitudinal,
c1= 1000.
Other buckling modes are covered in the Rules (ABS Steel Vessel Rules). The effective
flange width is equivalent to that determined for strength considerations. Other failure
modes, especially the torsional buckling mode, are covered in the Rules.
The ABS Rules call for the design buckling stress, oC,o f plate panels and longitudinals to
be greater than 1 . 0 f~or~ pl ate panels and 1 . 1f~or ~st iffeners. ua is the design stress
computed including the deadload and wave loads, i.e. the same stress used for strength
design. This should incorporate adjustments as discussed under the strength section for site
specific environments. oC is given as:
(7.106)
E)
u, = uF(1 - when UE L -OF (7.107)
2
Unit: if
Source: Handbook-Offshore-Engineering-Chakrabarti-2005.pdf p.633
"""

TABLE42_RELATIVEOCCURRENCE106_OFCOMBINATIONSOFH1 = 3
"""Table4.2 Relativeoccurrence·106 ofcombinationsofH1=3 andT1 intheNorthAtlantic
T1(cid:9)s(cid:11) H1/3(cid:9)m(cid:11)
from to FCUM 0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5 11.0 13.0 15.0 17.0 19.0 21.0 24.0
1.9 3.1 0.2 2040 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
3.1 4.3 0.6 2343 1324 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
4.3 5.3 5.3 21165 25562 306 0 0 0 0 0 0 0 0 0 0 0 0 0 0
5.3 6.2 14.3 17770 51668 20543 308 0 0 0 0 0 0 0 0 0 0 0 0 0
6.2 7.1 26.4 14666 38973 58152 8922 0 0 0 0 0 0 0 0 0 0 0 0 0
7.1 7.9 41.6 15234 29453 52102 49055 6093 304 0 0 0 0 0 0 0 0 0 0 0
7.9 9.0 57.0 9918 21472 33742 43660 36809 7464 715 0 0 0 0 0 0 0 0 0 0
9.0 10.1 75.9 7894 21221 26655 37214 39675 36189 17120 2768 307 0 0 0 0 0 0 0 0
10.1 11.1 85.4 3062 8167 11945 14497 15621 15314 13579 9188 3369 714 0 0 0 0 0 0 0
11.1 12.1 91.3 1672 4094 6034 7374 8208 8467 8121 6955 4845 2120 822 0 0 0 0 0 0
12.1 13.2 95.2 981 2185 3140 3986 4659 4948 4947 4726 4117 3062 2318 215 0 0 0 0 0
13.2 14.6 97.7 547 1038 1527 2122 2418 2633 2788 2754 2632 2385 3043 784 78 0 0 0 0
14.6 16.4 99.1 269 412 719 942 1069 1259 1312 1374 1358 1325 2246 1303 378 44 0 0 0
16.4 18.6 99.8 110 124 290 314 424 451 516 534 559 557 1072 908 544 197 43 3 0
18.6 21.0 100.0 32 32 71 86 106 126 132 151 154 162 327 314 268 187 86 27 5
FCUM 9.8 30.3 51.9 68.7 80.2 87.9 92.9 95.7 97.4 98.5 99.5 99.8 99.9 100.0 100.0 100.0 100.0
Unit: andT1
Source: Practical-Ship-Hydrodynamics-Bertram-2000.pdf p.126
"""

_12_USS_FREEDOM_LCS1_IS_FLOATING_UPRIGHT_WITH_A_DISPLACEMENT_OF_3100_LT_AND_KG = 18.0
"""12. USS FREEDOM (LCS-1) is floating upright with a displacement of 3100 LT and KG =
18.0 ft. 25 LT of equipment are added to the ship at an average location 30 ft above the
keel and 8 ft starboard of the ship's centerline.
a. What is the new KG?
b. What is the new TCG?
c. This new location of G is unsatisfactory. At what transverse and vertical location
would you add 20 LT of lead ballast to return to the ship’s original KG and
TCG?
13. USS RUSSELL (DDG-59) is floating on an even keel at a draft of 20.5 feet. The center of
gravity is located on the centerline, 21.3 feet above the keel. Lpp = 465 ft. 150 LT of
machinery is removed from a location 10 feet above the keel, 17 feet to port of centerline.
a. Determine KG after the machinery is removed.
b. Determine the ship’s new TCG after removing the machinery.
c. Draw a diagram showing the ship in static equilibrium after the machinery has
been removed.
Section 3.3 The Metacenter
14. Define in terms of K, B, and G and show on a diagram:
a. Transverse Metacentric Height (GM )
T
b. Transverse Metacentric Radius (BM )
T
15. Using the curves of form for the FFG7, determine its Transverse and Longitudinal
Metacentric Heights (GM & GM ) when it is floating at level trim with a mean draft
T L
(T ) of 12.4 ft with KG = 19 ft. Why is GM much larger than GM ?
M L T
Section 3.4 Angle of List
16. A small weight is shifted from port to
starboard as shown on the figure. Redraw the
figure showing the final positions of the
center of gravity (G), center of buoyancy (B),
the resultant weight of the ship (∆ ), the
S
resultant buoyant force (F ), the keel (K), the
B
transverse metacenter (M ). Be neat, clearly
T
label, and use a straight edge where possible.
Assume the angle of list is small.
3 - 39
Unit: ft.
Source: USNA-EN400-Principles-Ship-Performance-2020.pdf p.134
"""

_9_A_SHIP_HAS_A_DISPLACEMENT_OF_6250_LT_AND_KG = 17.6
"""9. A ship has a displacement of 6250 LT and KG = 17.6 ft. In this condition the ship
develops a righting arm of 5.5 ft when heeling to 30 degrees.
a. Draw a diagram showing the effect that lowering the center of gravity has on the
righting arm. Include on your diagram the old and new locations of G, old and
new locations of the center of buoyancy, the metacenter, angle of heel, initial and
final righting arms, and displacement and buoyant force vectors.
b. A weight shift causes the ship’s center of gravity to be lowered by 1.5 ft.
Calculate the ship’s righting arm at a heeling angle of 30° after the weight shift.
10. USS SUPPLY (AOE-6) is preparing to UNREP its Battle Group. Prior to UNREP the ship
was steaming on an even keel at a draft of 38.5 ft. The center of gravity was located 37 ft
above the keel. Lpp = 717 ft.
When UNREP is complete, AOE-6 has discharged 10000 LT (3.2 million gallons) of F-
76 and JP-5 to the Battle Group. The fuel is assumed to have had a center of gravity on
the centerline, 25 ft above the keel of AOE-6.
Using the curves of form and cross curves of stability, determine the following:
a. Displacement and draft of SUPPLY after UNREP.
b. Ship’s KG and TCG following UNREP
c. Compute and plot the righting arm curves for the initial and final conditions of the
ship. Do this for starboard heeling angles only. Note: use of a spreadsheet
program is encouraged.
d. From your results in part (c), complete the following table and comment on the
UNREP’s effect on stability.
Parameter Before UNREP After UNREP
Displacement, ∆ (LT)
Center of Gravity, KG (ft)
Maximum Righting Arm, GZ (ft)
max
Angle of GZ (degrees)
max
Range of Stability (degrees)
4 - 43
Unit: ft.
Source: USNA-EN400-Principles-Ship-Performance-2020.pdf p.182
"""

_14_AN_FFG7_CLASS_SHIP_IS_UNDERWAY_AT_A_DISPLACEMENT_OF_3990_LT_KM = 22.8
"""14. An FFG-7 class ship is underway at a displacement of 3990 LT. KM = 22.8 ft,
KG = 19.3 ft, Lpp = 408 ft. 9000 gallons (28 LT) of F-76 are transferred from a storage
tank located on the centerline, 6 ft above the keel, to a service tank located 6 ft above the
keel and 15 ft to port of centerline.
a. Determine the ship’s TCG after transferring fuel.
b. What is the ship’s list angle after the fuel transfer?
c. Draw a diagram of the ship heeling to port. Show the initial and final locations of
G and B (G ,G,B ,B), initial and final righting arms (G Z , GZ), metacenter
0 f 0 f 0 0 f f
(M), heeling angle (φ), and displacement and buoyant force vectors.
d. Using the cross curve for the FFG-7, calculate and plot for both port and starboard
heeling angles, the ship’s GZ curve before and after transferring fuel. Use of a
spreadsheet program for the computations and plotting is encouraged.
Section 4.7 Damage Stability
15. A compartment has a volume of 600 ft3 and permeability of 90%. How many LT of fresh
water would it hold if it were completely full. ( ρ = 1.94 lb-s2/ft4, 1 LT = 2240 lb ).
fresh
16. The compartment described in Q15 has a centroid 12 ft port of the centerline and 6 ft
above the keel and makes up part of a 6000LT ship with KG = 22 ft and TCG = 0 ft.
Calculate the damaged KG and TCG if the compartment is flooded by 80 % of its volume
with fresh water. ( ρ = 1.94 lb-s2/ft4, 1 LT = 2240 lb ).
fresh
17. The compartment described in Q15 and 16 has a centroid that vertically aligned with the
location of the ship’s center of floatation. Calculate the change in trim created by the
damage.
4 - 45
Unit: ft,
Source: USNA-EN400-Principles-Ship-Performance-2020.pdf p.184
"""

_26_A_SHIP_HAS_A_DISPLACEMENT_OF_12200_LT_KG = 22.6
"""26. A ship has a displacement of 12,200 LT, KG = 22.6 ft on the centerline. At this
displacement the ship has KM = 37 ft. The ship has a free surface in a fuel tank
T
(ρ =1.616 lb s2/ft4). The tank is 35 ft long, 40 ft wide, and 15 ft deep.
fuel
a. Calculate the effective metacentric height if the center of the fuel tank is located
on the centerline, 15 ft above the keel.
b. Calculate the ship’s effective metacentric height if the center of the fuel tank is
located 15 ft above the keel and 10 ft starboard of the centerline.
27. An FFG-7 class ship is on an even keel at a draft of 16.2 ft, KG = 19.1 ft, Lpp = 408 ft.
The ship suffers a major fire in CIC. While extinguishing the fire, the fire party fills CIC
50% full with saltwater. CIC has the following characteristics:
length = 45 ft kg = 46 ft
width = 35 ft tcg = 4 ft starboard of centerline
height = 10 ft lcg = 47 ft forward of amidships
permeability = 90 %
Using the cross curves of stability and curves of form, determine the following:
a. Weight of firefighting water in CIC.
b. Location of the ship’s center of gravity following the fire.
c. Ship’s forward, aft, and mean drafts after the fire.
d. Calculate the ship’s effective metacentric height after the fire.
e. Using the effective location of the vertical center of gravity, determine the ship’s
angle of list following the fire.
f. Calculate and plot the ship’s righting arm curve, for port and starboard heeling
angles, before and after the fire. When computing the GZ curve after the fire, use
the effective location of the center of gravity. Use of a computer is encouraged.
g. The DCA realizes the ship’s stability is threatened and proposes to counter-flood
on the port side by filling a ballast tank 75% full with salt water. The ballast tank
is located 7.5 ft above the keel, 12 ft port of centerline, and 98 ft aft of amidships.
The tank is 20 ft long, 20 ft wide, and 15 ft high. Is the DCA’s proposal a valid
proposal? Discuss why or why not.
4 - 49
Unit: ft
Source: USNA-EN400-Principles-Ship-Performance-2020.pdf p.188
"""

RESISTANCE_FOR = 172
"""Resistance for ∆ = 172 LT
S
The model will now be towed in the tank at scaled speeds (V ) corresponding to full-scale ship
m
speeds (V ) of 4, 7, 12, and 14 knots. Carefully observe the wave patterns created by the model.
S
3. In Figure 2, sketch the transverse and divergent wave patterns at speeds of 4 and 14 kts.
Figure 2 Diagram of YP wake patterns at speeds of 4 and 14 knots.
4. A very good approximation of the total hull resistance for a ship is to multiply the total
hull resistance of the model by the cube of the scale factor. Using the experimental data
and this relationship, complete the table:
R ≅ R λ3
TS TM
Recall:
1 knot = 1.688 ft/s
𝑉𝑉𝑆𝑆 𝑅𝑅𝑇𝑇𝑆𝑆𝑉𝑉𝑆𝑆
where, 𝜆𝜆 == s𝐿𝐿c𝑆𝑆a/le𝐿𝐿 𝑀𝑀ratio 𝑉𝑉 𝑀𝑀 = √𝜆𝜆 = total resi𝐸𝐸st𝐸𝐸an𝐸𝐸ce= o 5 f 5 t 0 h e𝑓𝑓 𝑠𝑠− 𝑓𝑓 −s 𝐻𝐻 𝑙𝑙h 𝐻𝐻 𝑙𝑙ip (lb)
=Effective Horsepower = total resistance of the model (lb)
𝜆𝜆 = length of ship (ft) 𝑅𝑅𝑇𝑇 𝑆𝑆 = speed of the ship (ft/s)
𝐸𝐸𝐸𝐸 𝐸𝐸= length of model (ft) 𝑅𝑅𝑇𝑇𝑀𝑀 = speed of the model (ft/s)
𝐿𝐿𝑠𝑠 𝑉𝑉𝑆𝑆
𝐿𝐿𝑀𝑀 𝑉𝑉𝑀𝑀
YP Resistance and EHP Data at ∆ = 172 LT
S
V (kt) V (ft/s) V (ft/s) R (lb) R (lb) EHP (HP)
S S M TM TS
4
7
12
14
Table 2 Speed and resistance data
LAB 7 - 4
Unit: LT
Source: USNA-EN400-Principles-Ship-Performance-2020.pdf p.468
"""

FULL_SCALE_SPEED = 7
"""Full scale speed
= 7 knots
Fr = 0.13
hull
Fr = 0.44
sail
Results
Unit: knots
Source: Warship-2011-Naval-Submarines-UUVs.pdf p.376
"""

FULL_SCALE_SPEED = 12
"""Full scale speed
= 12 knots
Fr = 0.21
hull
Fr = 0.71
sail
Results
Unit: knots
Source: Warship-2011-Naval-Submarines-UUVs.pdf p.377
"""

FULL_SCALE_SPEED = 15
"""Full scale speed
= 15 knots
Fr = 0.27
hull
Fr = 0.88
sail
Results
Unit: knots
Source: Warship-2011-Naval-Submarines-UUVs.pdf p.378
"""

FULL_SCALE_SPEED = 17
"""Full scale speed
= 17 knots
Fr = 0.32
hull
Fr = 1.06
sail
Results
Unit: knots
Source: Warship-2011-Naval-Submarines-UUVs.pdf p.379
"""
