python src\pyintegrity\tests\test_pyintegrity_bs7910.py
REM python src\pyintegrity\tests\test_pyintegrity_bs7910_ecs_2500ft_buoy_jt.py
REM python src\pyintegrity\tests\test_pyintegrity_bs7910_ecs_2500ft_buoy_jt.py
REM python src\pyintegrity\tests\test_pyintegrity_bs7910_ecs_2500ft_buoy_jt.py
REM python src\pyintegrity\tests\test_pyintegrity_bs7910_ecs_2500ft_buoy_jt.py
REM python src\pyintegrity\tests\test_pyintegrity_bs7910_ecs_2500ft_buoy_jt.py
REM python src\pyintegrity\tests\test_pyintegrity_bs7910_ecs_2500ft_buoy_jt.py
REM python src\pyintegrity\tests\test_pyintegrity_bs7910_ecs_2500ft_buoy_jt.py
