# Configuration for Mooring Tension Iteration System
# Project: CTR7 LNGC Mooring Analysis

# Paths configuration
paths:
  base_path: "D:/1522/ctr7/orcaflex/rev_a08/base_files"
  pretension_folder: "fsts_lngc_pretension"
  output_folder: "iteration_output"
  includefiles_folder: "includefiles"
  
# Target tension CSV files
target_files:
  default: "180km3_l000_pb_target_mooring_pretension.csv"
  alternatives:
    - "180km3_l000_pb_target_mooring_pretension.csv"
    - "240km3_l000_pb_target_mooring_pretension.csv"
    - "300km3_l000_pb_target_mooring_pretension.csv"

# OrcaFlex model files
models:
  static_6dof: "fsts_lngc_vessel_statics_6dof.yml"
  static_3dof: "fsts_lngc_vessel_statics_3dof.yml"
  extraction_config: "dm_ofx_post_fsts_lngc.yml"
  
# Iteration parameters
iteration:
  max_iterations: 10
  convergence_tolerance: 0.01  # 1% tension error tolerance
  damping_factor: 0.8          # 0.8 = moderate damping to prevent oscillation
  initial_damping: 0.5         # Lower damping for first iteration
  adaptive_damping: true       # Adjust damping based on convergence behavior
  
# Convergence criteria
convergence:
  tension_tolerance_percent: 1.0   # Maximum allowable tension error (%)
  force_tolerance_kN: 5.0          # Alternative: absolute force tolerance
  max_adjustment_m: 0.5            # Maximum length adjustment per iteration
  min_improvement: 0.001           # Minimum improvement to continue iterating
  
# Analysis settings
analysis:
  timeout_seconds: 600            # 10 minutes max per analysis
  extraction_timeout: 120          # 2 minutes for result extraction
  parallel_lines: false            # Process lines in parallel (future feature)
  use_cached_properties: true      # Cache line properties from first analysis
  
# Output options
output:
  save_history: true              # Save iteration history
  save_includefiles: true         # Keep all includefiles
  plot_convergence: true          # Generate convergence plots
  generate_report: true           # Generate detailed HTML report
  csv_summary: true               # Export summary to CSV
  json_history: true              # Export full history as JSON
  
# Logging configuration
logging:
  level: "INFO"                   # DEBUG, INFO, WARNING, ERROR
  file_logging: true              # Log to file
  console_logging: true           # Log to console
  log_folder: "logs"
  max_log_size_mb: 10
  backup_count: 5
  
# Advanced settings
advanced:
  # Line grouping for different treatment
  line_groups:
    bow_lines: ["Line01", "Line02", "Line03", "Line04", "Line05", "Line06"]
    stern_lines: ["Line07", "Line08", "Line09", "Line10", "Line11", "Line12"]
    breast_lines: ["Line13", "Line14", "Line15", "Line16", "Line17", "Line18"]
  
  # Different damping factors per group
  group_damping:
    bow_lines: 0.8
    stern_lines: 0.8
    breast_lines: 0.7
    
  # EA override (if not extracting from model)
  ea_overrides:
    default_ea: 1290.0  # kN
    high_stiffness_ea: 50000.0  # kN
    
# Validation settings
validation:
  check_initial_tensions: true     # Verify initial tensions are reasonable
  max_initial_error: 50.0          # Maximum initial error allowed (%)
  check_line_lengths: true         # Verify line lengths are realistic
  min_length: 5.0                  # Minimum line length (m)
  max_length: 500.0                # Maximum line length (m)
  
# Performance optimization
performance:
  cache_results: true              # Cache intermediate results
  compress_history: true           # Compress large history files
  cleanup_temp_files: true         # Remove temporary files after completion
  
# Notification settings (future feature)
notifications:
  email_on_completion: false
  email_on_failure: true
  webhook_url: null
  
# Environment specific settings
environment:
  digitalmodel_path: "digitalmodel"  # Path to digitalmodel executable
  orcaflex_version: "11.0"          # OrcaFlex version for compatibility
  python_path: "python"              # Python executable path