@echo off
REM ============================================================================
REM Sea Cypress Diffraction Analysis Batch Runner
REM Generated by OrcaWave Module Agent
REM ============================================================================

SETLOCAL EnableDelayedExpansion

REM Configuration
SET ORCAWAVE_PATH="C:\Program Files\Orcina\OrcaWave\bin\orcawave.exe"
SET CONFIG_DIR=..\configs
IF "%~1"=="" (
    SET CONFIG_FILE=%CONFIG_DIR%\sea_cypress_diffraction.yml
) ELSE (
    SET CONFIG_FILE=%~1
)
SET RESULTS_DIR=..\results
SET LOG_DIR=..\logs
SET TIMESTAMP=%date:~-4,4%%date:~-10,2%%date:~-7,2%_%time:~0,2%%time:~3,2%%time:~6,2%
SET TIMESTAMP=%TIMESTAMP: =0%
SET LOG_FILE=%LOG_DIR%\analysis_log_%TIMESTAMP%.txt

REM Create necessary directories
echo Creating output directories...
if not exist "%RESULTS_DIR%" mkdir "%RESULTS_DIR%"
if not exist "%LOG_DIR%" mkdir "%LOG_DIR%"
if not exist "%RESULTS_DIR%\csv_outputs" mkdir "%RESULTS_DIR%\csv_outputs"
if not exist "%RESULTS_DIR%\cache" mkdir "%RESULTS_DIR%\cache"

REM Display configuration
echo ============================================================================
echo OrcaWave Diffraction Analysis - Sea Cypress
echo ============================================================================
echo Configuration: %CONFIG_FILE%
echo Results: %RESULTS_DIR%
echo Log file: %LOG_FILE%
echo Timestamp: %TIMESTAMP%
echo ============================================================================

REM Check if OrcaWave exists
if not exist %ORCAWAVE_PATH% (
    echo ERROR: OrcaWave not found at %ORCAWAVE_PATH%
    echo Please verify installation path and update ORCAWAVE_PATH variable
    exit /b 1
)

REM Check if configuration file exists
if not exist "%CONFIG_FILE%" (
    echo ERROR: Configuration file not found: %CONFIG_FILE%
    exit /b 1
)

REM Check license availability
echo Checking OrcaWave license...
%ORCAWAVE_PATH% -check-license > "%LOG_DIR%\license_check.txt" 2>&1
if %ERRORLEVEL% NEQ 0 (
    echo WARNING: License check failed. Please verify license availability.
    type "%LOG_DIR%\license_check.txt"
    echo.
    echo Continue anyway? (Y/N)
    set /p CONTINUE=
    if /i "!CONTINUE!" NEQ "Y" exit /b 1
)

REM Run OrcaWave analysis
echo.
echo Starting OrcaWave Diffraction Analysis...
echo This may take 1-2 hours depending on mesh complexity...
echo.

REM Execute with detailed logging
%ORCAWAVE_PATH% ^
    -config "%CONFIG_FILE%" ^
    -batch ^
    -output-dir "%RESULTS_DIR%" ^
    -log "%LOG_FILE%" ^
    -verbose ^
    -progress

SET ANALYSIS_ERROR=%ERRORLEVEL%

if %ANALYSIS_ERROR% NEQ 0 (
    echo.
    echo ERROR: OrcaWave analysis failed with code %ANALYSIS_ERROR%
    echo Check log file for details: %LOG_FILE%
    
    REM Common error codes
    if %ANALYSIS_ERROR% EQU 1 echo Error Type: General failure
    if %ANALYSIS_ERROR% EQU 2 echo Error Type: License issue
    if %ANALYSIS_ERROR% EQU 3 echo Error Type: Geometry/mesh problem
    if %ANALYSIS_ERROR% EQU 4 echo Error Type: Solver convergence failure
    if %ANALYSIS_ERROR% EQU 5 echo Error Type: Memory allocation failure
    
    exit /b %ANALYSIS_ERROR%
)

echo.
echo ============================================================================
echo Analysis completed successfully!
echo ============================================================================

REM Post-processing
echo.
echo Processing results...

REM Check if Python script exists for conversion
if exist "..\scripts\convert_to_orcaflex.py" (
    echo Converting results to OrcaFlex format...
    cd /d "%~dp0"
    python convert_to_orcaflex.py --input "%RESULTS_DIR%" --output "%RESULTS_DIR%\orcaflex"
    if %ERRORLEVEL% NEQ 0 (
        echo WARNING: OrcaFlex conversion failed
    ) else (
        echo OrcaFlex conversion complete
    )
)

REM Generate summary report
echo.
echo Generating summary report...
if exist "..\scripts\generate_summary.py" (
    python generate_summary.py --results "%RESULTS_DIR%" --output "%RESULTS_DIR%\summary_%TIMESTAMP%.html"
)

REM List output files
echo.
echo ============================================================================
echo Output Files Generated:
echo ============================================================================
dir /b "%RESULTS_DIR%\*.xlsx" 2>nul
dir /b "%RESULTS_DIR%\*.csv" 2>nul
dir /b "%RESULTS_DIR%\*.yml" 2>nul
dir /b "%RESULTS_DIR%\*.h5" 2>nul

REM Display summary
echo.
echo ============================================================================
echo Batch processing complete!
echo ============================================================================
echo Results location: %RESULTS_DIR%
echo Log file: %LOG_FILE%
echo Timestamp: %TIMESTAMP%
echo ============================================================================

REM Optionally open results folder
echo.
echo Open results folder? (Y/N)
set /p OPEN_RESULTS=
if /i "%OPEN_RESULTS%" EQU "Y" (
    explorer "%RESULTS_DIR%"
)

ENDLOCAL
exit /b 0
