# Input Parameters for Parametric Analysis
# Source: C05 Single Point Mooring.yml
# Generated: 2026-01-18 22:19:49

water_depth: 220
current_speed: 1
wind_speed: 35
water_density: 1.025
stage_durations:
- 100
- 3600
wave_direction: 180

