# Input Parameters for Parametric Analysis
# Source: D04 J-tube pull in.yml
# Generated: 2026-01-18 22:18:09

water_depth: 120
current_speed: 0
wind_speed: 0
water_density: 1.025
stage_durations:
- 8
- 275
hs: 3
tp: 8
wave_direction: 180

