# the name of the file containing the base OrcaFlex model
basecaseName: basecase.dat

# in kN
maxTension: 250

# in kN
minTension: 0

# in m - the minimum allowable distance to the constraint defined above the stinger
minConstraintClearance: 0

# in kN - the maximum horizontal component of force exerted on the vessel
maxBollardPull: 500.0

# in m - this is the distance between anchor points from one load case to the next
increment: 1.0

# the number of cases required in the lay table, including the extremes (failed near and far cases)
noOfCasesToAnalyse: 18

# a text field only - the code check reference that will be inserted into the basecase data table in the spreadsheet
codeCheckReference: API RP 1111