# Cumulative Damage Analysis Configuration
# This configuration file defines parameters for calculating cumulative fatigue damage
# and fatigue life based on stress rainflow cycle counting and sea state occurrence data

analysis:
  name: "Cumulative Fatigue Damage Analysis"
  description: "Calculate fatigue life by combining damage rates with sea state occurrence probabilities"
  version: "1.0.0"
  
input:
  # Damage rate files from rainflow analysis
  base_folder: "D:/1522/ctr9/fatigue_wsp_method/07c_fatigue/output/damage"
  damage_rates:
    folder: "damage_results"
    pattern: "{config}_FC{fatigue_condition}_Strut{strut}_{location}_damage_rate.csv"
    file_format: "csv"
    columns:
      - "stress_range_mpa"        # Stress range in MPa
      - "cycles_annual"           # Annual cycles
      - "stress_corrected_mpa"    # Corrected stress in MPa
      - "cycles_to_failure"       # Cycles to failure
      - "damage_per_bin"          # Damage per stress bin
      - "damage_rate_per_year"    # Annual damage rate
    
  # Fatigue condition occurrence probabilities
  fatigue_conditions:
    file: "input/fatigue_seastates_production.csv"
    format: "csv"
    columns:
      - "Row"                     # Fatigue condition ID (FC001, FC002, etc.)
      - "Wind Speed (m/s)"        # Wind speed
      - "Wind Dir (deg)"          # Wind direction
      - "Hs (m)"                  # Significant wave height
      - "Tp (s)"                  # Peak period
      - "Wave Dir (deg)"          # Wave direction
      - "Occurrence (%)"          # Occurrence probability percentage

processing:
  # Configuration processing settings
  configurations:
    mode: "all"                   # Process all available configurations
    # specific: []                # Optional: specify configurations to process
    
  # Component processing settings
  struts:
    mode: "all"                   # Process all struts (1-8)
    range: [1, 8]
    
  # Location processing settings
  locations:
    mode: "all"                   # Process all available locations
    # expected: ["loc02", "loc03", "loc05", "loc06", "loc07", "loc09", "loc10"]
    
  # Methodology parameters
  methodology:
    damage_combination: "miners_rule"  # Use Miner's rule for damage accumulation
    fatigue_life_calculation:
      method: "inverse_damage_rate"    # Fatigue life = 1 / total_damage_rate
      units: "years"
    
  # Data handling
  missing_data:
    handling: "skip"              # Skip missing file combinations
    log_missing: true             # Log missing files for tracking

output:
  # Output directory structure
  base_folder: "D:/1522/ctr9/fatigue_wsp_method/07c_fatigue/output/damage"
  
  # Individual result files (one per config/strut/location)
  individual_files:
    enabled: true
    folder: "individual_results"
    pattern: "{config}_FC_all_Strut{strut}_{location}_fatigue_life.csv"
    format: "csv"
    columns:
      - "fatigue_condition"       # FC001, FC002, etc.
      - "occurrence_percent"      # Occurrence probability
      - "damage_rate_annual"      # Annual damage rate for this FC
      - "weighted_damage_rate"    # Damage rate × occurrence probability
      - "contribution_percent"    # % contribution to total damage
    summary_rows:
      - "total_damage_rate"       # Sum of weighted damage rates
      - "fatigue_life_years"      # 1 / total_damage_rate
      
  # Summary file (all results combined)
  summary:
    enabled: true
    filename: "fatigue_life_summary.csv"
    format: "csv"
    columns:
      - "configuration"           # Configuration name
      - "strut"                   # Strut number
      - "location"                # Location ID
      - "total_damage_rate"       # Annual damage rate
      - "fatigue_life_years"      # Fatigue life in years
      - "critical_fc"             # FC with highest contribution
      - "critical_fc_contribution" # % contribution of critical FC
      
  # Visualization outputs
  plots:
    enabled: true
    folder: "plots"
    
    # Individual plots (per config/strut/location)
    individual:
      enabled: true
      types:
        - type: "bar_chart"
          name: "damage_contribution_by_fc"
          description: "Damage rate contribution by fatigue condition"
          x_axis: "fatigue_condition"
          y_axis: "weighted_damage_rate"
          secondary_y: "cumulative_damage_rate"
          
        - type: "stacked_bar"
          name: "damage_percentage_breakdown"
          description: "Percentage contribution to total damage"
          x_axis: "fatigue_condition"
          y_axis: "contribution_percent"
          
    # Aggregated plots (by configuration)
    aggregated:
      enabled: true
      types:
        - type: "heatmap"
          name: "fatigue_life_matrix"
          description: "Fatigue life heatmap (struts vs locations)"
          x_axis: "location"
          y_axis: "strut"
          value: "fatigue_life_years"
          colorscale: "viridis"
          
        - type: "grouped_bar"
          name: "fatigue_life_comparison"
          description: "Compare fatigue life across struts and locations"
          x_axis: "strut"
          group_by: "location"
          y_axis: "fatigue_life_years"
          
        - type: "line_plot"
          name: "critical_damage_trends"
          description: "Critical damage rate trends across struts"
          x_axis: "strut"
          y_axis: "total_damage_rate"
          group_by: "location"

# Execution parameters
execution:
  parallel_processing: false      # Enable parallel processing (disabled for sample data)
  max_workers: 4                  # Maximum parallel workers
  verbose: true                   # Verbose output
  log_level: "INFO"              # Logging level
  
# Reporting
reporting:
  generate_report: true           # Generate analysis report
  report_format: "markdown"       # Report format
  include_sections:
    - "executive_summary"
    - "methodology"
    - "results_overview"
    - "critical_findings"
    - "recommendations"
  
# Quality checks
quality_checks:
  enabled: true
  checks:
    - name: "damage_rate_bounds"
      description: "Check damage rates are within reasonable bounds"
      min_value: 0.0
      max_value: 1.0
      
    - name: "fatigue_life_bounds"
      description: "Check fatigue life is within expected range"
      min_years: 1.0
      max_years: 1000.0
      
    - name: "occurrence_sum"
      description: "Verify occurrence probabilities sum to ~100%"
      expected_sum: 100.0
      tolerance: 0.1