%%YAML 1.1
# Minimal OrcaWave configuration to test geometry import
---
# Model
UnitsSystem: SI

# Environment
WaterDepth: 100
WaterDensity: 1025

# Just test loading the geometry
Bodies:
  - BodyName: SeaCypress_Test
    BodyMeshPosition: [0, 0, 0]
    BodyMeshAttitude: [0, 0, 0]
    BodyIncludedInAnalysis: Yes
    BodyMeshFileName: ../inputs/geometry/sea_cypress_gmsh_optimized.dat
    BodyMeshFormat: Aqwa dat
    BodyMeshLengthUnits: m
    BodyMeshSymmetry: None
    BodyMeshBodyNumber: 1
    
# Minimal frequency range for testing
PeriodOrFrequency:
  - 10  # Just one period for quick test
  
WaveHeading:
  - 0   # Just head seas for quick test
...
