%YAML 1.1
# Test configuration for simple box geometry
# Purpose: Verify OrcaWave can import our GDF files
---
# Model
UnitsSystem: SI

# Environment
WaterDepth: 100
WaterDensity: 1025

# Minimal calculation settings for quick test
SolveType: Radiation and diffraction
LoadRAOCalculationMethod: Direct integration
ValidatePanelArrangement: Yes
OutputIntermediateResults: Yes

# Single frequency and heading for quick test
WavesReferredToBy: period (s)
PeriodOrFrequency:
  - 10
  
WaveHeading:
  - 0

# Simple box body
Bodies:
  - BodyName: TestBox
    BodyMeshPosition: [0, 0, 0]
    BodyMeshAttitude: [0, 0, 0]
    BodyIncludedInAnalysis: Yes
    BodyMeshFileName: ../inputs/geometry/simple_box_test.gdf
    BodyMeshFormat: Wamit gdf
    BodyMeshLengthUnits: m
    BodyMeshSymmetry: None
    BodyMeshBodyNumber: 1
    
    # Basic mass properties
    BodyInertiaSpecifiedBy: Matrix (for a general body)
    BodyCentreOfMass: [0, 0, -1]
    BodyMass: 100000
    
    BodyInertiaTensorRx, BodyInertiaTensorRy, BodyInertiaTensorRz:
      - [1e6, 0, 0]
      - [0, 1e6, 0]
      - [0, 0, 1e6]
    BodyInertiaTensorOriginType: Centre of mass
    
    # Free floating
    BodyConnectionParent: Free
    BodyFixedDOFx: No
    BodyFixedDOFy: No
    BodyFixedDOFz: No
    BodyFixedDOFRx: No
    BodyFixedDOFRy: No
    BodyFixedDOFRz: No
...