@startuml website_tools
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Tomato

title Website Tools\n HairByLiz

start

    partition "Setup" {

        :Raw Files:
            Github;
            note right
                Change management etc.
                https://github.com/vamseeachanta/hairbyliz
                Access: VA, PP
            end note

        :Deployment:
            Heroku Dyno;
            note right
                https://hairbyliz.herokuapp.com/
                java,
                content, ssl cert etc.
                Access: VA, PP
            end note
        :DNS Host
            GoDaddy;
            note right
                Access: VA
            end note

    }


    partition "Operations" {

        :Organic SEO Updates:
            Github;
            note right
                Change management etc.
                https://github.com/vamseeachanta/hairbyliz
                Access: VA, PP
            end note

        :Page view analytics:
            Google Analytics;
            note right
                https://analytics.google.com/analytics/web/
                Access: VA, PP
            end note

        :Paid SEO: 
            Google Ads;
            note right
                https://ads.google.com/
                1st time use of USD 500 has 
                additional USD 500 offer.
                Access: None
            end note



    }



stop

footer
%date("yyyy.MM.dd' at 'HH:mm")
%filename()
end footer

@enduml