# Input Parameters for Parametric Analysis
# Source: basedatawithbuoy2.yml
# Generated: 2026-01-18 21:53:19

water_depth: 499.9999999999999
wind_speed: 42.2
water_density: 0.06398865959054831
stage_durations:
- 10
- 500
wave_direction: 45

