# Sea Cypress Vessel Configuration
# Specific configuration for Sea Cypress diffraction analysis

vessel:
  name: "Sea Cypress"
  type: "Tug"
  length_overall: 30.0  # meters (approximate)
  beam: 10.0           # meters (approximate)
  draft: 3.5           # meters (approximate)
  
geometry:
  primary_file: "Sea Cypress_0.25 Mesh_Binary.stl"
  alternate_files:
    - "Sea Cypress_0.25 Mesh_Ascii.stl"
    - "Sea Cypress_0.25 Mesh_Binary.obj"
  path: "specs/modules/orcawave/sea-cypress-diffraction-analysis/inputs/geometry"
  # Alternative absolute path (update as needed):
  # path: "D:\\github\\digitalmodel\\specs\\modules\\orcawave\\sea-cypress-diffraction-analysis\\inputs\\geometry"
  
# Override base configuration values
environment:
  water_depth: 100.0  # Site-specific depth
  
mesh_settings:
  panel_size: 0.25    # Matches provided mesh
  
frequency_range:
  start: 0.01
  end: 3.0
  steps: 100
  
project:
  name: "B1512 Sea Cypress Analysis"
  client: "Nork & Mendez"
  reference: "B1512"
  
analysis_specifics:
  purpose: "Hydrodynamic analysis for Sea Cypress vessel"
  applications:
    - "OrcaFlex integration"
    - "Motion response analysis"
    - "Mooring system design"