#!/usr/bin/env python3
"""Recover original (pre-overwrite) issue bodies from GitHub edit history.

Read-only. Uses the GraphQL `userContentEdits` API, which retains a full
snapshot of the issue body at every edit. For each affected issue we take the
most recent revision *before* the migration script stamped a `## WRK-NNN`
template over it, and save that original body to a local file.

Nothing here writes to GitHub. Restoring the live bodies is a separate,
human-gated action (see the generated `RESTORE_COMMANDS.sh`).

Usage:
    python scripts/maintenance/recover_issue_bodies.py \
        --repo vamseeachanta/digitalmodel \
        --issues 13,17,18,19,20,23,28,29 \
        --out docs/issue-body-recovery
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

WRK_SIGNATURE = re.compile(r"^\s*##\s*WRK-?\d+", re.IGNORECASE)


def gh_graphql(owner: str, name: str, number: int) -> dict:
    query = """
    query($owner:String!, $name:String!, $number:Int!) {
      repository(owner:$owner, name:$name) {
        issue(number:$number) {
          title
          body
          userContentEdits(first: 50) {
            totalCount
            nodes { editedAt diff editor { login } }
          }
        }
      }
    }
    """
    r = subprocess.run(
        [
            "gh", "api", "graphql",
            "-f", f"query={query}",
            "-F", f"owner={owner}",
            "-F", f"name={name}",
            "-F", f"number={number}",
        ],
        capture_output=True, text=True,
    )
    if r.returncode != 0:
        raise RuntimeError(f"gh graphql failed for #{number}: {r.stderr.strip()}")
    return json.loads(r.stdout)["data"]["repository"]["issue"]


def looks_like_wrk_template(text: str | None) -> bool:
    return bool(text) and bool(WRK_SIGNATURE.match(text.strip()))


def pick_original(issue: dict) -> tuple[str | None, str]:
    """Return (original_body, note).

    The `diff` field of each userContentEdit is a full snapshot of the body at
    that edit. Newest first. We skip any snapshot that is itself a WRK template
    (the clobber and any later re-stamps) and return the newest human snapshot.
    """
    nodes = issue.get("userContentEdits", {}).get("nodes", []) or []
    if not nodes:
        return None, "no edit history available"
    # nodes are newest-first; the current live body is implicit (latest stamp).
    for node in nodes:
        snap = node.get("diff")
        if snap is None:
            # null diff = issue creation with empty body, or redacted
            continue
        if looks_like_wrk_template(snap):
            continue  # this revision is a machine WRK stamp, keep looking back
        return snap, f"recovered from revision edited {node.get('editedAt')}"
    # All snapshots were WRK templates (or null) -> no human body to recover.
    return None, "no pre-WRK human revision found in history"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--repo", required=True, help="owner/name")
    ap.add_argument("--issues", required=True, help="comma-separated issue numbers")
    ap.add_argument("--out", default="docs/issue-body-recovery")
    args = ap.parse_args(argv)

    owner, name = args.repo.split("/", 1)
    numbers = [int(x) for x in args.issues.split(",") if x.strip()]
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    summary = []
    restore_cmds = ["#!/usr/bin/env bash",
                    "# Human-gated restore of recovered issue bodies. Review each file first.",
                    "# Generated by recover_issue_bodies.py — NOT run automatically.",
                    "set -euo pipefail", ""]

    for n in numbers:
        try:
            issue = gh_graphql(owner, name, n)
        except RuntimeError as e:
            summary.append({"issue": n, "recovered": False, "note": str(e)})
            print(f"#{n}: ERROR {e}", file=sys.stderr)
            continue

        original, note = pick_original(issue)
        title = (issue.get("title") or "").strip()
        live_clobbered = looks_like_wrk_template(issue.get("body"))

        if original is not None and original.strip():
            fpath = out / f"issue-{n}.md"
            fpath.write_text(original if original.endswith("\n") else original + "\n")
            summary.append({"issue": n, "title": title, "recovered": True,
                            "file": str(fpath), "note": note,
                            "live_clobbered": live_clobbered})
            restore_cmds.append(
                f'gh issue edit {n} --repo {args.repo} '
                f'--body-file {fpath}  # {title}')
            print(f"#{n}: recovered -> {fpath} ({note})")
        else:
            summary.append({"issue": n, "title": title, "recovered": False,
                            "note": note, "live_clobbered": live_clobbered})
            print(f"#{n}: NOT recovered ({note})", file=sys.stderr)

    (out / "RECOVERY_SUMMARY.json").write_text(json.dumps(summary, indent=2) + "\n")
    restore_path = out / "RESTORE_COMMANDS.sh"
    restore_path.write_text("\n".join(restore_cmds) + "\n")
    restore_path.chmod(0o755)
    n_ok = sum(1 for s in summary if s.get("recovered"))
    print(f"\nRecovered {n_ok}/{len(numbers)} bodies. "
          f"Summary: {out / 'RECOVERY_SUMMARY.json'}; "
          f"restore commands (human-gated): {restore_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
