# Input Parameters for Parametric Analysis
# Source: A06 SHEAR7 import drag amplification.yml
# Generated: 2026-01-18 21:51:02

water_depth: 5900
current_speed: 0.9842519685039368
wind_speed: 0
water_density: 64.00000000000001
hs: 0
tp: 14
wave_direction: 180

