# Input Parameters for Parametric Analysis
# Source: E03 Detailed hinged stinger.yml
# Generated: 2026-01-18 22:18:12

water_depth: 100
current_speed: 0.5
wind_speed: 0
water_density: 1.025
stage_durations:
- 8
- 50
wave_direction: 0

