# Input Parameters for Parametric Analysis
# Source: L04 Sectional bodies.yml
# Generated: 2026-01-18 21:52:42

current_speed: 0
wind_speed: 0
water_density: 1.025
stage_durations:
- 30
- 50
hs: 5
tp: 7
wave_direction: 180

