# Example configuration file for FSTS LNGC with max_workers parameter
# This shows all available parallel processing options

meta:
  label: 'fsts_l015_lwl_180km3_l100_pb'
  basename: 'orcaflex_post_process'

file_management:
  input_directory: '../02c_005yr'
  output_directory: '../output/csv/02c_005yr'
  filename:
    pattern: 'fsts_l015_lwl_180km3_l100_pb'

# ===========================
# PARALLEL PROCESSING OPTIONS
# ===========================
parallel_processing:
  # Enable/disable parallel processing
  enabled: true
  
  # Number of parallel workers
  # Options:
  #   - Integer (e.g., 4): Use specific number of workers
  #   - 'auto': Automatically determine based on CPU cores and file sizes
  #   - null/omit: Use default (auto)
  max_workers: 4
  
  # Task type affects worker pool selection
  # Options:
  #   - 'cpu_bound': Use ProcessPoolExecutor (for CPU-intensive tasks)
  #   - 'io_bound': Use ThreadPoolExecutor (for I/O-intensive tasks)  
  #   - 'mixed': Auto-select based on task characteristics
  task_type: 'mixed'
  
  # Auto-optimize worker count based on file sizes
  # When true, analyzes .sim file sizes to determine optimal worker count
  auto_optimize: true
  
  # Timeout per file in seconds
  # Prevents hanging on problematic files
  timeout_per_file: 3600
  
  # Save detailed error reports for failed files
  save_error_reports: true
  
  # Minimum items needed to trigger parallel processing
  # Files fewer than this will be processed sequentially
  min_items_for_parallel: 2

# OrcaFlex specific settings
orcaflex:
  post_process:
    enabled: true
    output_format: 'csv'
    
# You can also override via command line:
# python -m digitalmodel dm_fsts_lngc.yml "{'parallel_processing': {'max_workers': 8}}"