current_direction: 180.0
current_speed: 0.0
hs: 0.75
stage_durations:
- 5
- 5
- 300
- 300
- 5
- 200
- 5
- 85
time_step: 0.1
tp: 4.5
water_density: 1.025
water_depth: 100.0
wave_direction: 180.0
wind_speed: 0.0
