# Input Parameters for Parametric Analysis
# Source: E05 Pipe davit lift.yml
# Generated: 2026-01-18 21:52:00

water_depth: 100
current_speed: 0
wind_speed: 0
water_density: 1.025
stage_durations:
- 5
- 5
- 300
- 300
- 5
- 200
- 5
- 85
hs: 0.75
tp: 4.5
wave_direction: 180

