"""Tests for the AQWA .AH1 ASCII hydrodynamic database parser.

Tests cover:
- Header parsing (body count, frequency count, heading count, values)
- GENERAL section (water depth, density, gravity)
- MASS and HYDSTIFFNESS matrix parsing
- ADDEDMASS and DAMPING frequency-dependent matrix parsing
- FORCERAO excitation force parsing
- Edge cases (empty file, missing sections)
"""

from pathlib import Path
from textwrap import dedent

import numpy as np
import pytest

from digitalmodel.hydrodynamics.diffraction.aqwa_ah1_parser import (
    AH1ParseResult,
    parse_ah1,
)


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------

_MINIMAL_AH1 = dedent("""\
    * AQWA Hydrodynamic Database
    * Generated by test
         1         2         3
      0.000000    45.000000
      0.300000    0.500000    0.700000
    GENERAL
      100.0    1025.0    9.80665
    DRAFT
      5.0
    COG
      0.0  0.0  -2.5
    MASS
      1000.0  0.0  0.0  0.0  0.0  0.0
      0.0  1000.0  0.0  0.0  0.0  0.0
      0.0  0.0  1000.0  0.0  0.0  0.0
      0.0  0.0  0.0  500.0  0.0  0.0
      0.0  0.0  0.0  0.0  500.0  0.0
      0.0  0.0  0.0  0.0  0.0  500.0
    HYDSTIFFNESS
      0.0  0.0  0.0  0.0  0.0  0.0
      0.0  0.0  0.0  0.0  0.0  0.0
      0.0  0.0  9810.0  0.0  0.0  0.0
      0.0  0.0  0.0  1000.0  0.0  0.0
      0.0  0.0  0.0  0.0  1000.0  0.0
      0.0  0.0  0.0  0.0  0.0  0.0
    ADDEDMASS
      100.0  0.0  0.0  0.0  0.0  0.0
      0.0  100.0  0.0  0.0  0.0  0.0
      0.0  0.0  100.0  0.0  0.0  0.0
      0.0  0.0  0.0  50.0  0.0  0.0
      0.0  0.0  0.0  0.0  50.0  0.0
      0.0  0.0  0.0  0.0  0.0  50.0
      200.0  0.0  0.0  0.0  0.0  0.0
      0.0  200.0  0.0  0.0  0.0  0.0
      0.0  0.0  200.0  0.0  0.0  0.0
      0.0  0.0  0.0  100.0  0.0  0.0
      0.0  0.0  0.0  0.0  100.0  0.0
      0.0  0.0  0.0  0.0  0.0  100.0
      300.0  0.0  0.0  0.0  0.0  0.0
      0.0  300.0  0.0  0.0  0.0  0.0
      0.0  0.0  300.0  0.0  0.0  0.0
      0.0  0.0  0.0  150.0  0.0  0.0
      0.0  0.0  0.0  0.0  150.0  0.0
      0.0  0.0  0.0  0.0  0.0  150.0
    DAMPING
      10.0  0.0  0.0  0.0  0.0  0.0
      0.0  10.0  0.0  0.0  0.0  0.0
      0.0  0.0  10.0  0.0  0.0  0.0
      0.0  0.0  0.0  5.0  0.0  0.0
      0.0  0.0  0.0  0.0  5.0  0.0
      0.0  0.0  0.0  0.0  0.0  5.0
      20.0  0.0  0.0  0.0  0.0  0.0
      0.0  20.0  0.0  0.0  0.0  0.0
      0.0  0.0  20.0  0.0  0.0  0.0
      0.0  0.0  0.0  10.0  0.0  0.0
      0.0  0.0  0.0  0.0  10.0  0.0
      0.0  0.0  0.0  0.0  0.0  10.0
      30.0  0.0  0.0  0.0  0.0  0.0
      0.0  30.0  0.0  0.0  0.0  0.0
      0.0  0.0  30.0  0.0  0.0  0.0
      0.0  0.0  0.0  15.0  0.0  0.0
      0.0  0.0  0.0  0.0  15.0  0.0
      0.0  0.0  0.0  0.0  0.0  15.0
    FORCERAO
      1.0  0.5  0.3  0.01  0.02  0.005
      0.0  10.0  20.0  30.0  40.0  50.0
      2.0  1.0  0.6  0.02  0.04  0.01
      5.0  15.0  25.0  35.0  45.0  55.0
      3.0  1.5  0.9  0.03  0.06  0.015
      10.0  20.0  30.0  40.0  50.0  60.0
      1.1  0.6  0.4  0.015  0.025  0.006
      1.0  11.0  21.0  31.0  41.0  51.0
      2.1  1.1  0.7  0.025  0.045  0.011
      6.0  16.0  26.0  36.0  46.0  56.0
      3.1  1.6  1.0  0.035  0.065  0.016
      11.0  21.0  31.0  41.0  51.0  61.0
""")


@pytest.fixture
def minimal_ah1_file(tmp_path: Path) -> Path:
    """Write the minimal AH1 test fixture to a temp file."""
    p = tmp_path / "test.AH1"
    p.write_text(_MINIMAL_AH1, encoding="utf-8")
    return p


# ---------------------------------------------------------------------------
# Header parsing
# ---------------------------------------------------------------------------


class TestAH1HeaderParsing:
    """Test header extraction: body, heading, frequency counts and values."""

    def test_body_count(self, minimal_ah1_file: Path):
        result = parse_ah1(minimal_ah1_file)
        assert result.num_bodies == 1

    def test_heading_count(self, minimal_ah1_file: Path):
        result = parse_ah1(minimal_ah1_file)
        assert result.num_headings == 2

    def test_frequency_count(self, minimal_ah1_file: Path):
        result = parse_ah1(minimal_ah1_file)
        assert result.num_frequencies == 3

    def test_heading_values(self, minimal_ah1_file: Path):
        result = parse_ah1(minimal_ah1_file)
        np.testing.assert_allclose(result.headings, [0.0, 45.0])

    def test_frequency_values(self, minimal_ah1_file: Path):
        result = parse_ah1(minimal_ah1_file)
        np.testing.assert_allclose(result.frequencies, [0.3, 0.5, 0.7])


# ---------------------------------------------------------------------------
# GENERAL section
# ---------------------------------------------------------------------------


class TestAH1GeneralSection:
    """Test GENERAL section: water depth, density, gravity."""

    def test_water_depth(self, minimal_ah1_file: Path):
        result = parse_ah1(minimal_ah1_file)
        assert result.water_depth == 100.0

    def test_water_density(self, minimal_ah1_file: Path):
        result = parse_ah1(minimal_ah1_file)
        assert result.water_density == 1025.0

    def test_gravity(self, minimal_ah1_file: Path):
        result = parse_ah1(minimal_ah1_file)
        assert result.gravity == pytest.approx(9.80665)


# ---------------------------------------------------------------------------
# DRAFT and COG
# ---------------------------------------------------------------------------


class TestAH1DraftAndCOG:
    """Test DRAFT and COG section parsing."""

    def test_draft_values(self, minimal_ah1_file: Path):
        result = parse_ah1(minimal_ah1_file)
        np.testing.assert_allclose(result.drafts, [5.0])

    def test_cog_values(self, minimal_ah1_file: Path):
        result = parse_ah1(minimal_ah1_file)
        assert result.cog.shape == (1, 3)
        np.testing.assert_allclose(result.cog[0], [0.0, 0.0, -2.5])


# ---------------------------------------------------------------------------
# MASS matrix
# ---------------------------------------------------------------------------


class TestAH1MassMatrix:
    """Test MASS section parsing."""

    def test_mass_shape(self, minimal_ah1_file: Path):
        result = parse_ah1(minimal_ah1_file)
        assert result.mass.shape == (1, 6, 6)

    def test_mass_diagonal(self, minimal_ah1_file: Path):
        result = parse_ah1(minimal_ah1_file)
        np.testing.assert_allclose(
            np.diag(result.mass[0]),
            [1000.0, 1000.0, 1000.0, 500.0, 500.0, 500.0],
        )


# ---------------------------------------------------------------------------
# ADDEDMASS
# ---------------------------------------------------------------------------


class TestAH1AddedMass:
    """Test ADDEDMASS section parsing."""

    def test_added_mass_shape(self, minimal_ah1_file: Path):
        """Shape: (num_bodies, num_bodies, num_frequencies, 6, 6)."""
        result = parse_ah1(minimal_ah1_file)
        assert result.added_mass.shape == (1, 1, 3, 6, 6)

    def test_added_mass_diagonal_freq0(self, minimal_ah1_file: Path):
        """First frequency added mass diagonal values."""
        result = parse_ah1(minimal_ah1_file)
        np.testing.assert_allclose(
            np.diag(result.added_mass[0, 0, 0]),
            [100.0, 100.0, 100.0, 50.0, 50.0, 50.0],
        )

    def test_added_mass_diagonal_freq2(self, minimal_ah1_file: Path):
        """Third frequency added mass diagonal values."""
        result = parse_ah1(minimal_ah1_file)
        np.testing.assert_allclose(
            np.diag(result.added_mass[0, 0, 2]),
            [300.0, 300.0, 300.0, 150.0, 150.0, 150.0],
        )


# ---------------------------------------------------------------------------
# DAMPING
# ---------------------------------------------------------------------------


class TestAH1Damping:
    """Test DAMPING section parsing."""

    def test_damping_shape(self, minimal_ah1_file: Path):
        result = parse_ah1(minimal_ah1_file)
        assert result.damping.shape == (1, 1, 3, 6, 6)

    def test_damping_diagonal_freq0(self, minimal_ah1_file: Path):
        result = parse_ah1(minimal_ah1_file)
        np.testing.assert_allclose(
            np.diag(result.damping[0, 0, 0]),
            [10.0, 10.0, 10.0, 5.0, 5.0, 5.0],
        )


# ---------------------------------------------------------------------------
# FORCERAO
# ---------------------------------------------------------------------------


class TestAH1ForceRAO:
    """Test FORCERAO section parsing."""

    def test_excitation_magnitude_shape(self, minimal_ah1_file: Path):
        """Shape: (num_bodies, num_headings, num_frequencies, 6)."""
        result = parse_ah1(minimal_ah1_file)
        assert result.excitation_magnitude.shape == (1, 2, 3, 6)

    def test_excitation_phase_shape(self, minimal_ah1_file: Path):
        result = parse_ah1(minimal_ah1_file)
        assert result.excitation_phase.shape == (1, 2, 3, 6)

    def test_first_rao_magnitude(self, minimal_ah1_file: Path):
        """First body, first heading, first frequency magnitude."""
        result = parse_ah1(minimal_ah1_file)
        np.testing.assert_allclose(
            result.excitation_magnitude[0, 0, 0],
            [1.0, 0.5, 0.3, 0.01, 0.02, 0.005],
        )

    def test_first_rao_phase(self, minimal_ah1_file: Path):
        """First body, first heading, first frequency phase."""
        result = parse_ah1(minimal_ah1_file)
        np.testing.assert_allclose(
            result.excitation_phase[0, 0, 0],
            [0.0, 10.0, 20.0, 30.0, 40.0, 50.0],
        )


# ---------------------------------------------------------------------------
# Edge cases
# ---------------------------------------------------------------------------


class TestAH1EdgeCases:
    """Test parser edge cases."""

    def test_file_not_found_raises(self):
        with pytest.raises(FileNotFoundError):
            parse_ah1("/nonexistent/path/test.AH1")

    def test_empty_file_raises(self, tmp_path: Path):
        p = tmp_path / "empty.AH1"
        p.write_text("* comment only\n", encoding="utf-8")
        with pytest.raises((ValueError, IndexError)):
            parse_ah1(p)
