#!/usr/bin/env python3
"""
ABOUTME: CalculiX INP file writer — converts mesh data (nodes + elements) into
Abaqus-format .inp files for CalculiX ccx solver.
"""

from pathlib import Path
from typing import Optional

import numpy as np

# Element type mapping: gmsh name -> CalculiX type
ELEMENT_TYPE_MAP = {
    "Tetrahedron 4": "C3D4",
    "Tetrahedron 10": "C3D10",
    "Hexahedron 8": "C3D8",
    "Hexahedron 20": "C3D20",
    "Wedge 6": "C3D6",
    "Wedge 15": "C3D15",
    "Line 2": "B31",
    "Line 3": "B32",
}

# CalculiX beam element types
BEAM_ELEMENT_TYPES = {"B31", "B32"}


class INPWriter:
    """
    Write CalculiX-compatible INP files from mesh data.

    Mesh data uses 0-based indexing (gmsh convention). This writer converts
    all IDs to 1-based when writing the INP file (CalculiX convention).
    """

    def __init__(self, nodes: np.ndarray, elements: dict):
        self.nodes = nodes
        self.elements = elements
        self._materials: list[dict] = []
        self._node_sets: list[dict] = []
        self._element_sets: list[dict] = []
        self._beam_sections: list[dict] = []
        self._boundary_conditions: list[dict] = []
        self._loads: list[dict] = []
        self._steps: list[dict] = []

    def add_material(
        self, name: str, youngs_modulus: float, poissons_ratio: float
    ):
        """Add a material definition."""
        self._materials.append({
            "name": name,
            "E": youngs_modulus,
            "nu": poissons_ratio,
        })

    def add_node_set(self, name: str, node_ids: list[int]):
        """Define a named node set. node_ids are 0-based."""
        self._node_sets.append({"name": name, "ids": node_ids})

    def add_element_set(self, name: str, element_ids: list[int]):
        """Define a named element set. element_ids are 0-based."""
        self._element_sets.append({"name": name, "ids": element_ids})

    def add_boundary_condition(
        self, node_set: str, dof: int, value: float = 0.0
    ):
        """Add a boundary condition on a named node set."""
        self._boundary_conditions.append({
            "node_set": node_set, "dof": dof, "value": value,
        })

    def add_load(
        self,
        element_set: str,
        load_type: str,
        magnitude: float,
        direction: Optional[tuple] = None,
    ):
        """Add a load definition."""
        self._loads.append({
            "set": element_set,
            "type": load_type,
            "magnitude": magnitude,
            "direction": direction,
        })

    def add_beam_section(
        self,
        elset: str,
        material: str,
        section_type: str,
        dimensions: tuple,
        direction: tuple = (0.0, 0.0, 1.0),
    ):
        """Add a beam section definition.

        Args:
            elset: Element set name for the beam elements.
            material: Material name (must match an add_material call).
            section_type: Cross-section shape — RECT, CIRC, PIPE, etc.
            dimensions: Section dimensions tuple (depends on section_type).
                RECT: (width, height), CIRC: (radius,), PIPE: (outer_r, thickness).
            direction: Normal direction vector for the beam cross-section.
        """
        self._beam_sections.append({
            "elset": elset,
            "material": material,
            "section_type": section_type.upper(),
            "dimensions": dimensions,
            "direction": direction,
        })

    def add_step(self, step_type: str = "static", description: str = ""):
        """Add an analysis step."""
        self._steps.append({"type": step_type, "description": description})

    # ------------------------------------------------------------------
    # Write
    # ------------------------------------------------------------------

    def write(self, filepath: Path) -> Path:
        """Write the .inp file and return its path."""
        filepath = Path(filepath)
        lines: list[str] = []

        self._write_heading(lines)
        self._write_nodes(lines)
        self._write_elements(lines)
        self._write_node_sets(lines)
        self._write_element_sets(lines)
        self._write_materials(lines)
        self._write_solid_sections(lines)
        self._write_beam_sections(lines)
        self._write_steps(lines)

        filepath.write_text("\n".join(lines) + "\n")
        return filepath

    # ------------------------------------------------------------------
    # Private section writers
    # ------------------------------------------------------------------

    def _write_heading(self, lines: list[str]):
        lines.append("*HEADING")
        lines.append("CalculiX analysis generated by digitalmodel")

    def _write_nodes(self, lines: list[str]):
        lines.append("*NODE")
        for i, (x, y, z) in enumerate(self.nodes):
            lines.append(f"{i + 1}, {x:.8E}, {y:.8E}, {z:.8E}")

    def _write_elements(self, lines: list[str]):
        elem_id = 1
        for gmsh_name, data in self.elements.items():
            ccx_type = ELEMENT_TYPE_MAP.get(gmsh_name)
            if ccx_type is None:
                continue
            if ccx_type in BEAM_ELEMENT_TYPES:
                elset = f"EBEAM_{ccx_type}"
            else:
                elset = "EALL"
            lines.append(f"*ELEMENT, TYPE={ccx_type}, ELSET={elset}")
            for row in data["connectivity"]:
                node_refs = ", ".join(str(int(n) + 1) for n in row)
                lines.append(f"{elem_id}, {node_refs}")
                elem_id += 1

    def _write_node_sets(self, lines: list[str]):
        for ns in self._node_sets:
            lines.append(f"*NSET, NSET={ns['name']}")
            ids_1based = [str(nid + 1) for nid in ns["ids"]]
            for i in range(0, len(ids_1based), 16):
                lines.append(", ".join(ids_1based[i:i + 16]))

    def _write_element_sets(self, lines: list[str]):
        for es in self._element_sets:
            lines.append(f"*ELSET, ELSET={es['name']}")
            ids_1based = [str(eid + 1) for eid in es["ids"]]
            for i in range(0, len(ids_1based), 16):
                lines.append(", ".join(ids_1based[i:i + 16]))

    def _write_materials(self, lines: list[str]):
        for mat in self._materials:
            lines.append(f"*MATERIAL, NAME={mat['name']}")
            lines.append("*ELASTIC")
            lines.append(f"{mat['E']}, {mat['nu']}")

    def _write_solid_sections(self, lines: list[str]):
        has_solid = any(
            ELEMENT_TYPE_MAP.get(name) not in BEAM_ELEMENT_TYPES
            for name in self.elements
            if ELEMENT_TYPE_MAP.get(name) is not None
        )
        if self._materials and has_solid:
            mat_name = self._materials[0]["name"]
            lines.append(f"*SOLID SECTION, ELSET=EALL, MATERIAL={mat_name}")

    def _write_beam_sections(self, lines: list[str]):
        for bs in self._beam_sections:
            lines.append(
                f"*BEAM SECTION, ELSET={bs['elset']}, "
                f"MATERIAL={bs['material']}, SECTION={bs['section_type']}"
            )
            lines.append(", ".join(str(d) for d in bs["dimensions"]))
            lines.append(", ".join(str(v) for v in bs["direction"]))

    def _write_steps(self, lines: list[str]):
        for step in self._steps:
            lines.append("*STEP")
            lines.append(f"*{step['type'].upper()}")
            self._write_boundary_conditions(lines)
            self._write_loads(lines)
            lines.append("*NODE FILE")
            lines.append("U")
            lines.append("*EL FILE")
            lines.append("S")
            lines.append("*END STEP")

        # If no steps defined but we have BCs/loads, create a default step
        if not self._steps and (self._boundary_conditions or self._loads):
            lines.append("*STEP")
            lines.append("*STATIC")
            self._write_boundary_conditions(lines)
            self._write_loads(lines)
            lines.append("*NODE FILE")
            lines.append("U")
            lines.append("*EL FILE")
            lines.append("S")
            lines.append("*END STEP")

    def _write_boundary_conditions(self, lines: list[str]):
        if not self._boundary_conditions:
            return
        lines.append("*BOUNDARY")
        for bc in self._boundary_conditions:
            lines.append(
                f"{bc['node_set']}, {bc['dof']}, {bc['dof']}, {bc['value']}"
            )

    def _write_loads(self, lines: list[str]):
        for load in self._loads:
            if load["type"].lower() == "cload":
                lines.append("*CLOAD")
                direction = load.get("direction") or (1, 0, 0)
                for dof_idx, component in enumerate(direction, start=1):
                    if abs(component) > 1e-15:
                        mag = load["magnitude"] * component
                        lines.append(f"{load['set']}, {dof_idx}, {mag}")
