name: digitalmodel
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pandas
  - pip
  - pip:
      - -r requirements.txt  # source pip specific requirements 
    #- -r dev_tools/requirements.txt  # source pip specific requirements 
