name: digitalmodel
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pandas
  - pip
  - pip:
      - plotly
      - dash
      - pyyaml
      - bumpver
      - webcolors
      - matplotlib
      - scipy
      - pandas
      - xlrd
      - openpyxl
      - imgkit
      - xmltodict
      - OrcFxAPI
      - docx
      - deepdiff
      - pytest
      - sympy
      - kaleido
      - winreg