# Input Parameters for Parametric Analysis
# Source: C06_Discretised_CALM_Buoy.yml
# Generated: 2026-01-18 22:19:53

water_depth: 100
current_speed: 1
wind_speed: 12
water_density: 1.025
stage_durations:
- 10
- 100
wave_direction: 180

