# Input Parameters for Parametric Analysis
# Source: HeaveCompensatedWinch.yml
# Generated: 2026-01-18 21:52:04

water_depth: 100
current_speed: 0
wind_speed: 0
water_density: 1.025
stage_durations:
- 10
- 100
wave_direction: 180

