@startuml  cp_calculation

scale 2
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Tomato

title CP | Calculation

start
:CP Calculation;


partition Inputs {
:Environment - Seawater \nSalinity and Resistivity;

  note right
    Seawater properties depend on:
    - dissolved oxygen content
    - sea currents
    - temperature
    - marine growth
    - water depth 
    - tide changes 
    - Seawater pH, carbonate content etc. (calcaresous layers)
    - etc.
  end note

:Enviornment - Seabed sediments;

  note right
    Seabed sediments influences CP system behavior:
    - temperature
    - bacterial growth
    - salinity
    - sediment coarseness etc.
    - etc.
  end note

:Structure - Wetted Area;

  note right
    Area considers following:
    - tide changes for fixed structures
    - Draft changes for ships

  end note

:Structure - Coatings\n influence Current demand requirements;

  note right
    CP  varies with:
    - Low vs. high durability
    - Coating gaps
    - Coating holidays
    - etc.

  end note

:(non-metallic) Coating;
  note right
    - used when CP demand for bare metal is high
      - eg: subsea structures are coated
      - eg: Ships are also Coating breakdown factor
  end note

}

partition Design Considerations {


:Protective Potentials;
  note right
    - design range: -0.9V to -1.05V
    - < -0.8V (underprotection)
    - > -1.15V (overprotection)
    - These potentials may not apply for CP 
    by galvanic andoes based on Al or Zn
  end note

:Detrimental effects of CP;
  note right
    - No ventilition can develop explosive gas mixure (H2/O2)
    - calcareous layer (consisting primarily of calcium carbonate)
      - forms film coating
      - may insulate connectors of CP system
  end note
}


partition CP Design {

:Structure Electrical continuity & current drain;
  note right
    - TBA
  end note

:electrochemical potential;
  note right
    - Standard calomel electrode (SCE)
  end note

:Design Life;
  note right
    - TBA
  end note

:Coating breakdown factor\nIf coating present;
  note right
    - fc = a + b*t 
    - t in years is coating age
    - fcm (mean)
    - fcf (final) 
  end note

:Design Current Densitites;
  note right
    - Initial design current density
    - Final design current density
    - mean design current density (typ. 0.15 or 0.2 V more negative than design protective potenttial)
    - Guidelines are provided in code
    - all electrically connected items for COP system  considered for current drain
  end note

:Anode Weight Required;
  note right
    Evaluate Anode weight based on:
    - Current capacity
    - Based on anode geometry
    - etc.
  end note

}

partition Anode Considerations {

:Materials;
  note right
    - design electrochemical capacity, ε (Ah /kg)
    - design closed circuit anode potential, Eoa (V)
    - Ohms & Faradays laws use ε & Eoa to calculate:
      - anode current output
      - required anode mass
    - Al - for higher electrochemical capacity
    - Zn - more reliable in anaerobic conditions 
    i.e. sediments or internal compartments with high bacterial activity
  end note

:Geometry;
  note right
    - Initial anode diemensions are calculated using  anode resistance, Ra 
    - Anode utilization
    - Slender Stand-off
      - short/long (l/w ratio)
      - long stand-off (100 kg + )for Platforms ubstructures, susbsea templates
    - Elongated, flush mounted
      - Compared to stand-off, a flush-mounted anode with the same net anode mass 
      will have a lower anode current output and lower utilisation factor.
    - bracelet (pipelines)
  end note

:Electrical continuity & current drain;
  note right
    - None
  end note

:Anode Current Demand Checks;
  note right
    - Initial check
    - End of Life check
  end note

}
stop
@enduml