@startuml  fst_cp_work

scale 2
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Tomato

title FST CP | Pending Work

start
:Complete Aluminum Calculations;
  note right
    - Anode geometry properties
    - Final calulcations
    - others?
  end note

:Complete Zinc Calculations;

  note right
    - Zinc densitiy
    - Zinc Potential, resistivity etc.
    - Anode related calculations
  end note


stop
@enduml