# Stress Rainflow to Damage Analysis Configuration
# Module: Fatigue Damage Calculation using Miner's Rule
# Created: 2025-01-24
# Version: 1.0.0
# Status: REQUIRES CLARIFICATION - See comments marked [CLARIFY]

# ============================================================================
# PROJECT IDENTIFICATION
# ============================================================================
project:
  name: "Stress Rainflow to Damage Analysis"
  description: "Calculate fatigue damage rates from stress rainflow cycle counts using S-N curves"
  analysis_type: "fatigue-damage-miners-rule"
  project_id: "FATIGUE-DAMAGE-001"
  version: "1.0.0"
  date: "2025-01-24"
  author: "Engineering Team"
  
# ============================================================================
# INPUT DATA CONFIGURATION
# ============================================================================
input_data:
  # Stress rainflow input files
  stress_rainflow:
    # Base folder containing stress rainflow CSV files
    data_folder: "stress_rainflow"
    
    # File naming pattern for input files
    file_pattern: "{config}_FC{fc_number:03d}_Strut{strut_number}_{location_id}_stress_rainflow.csv"
    
    # Filter pattern for file selection
    filter_pattern: "*_stress_rainflow.csv"
    
    # Column specifications
    columns:
      stress_range: "stress range (Mpa)"  # Stress range in MPa
      annual_cycles: "Cycles_Annual"      # Annual cycle count
    
    # Data validation
    validation:
      min_stress_range: 0.0     # Minimum valid stress range [MPa]
      max_stress_range: 2000.0  # Maximum valid stress range [MPa]
      min_cycles: 0             # Minimum cycle count
      max_cycles: 1.0e10        # Maximum cycle count

  # Processing options
  processing:
    # Batch processing configuration
    batch_mode: true
    continue_on_error: true
    parallel_processing: false  # Can be enabled for large datasets
    max_workers: 4             # Number of parallel workers if enabled
    
    # File selection options
    file_selection:
      all_files: true          # Process all matching files
      # Alternatively, specify specific patterns:
      # configs: ["fsts_l015_125km3_l100_pb", "fsts_l015"]
      # fc_numbers: [1, 10]     # Will process FC001, FC010
      # strut_numbers: [1, 2, 3, 4, 5, 6, 7, 8]
      # location_ids: ["loc01", "loc02", "loc03", "loc04", "loc05", "loc06", "loc07", "loc08", "loc09", "loc10"]

# ============================================================================
# S-N CURVE CONFIGURATION
# ============================================================================
sn_curve:
  # Curve selection
  curve_type: "ABS-E"          # ABS E curve as specified
  environment: "in-air"        # In air conditions
  
  # Two-Segment S-N curve parameters (ABS E curve, in air)
  # Segment 1: log10(N) = log_a - m * log10(S)   [N < 10^7]
  # Segment 2: log10(N) = log_c - r * log10(S)   [N >= 10^7]
  # Where: N = cycles to failure, S = stress range [MPa]
  parameters:
    # Segment 1 parameters (High Stress, N < 10^7 cycles)
    log_a: 12.0170             # log10(a) - ABS'20 Table 1
    m: 3.0                     # Slope for Segment 1

    # Transition point (where Segment 1 meets Segment 2)
    fatigue_limit_cycles: 1.0e7        # Transition at 10 million cycles
    fatigue_limit_stress: 47.0         # Stress at transition point [MPa] - ABS'20 Table 1

    # Segment 2 parameters (Low Stress, N >= 10^7 cycles)
    two_segment:
      enabled: true                     # Enable two-segment S-N curve
      transition_cycles: 1.0e7          # Must match fatigue_limit_cycles
      log_c: 15.362                     # log10(c) for Segment 2 - ABS'20 database
      r: 5.0                            # Slope for Segment 2
  
  # Alternative curve references (for comparison/validation)
  alternative_curves:
    DNV_C:
      enabled: false
      log_a: 12.049
      m: 3.0
    GL_E:
      enabled: false  
      log_a: 12.164
      m: 3.0
    API_X:
      enabled: false
      log_a: 12.037
      m: 3.0

# ============================================================================
# THICKNESS CORRECTION
# ============================================================================
thickness_correction:
  enabled: true
  reference_thickness_mm: 22.0    # Reference thickness from spec
  
  # Thickness correction formula: TCF = (t/t_ref)^tk
  thickness_exponent_tk: 0.25     # Confirmed value for steel (ABS guideline)
  
  # Location-specific thicknesses from location_metadata.csv
  location_thickness_mm:
    loc01: 50.0    # Mooring Blisters 50mm PL
    loc02: 25.0    # Mooring Blisters 25mm PL
    loc03: 25.0    # Mooring Interior 25mm PL
    loc04: 20.0    # Mooring Interior 20mm PL
    loc05: 18.0    # Mooring Interior 18mm PL
    loc06: 20.0    # Mooring Interior 20mm PL (ELEM 58090)
    loc07: 20.0    # Mooring Interior 20mm PL (ELEM 68254)
    loc08: 50.0    # Mooring Blisters 50mm PL (ELEM 1126659)
    loc09: 50.0    # Mooring Blisters 50mm PL (ELEM 1125808)
    loc10: 50.0    # Mooring Blisters 50mm PL (ELEM 1127909)
    default: 22.0  # Default reference thickness

# ============================================================================
# STRESS MODIFICATION FACTORS
# ============================================================================
stress_factors:
  # Stress Concentration Factor (SCF)
  # SCFs need to be applied to the stress ranges
  stress_concentration:
    enabled: true               # Apply SCF to stress ranges
    location_scf:
      loc01: 1.15    # Mooring Blisters 50mm PL, Max Overall
      loc02: 2.0     # Mooring Blisters 25mm PL, Max Overall
      loc03: 1.15    # Mooring Interior 25mm PL, Max Overall
      loc04: 1.15    # Mooring Interior 20mm PL, Max Overall
      loc05: 1.15    # Mooring Interior 18mm PL, Max Overall
      loc06: 1.15    # Mooring Interior 20mm PL, ELEM 58090
      loc07: 1.15    # Mooring Interior 20mm PL, ELEM 68254
      loc08: 1.15    # Mooring Blisters 50mm PL, ELEM 1126659
      loc09: 1.15    # Mooring Blisters 50mm PL, ELEM 1125808
      loc10: 1.15    # Mooring Blisters 50mm PL, ELEM 1127909
      default: 1.0
  
  # Mean stress correction
  # User confirmed no mean stress correction needed
  mean_stress_correction:
    enabled: false
    method: "none"  # No correction applied
    ultimate_tensile_strength_mpa: 550  # Not used
    yield_strength_mpa: 355              # Not used

# ============================================================================
# DAMAGE CALCULATION
# ============================================================================
damage_calculation:
  # Miner's Rule parameters
  miners_rule:
    damage_sum_threshold: 1.0   # Damage sum at failure (typically 1.0)
    
  # Safety factors
  safety_factors:
    design_factor: 5.0          # From location_metadata.csv
    fatigue_safety_factor: 1.0  # Applied to S-N curve (typically 1.0 for analysis)
    
  # Calculation options
  options:
    # Two-segment S-N curve behavior (NO FATIGUE ENDURANCE LIMIT)
    ignore_below_fatigue_limit: false   # FALSE = All stress cycles contribute to damage
                                        # TRUE = Infinite life below fatigue_limit_stress
                                        # For two-segment curve, set FALSE to use both segments
    cumulative_damage_method: "linear"  # Linear Miner's rule damage accumulation

# ============================================================================
# OUTPUT CONFIGURATION
# ============================================================================
output:
  # Output folder configuration
  folders:
    # As specified in user_spec.md
    base: "specs/modules/fatigue-analysis/reference-seastate-scale-load/output/rainflow/stress_range"
    results: "damage_results"
    plots: "visualizations"
    reports: "reports"
    
  # File naming pattern for output files
  file_naming:
    pattern: "{config}_FC{fc_number:03d}_Strut{strut_number}_{location_id}_damage_rate"
    extension: "csv"
    
  # Output file format
  formats:
    # Damage results CSV
    damage_results:
      enabled: true
      columns:
        - "stress_range_mpa"      # Stress range bins
        - "cycles_annual"          # Annual cycles per bin
        - "cycles_to_failure"      # N from S-N curve
        - "damage_per_bin"         # ni/Ni for each bin
        - "damage_rate_per_year"   # Annual damage rate per bin
      include_total: true          # Add total damage rate row
      
    # Summary report
    summary_report:
      enabled: true
      filename: "damage_analysis_summary.csv"
      columns:
        - "filename"
        - "config"
        - "fc_number"
        - "strut_number"
        - "location_id"
        - "thickness_mm"
        - "thickness_correction_factor"
        - "total_cycles_per_year"
        - "total_damage_rate_per_year"
        - "fatigue_life_years"
        - "safety_margin"

# ============================================================================
# VISUALIZATION CONFIGURATION
# ============================================================================
visualization:
  # Damage vs stress range plot
  damage_plot:
    enabled: true
    figure_size: [12, 8]
    dpi: 150
    
    # Plot components
    components:
      damage_histogram: true       # Bar plot of damage vs stress range
      sn_curve_overlay: true       # Show S-N curve on same plot
      cumulative_damage: true      # Cumulative damage curve
      
    # Plot styling
    styling:
      title: "Fatigue Damage Analysis - {config} FC{fc_number:03d} Strut{strut_number} {location_id}"
      xlabel: "Stress Range [MPa]"
      ylabel_left: "Annual Damage Rate [1/year]"
      ylabel_right: "Cycles to Failure"
      grid: true
      log_scale_y: true            # Log scale for damage rate
      log_scale_x: false           # Linear scale for stress range
      
    # Legend configuration
    legend:
      location: "upper right"
      show_total_damage: true
      show_fatigue_life: true
      
  # S-N curve comparison plot
  sn_curve_plot:
    enabled: true
    show_design_curve: true
    show_mean_curve: false
    show_rainflow_points: true
    annotate_fatigue_limit: true

# ============================================================================
# VALIDATION AND QA
# ============================================================================
validation:
  # Input validation
  input_checks:
    check_file_existence: true
    check_column_names: true
    check_data_ranges: true
    check_sum_cycles: true         # Verify total cycles are reasonable
    
  # Calculation validation
  calculation_checks:
    verify_damage_sum: true        # Check Miner's sum calculation
    check_thickness_correction: true
    verify_sn_curve: true          # Test S-N curve with known points
    
  # Output validation
  output_checks:
    check_file_generation: true
    verify_plot_generation: true
    check_summary_completeness: true
    
  # Validation thresholds
  thresholds:
    max_annual_damage: 1.0         # Alert if damage > 1.0/year (immediate failure)
    min_fatigue_life_years: 1.0    # Alert if life < 1 year
    max_stress_range_mpa: 1000.0   # Alert for unrealistic stress

# ============================================================================
# LOGGING AND REPORTING
# ============================================================================
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_to_file: true
  log_file: "damage_analysis_{timestamp}.log"
  
  # Progress reporting
  progress:
    show_progress_bar: true
    report_interval: 10  # Report every N files
    
  # Error handling
  errors:
    save_error_log: true
    include_traceback: true
    continue_on_error: true

# ============================================================================
# PERFORMANCE OPTIMIZATION
# ============================================================================
performance:
  # Memory management
  chunk_size: 1000          # Process in chunks for large files
  
  # Caching
  cache_sn_calculations: true  # Cache S-N curve calculations
  
  # Parallel processing (if enabled)
  parallel:
    enabled: false          # Enable for production run with 64 cores available
    max_workers: 4          # Can increase to 32 for production
    batch_size: 50

# ============================================================================
# NOTES AND CLARIFICATIONS COMPLETED
# ============================================================================
# Clarifications and corrections:
# 1. Location thickness values: Retrieved from location_metadata.csv
# 2. ABS E curve parameters: CORRECTED to log_a=12.0170, m=3.0, S0=47.0 MPa (from ABS Table 1)
# 3. Thickness exponent tk=0.25 confirmed
# 4. SCFs NOT included in stress ranges - MUST be applied during calculation
# 5. No mean stress correction needed
# 6. Output to specs/modules/fatigue-analysis/reference-seastate-scale-load/output/rainflow/stress_range
# 7. Processing scope: Start with 5 files, then process all 224 files
# 8. Design factor of 5 from metadata for fatigue life calculation
# 9. Two-segment S-N curve with transition at 10^7 cycles per ABS specification

# ============================================================================
# REFERENCES
# ============================================================================
references:
  - "ABS Guide for Fatigue Assessment of Offshore Structures (2020)"
  - "Section 4: Fatigue Design Factors"
  - "URL: https://pub-rm20.apps.eagle.org/r/2/2020-06-01/Section-4-Fatigue-Design-Factors"
  - "DNV-RP-C203: Fatigue Design of Offshore Steel Structures"
  - "API 579-1/ASME FFS-1: Fitness-For-Service"