# Stress Rainflow to Damage Analysis Configuration - PRODUCTION (ALL FILES)
# Module: Fatigue Damage Calculation using Miner's Rule
# Created: 2025-01-25
# Version: 1.0.0
# Status: READY FOR PRODUCTION

# ============================================================================
# PROJECT IDENTIFICATION
# ============================================================================
project:
  name: "Stress Rainflow to Damage Analysis - Production Run"
  description: "Calculate fatigue damage rates from stress rainflow cycle counts using S-N curves (all 224 files)"
  analysis_type: "fatigue-damage-miners-rule"
  project_id: "FATIGUE-DAMAGE-PROD"
  version: "1.0.0"
  date: "2025-01-25"
  author: "Engineering Team"
  
# ============================================================================
# INPUT DATA CONFIGURATION - PRODUCTION SET (ALL FILES)
# ============================================================================
input_data:
  # Stress rainflow input files
  stress_rainflow:
    # Base folder containing stress rainflow CSV files
    data_folder: "D:/1522/ctr9/fatigue_wsp_method/07c_fatigue/output/rainflow_stress"
    
    # File naming pattern for input files
    file_pattern: "{config}_FC{fc_number:03d}_Strut{strut_number}_{location_id}_stress_rainflow.csv"
    
    # Filter pattern for file selection
    filter_pattern: "*_stress_rainflow.csv"
    
    # Column specifications
    columns:
      stress_range: "stress range (Mpa)"  # Stress range in MPa
      annual_cycles: "Cycles_Annual"      # Annual cycle count
    
    # Data validation
    validation:
      min_stress_range: 0.0     # Minimum valid stress range [MPa]
      max_stress_range: 2000.0  # Maximum valid stress range [MPa]
      min_cycles: 0             # Minimum cycle count
      max_cycles: 1.0e10        # Maximum cycle count

  # Processing options - PRODUCTION SET
  processing:
    # Batch processing configuration
    batch_mode: true
    continue_on_error: true
    parallel_processing: true   # Enable parallel processing for production
    max_workers: 32            # Use 32 cores (half of 64 available)
    
    # File selection options - PROCESS ALL FILES
    file_selection:
      all_files: true          # Process all matching files (18,144 total)
      # Full production run parameters (for reference):
      # - Configurations: fsts_l015_125km3_l100_pb, fsts_l015, fsts_l095_125km3_l000_pb, fsts_l095
      # - FC Numbers: FC001 through FC081 (81 flight conditions)
      # - Strut Numbers: 1 through 8
      # - Location IDs: loc02, loc03, loc05, loc06, loc07, loc09, loc10 (7 locations)
      # Total files: 18,144 (81 FC × 8 Struts × 7 Locations × 4 configs)

# ============================================================================
# S-N CURVE CONFIGURATION
# ============================================================================
sn_curve:
  # Curve selection
  curve_type: "ABS-E"          # ABS E curve as specified
  environment: "in-air"        # In air conditions
  
  # S-N curve parameters (ABS E curve, in air)
  # Format: log10(N) = log10(a) - m * log10(S)
  # Where: N = number of cycles to failure, S = stress range [MPa]
  parameters:
    # CORRECTED ABS E curve parameters from official ABS table
    log_a: 12.0170             # log10(1.04e12) - Verified from ABS Table 1
    m: 3.0                     # Slope (negative inverse slope)
    
    # Fatigue limit (endurance limit)
    fatigue_limit_cycles: 1.0e7     # Cycles at fatigue limit
    fatigue_limit_stress: 47.0      # CORRECTED: Stress at fatigue limit [MPa] from ABS Table 1
    
    # Two-segment S-N curve option (for N > 10^7 cycles)
    two_segment:
      enabled: true            # ABS E has two segments
      transition_cycles: 1.0e7 # Transition at fatigue limit
      log_c: 15.378           # log10(2.39e15) for second segment
      r: 5.0                  # Slope for N > 10^7

# ============================================================================
# THICKNESS CORRECTION
# ============================================================================
thickness_correction:
  enabled: true
  reference_thickness_mm: 22.0    # Reference thickness from spec
  
  # Thickness correction formula: TCF = (t/t_ref)^tk
  thickness_exponent_tk: 0.25     # Confirmed value for steel (ABS guideline)
  
  # Location-specific thicknesses from location_metadata.csv
  location_thickness_mm:
    loc01: 50.0    # Mooring Blisters 50mm PL
    loc02: 25.0    # Mooring Blisters 25mm PL
    loc03: 25.0    # Mooring Interior 25mm PL
    loc04: 20.0    # Mooring Interior 20mm PL
    loc05: 18.0    # Mooring Interior 18mm PL
    loc06: 20.0    # Mooring Interior 20mm PL (ELEM 58090)
    loc07: 20.0    # Mooring Interior 20mm PL (ELEM 68254)
    loc08: 50.0    # Mooring Blisters 50mm PL (ELEM 1126659)
    loc09: 50.0    # Mooring Blisters 50mm PL (ELEM 1125808)
    loc10: 50.0    # Mooring Blisters 50mm PL (ELEM 1127909)
    default: 22.0  # Default reference thickness

# ============================================================================
# STRESS MODIFICATION FACTORS
# ============================================================================
stress_factors:
  # Stress Concentration Factor (SCF)
  # SCFs need to be applied to the stress ranges
  stress_concentration:
    enabled: true               # Apply SCF to stress ranges
    location_scf:
      loc01: 1.15    # Mooring Blisters 50mm PL, Max Overall
      loc02: 2.0     # Mooring Blisters 25mm PL, Max Overall
      loc03: 1.15    # Mooring Interior 25mm PL, Max Overall
      loc04: 1.15    # Mooring Interior 20mm PL, Max Overall
      loc05: 1.15    # Mooring Interior 18mm PL, Max Overall
      loc06: 1.15    # Mooring Interior 20mm PL, ELEM 58090
      loc07: 1.15    # Mooring Interior 20mm PL, ELEM 68254
      loc08: 1.15    # Mooring Blisters 50mm PL, ELEM 1126659
      loc09: 1.15    # Mooring Blisters 50mm PL, ELEM 1125808
      loc10: 1.15    # Mooring Blisters 50mm PL, ELEM 1127909
      default: 1.0
  
  # Mean stress correction
  # User confirmed no mean stress correction needed
  mean_stress_correction:
    enabled: false
    method: "none"  # No correction applied

# ============================================================================
# DAMAGE CALCULATION
# ============================================================================
damage_calculation:
  # Miner's Rule parameters
  miners_rule:
    damage_sum_threshold: 1.0   # Damage sum at failure (typically 1.0)
    
  # Safety factors
  safety_factors:
    design_factor: 5.0          # From location_metadata.csv
    fatigue_safety_factor: 1.0  # Applied to S-N curve (typically 1.0 for analysis)
    
  # Calculation options
  options:
    ignore_below_fatigue_limit: false  # Include cycles below fatigue limit
    cumulative_damage_method: "linear" # Linear damage accumulation

# ============================================================================
# OUTPUT CONFIGURATION
# ============================================================================
output:
  # Output folder configuration
  folders:
    # As specified in user_spec.md
    base: "D:/1522/ctr9/fatigue_wsp_method/07c_fatigue/output/damage"
    results: "damage_results"
    plots: "visualizations"
    reports: "reports"
    
  # File naming pattern for output files
  file_naming:
    pattern: "{config}_FC{fc_number:03d}_Strut{strut_number}_{location_id}_damage_rate"
    extension: "csv"
    
  # Output file format
  formats:
    # Damage results CSV
    damage_results:
      enabled: true
      columns:
        - "stress_range_mpa"      # Stress range bins
        - "cycles_annual"          # Annual cycles per bin
        - "cycles_to_failure"      # N from S-N curve
        - "damage_per_bin"         # ni/Ni for each bin
        - "damage_rate_per_year"   # Annual damage rate per bin
      include_total: true          # Add total damage rate row
      
    # Summary report
    summary_report:
      enabled: true
      filename: "damage_analysis_summary.csv"
      columns:
        - "filename"
        - "config"
        - "fc_number"
        - "strut_number"
        - "location_id"
        - "thickness_mm"
        - "thickness_correction_factor"
        - "total_cycles_per_year"
        - "total_damage_rate_per_year"
        - "fatigue_life_years"
        - "safety_margin"

# ============================================================================
# VISUALIZATION CONFIGURATION
# ============================================================================
visualization:
  # Damage vs stress range plot
  damage_plot:
    enabled: true
    figure_size: [12, 8]
    dpi: 150
    
    # Plot components
    components:
      damage_histogram: true       # Bar plot of damage vs stress range
      sn_curve_overlay: true       # Show S-N curve on same plot
      cumulative_damage: true      # Cumulative damage curve
      
    # Plot styling
    styling:
      title: "Fatigue Damage Analysis - {config} FC{fc_number:03d} Strut{strut_number} {location_id}"
      xlabel: "Stress Range [MPa]"
      ylabel_left: "Annual Damage Rate [1/year]"
      ylabel_right: "Cycles to Failure"
      grid: true
      log_scale_y: true            # Log scale for damage rate
      log_scale_x: false           # Linear scale for stress range
      
    # Legend configuration
    legend:
      location: "upper right"
      show_total_damage: true
      show_fatigue_life: true
      
  # S-N curve comparison plot
  sn_curve_plot:
    enabled: true
    show_design_curve: true
    show_mean_curve: false
    show_rainflow_points: true
    annotate_fatigue_limit: true

# ============================================================================
# VALIDATION AND QA
# ============================================================================
validation:
  # Input validation
  input_checks:
    check_file_existence: true
    check_column_names: true
    check_data_ranges: true
    check_sum_cycles: true         # Verify total cycles are reasonable
    
  # Calculation validation
  calculation_checks:
    verify_damage_sum: true        # Check Miner's sum calculation
    check_thickness_correction: true
    verify_sn_curve: true          # Test S-N curve with known points
    
  # Output validation
  output_checks:
    check_file_generation: true
    verify_plot_generation: true
    check_summary_completeness: true
    
  # Validation thresholds
  thresholds:
    max_annual_damage: 1.0         # Alert if damage > 1.0/year (immediate failure)
    min_fatigue_life_years: 1.0    # Alert if life < 1 year
    max_stress_range_mpa: 1000.0   # Alert for unrealistic stress

# ============================================================================
# LOGGING AND REPORTING
# ============================================================================
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  log_to_file: true
  log_file: "damage_analysis_{timestamp}.log"
  
  # Progress reporting
  progress:
    show_progress_bar: true
    report_interval: 10  # Report every 10 files
    
  # Error handling
  errors:
    save_error_log: true
    include_traceback: true
    continue_on_error: true

# ============================================================================
# PERFORMANCE OPTIMIZATION
# ============================================================================
performance:
  # Memory management
  chunk_size: 1000          # Process in chunks for large files
  
  # Caching
  cache_sn_calculations: true  # Cache S-N curve calculations
  
  # Parallel processing (enabled for production)
  parallel:
    enabled: true           # Multi-threaded processing
    max_workers: 32         # Use 32 cores (half of 64 available)
    batch_size: 50          # Files per batch

# ============================================================================
# PRODUCTION RUN NOTES
# ============================================================================
# This configuration processes all available stress rainflow files:
# - Configurations: 
#   • fsts_l015_125km3_l100_pb
#   • fsts_l015
#   • fsts_l095_125km3_l000_pb
#   • fsts_l095
# - FC Numbers: FC001 through FC081 (81 flight conditions)
# - Struts: 1 through 8 (all struts)
# - Locations: loc02, loc03, loc05, loc06, loc07, loc09, loc10 (7 locations)
# - Total files: 18,144 (81 FC × 8 Struts × 7 Locations × 4 Configs)
#
# Performance optimizations:
# - Parallel processing with 32 workers (half of 64 cores)
# - S-N calculation caching enabled
# - Batch processing for efficient memory usage
#
# Run sample configuration first to verify setup before production run.

# ============================================================================
# REFERENCES
# ============================================================================
references:
  - "ABS Guide for Fatigue Assessment of Offshore Structures (2020)"
  - "Section 4: Fatigue Design Factors"
  - "URL: https://pub-rm20.apps.eagle.org/r/2/2020-06-01/Section-4-Fatigue-Design-Factors"
  - "DNV-RP-C203: Fatigue Design of Offshore Steel Structures"
  - "API 579-1/ASME FFS-1: Fitness-For-Service"