# Load Scaling Program Configuration
# Fatigue Analysis using Reference Seastate Scaling Method
# Created: 2025-01-23
# Version: 1.0.0

# ============================================================================
# PROJECT IDENTIFICATION
# ============================================================================
project:
  name: "Load Scaling Fatigue Analysis"
  description: "Fatigue analysis using reference seastate scaling methodology"
  analysis_type: "reference-seastate-scaling"
  project_id: "LS-FAT-001"
  version: "1.0.0"
  date: "2025-01-23"
  
# ============================================================================
# INPUT DATA CONFIGURATION
# ============================================================================
input_data:
  # Reference Seastate Configuration
  reference_seastate:
    # Metadata file containing reference load case definitions
    metadata_file: "specs/modules/fatigue-analysis/reference-seastate-scaling-fatigue/input/reference_seastate_definitions_sample.csv"
    
    # Time trace data folder containing reference tension time series
    data_folder: "specs/modules/fatigue-analysis/reference-seastate-scaling-fatigue/reference_data"
    
    # File pattern for reference data files
    file_pattern: "{config}_{env_ref}_Strut{strut_id}.csv"
    
    # Column containing tension data in reference files
    tension_column: "Effective Tension (kN)"
    
  # Fatigue Seastates Configuration
  fatigue_seastates:
    # Metadata file containing fatigue seastate definitions
    metadata_file: "specs/modules/fatigue-analysis/reference-seastate-scaling-fatigue/input/fatigue_seastates_sample.csv"
    
    # Column mapping for fatigue seastate parameters
    column_mapping:
      wind_speed: "Wind Speed (m/s)"
      wind_direction: "Wind Dir (°)"
      wave_height: "Hs (m)"
      wave_period: "Tp (s)"
      wave_direction: "Wave Dir (°)"
      occurrence: "Occurrence (%)"
      
  # Vessel Configurations
  vessel_configurations:
    # Four vessel loading configurations
    configs:
      - id: "fsts_l015"
        name: "Light Load 15%"
        description: "15% loading condition"
        ballast_config: "Light"
        
      - id: "fsts_l095"  
        name: "Full Load 95%"
        description: "95% loading condition"
        ballast_config: "Full"
        
      - id: "fsts_l015_125km3_l100_pb"
        name: "Light Load with Port Ballast"
        description: "15% loading with 125km³ and 100% port ballast"
        ballast_config: "Light_PB"
        
      - id: "fsts_l095_125km3_l000_pb"
        name: "Full Load with No Ballast"
        description: "95% loading with 125km³ and 0% port ballast"
        ballast_config: "Full_NB"
    
    # Strut components to analyze
    struts: [1, 2, 3, 4, 5, 6, 7, 8]
    
# ============================================================================
# LOAD SCALING METHOD
# ============================================================================
load_scaling:
  # Reference Selection Method
  reference_selection:
    # Wind reference selection criteria
    wind:
      method: "closest_direction"
      tolerance_degrees: 45  # Maximum angular difference for matching
      
    # Wave reference selection criteria  
    wave:
      method: "closest_direction_and_period"
      direction_tolerance_degrees: 45
      period_tolerance_seconds: 1.0
      priority: ["direction", "period"]  # Priority order for matching
      
  # Scaling Parameters
  scaling_parameters:
    # Wind scaling formula: (V_fatigue / V_reference)^2
    wind:
      formula: "(V_fatigue / V_reference)^2"
      exponent: 2.0
      min_reference_speed: 5.0  # Minimum reference wind speed (m/s)
      
    # Wave scaling formula: Hs_fatigue / Hs_reference  
    wave:
      formula: "Hs_fatigue / Hs_reference"
      exponent: 1.0
      min_reference_height: 0.1  # Minimum reference wave height (m)
      
    # Combination method for scaled loads
    combination:
      method: "linear_superposition"
      formula: "Effective_tension = scaled_wind_tension + scaled_wave_tension"
      
  # Scaling limits and validation
  validation:
    max_wind_scaling_factor: 10.0
    min_wind_scaling_factor: 0.1
    max_wave_scaling_factor: 10.0
    min_wave_scaling_factor: 0.1
    warn_if_no_exact_match: true
    
# ============================================================================
# PROCESSING PARAMETERS
# ============================================================================
processing:
  # Time series processing
  time_series:
    duration_seconds: 100       # Duration of each time series sample
    time_step_seconds: 0.1      # Time step in tension time series
    sample_points: 1000         # Number of points in each sample
    
  # Fatigue analysis parameters
  fatigue_analysis:
    design_life_years: 20       # Design life for fatigue assessment
    seconds_per_year: 31557600  # 365.25 * 24 * 3600
    
  # Rainflow counting settings
  rainflow:
    method: "ASTM_E1049"        # Standard rainflow counting method
    min_range_kN: 0.01          # Minimum cycle range to consider
    normalize_yearly: true       # Normalize to yearly cycles
    
  # S-N curve parameters
  sn_curve:
    curve_type: "DNV-C"         # DNV C-curve for steel in seawater
    description: "Steel in seawater with cathodic protection"
    parameters:
      a: 6.0e11                 # Fatigue strength coefficient
      m: 3.0                    # Fatigue strength exponent
    stress_units: "MPa"
    
  # Tension to stress conversion
  tension_to_stress:
    method: "linear_factor"
    conversion_factor: 0.25     # MPa/kN conversion factor
    includes_scf: true          # Stress concentration factor included
    
# ============================================================================
# OUTPUT CONFIGURATION
# ============================================================================
output:
  # Output folder structure
  base_folder: "specs/modules/fatigue-analysis/reference-seastate-scaling-fatigue/output"
  
  # Output file naming pattern
  file_naming:
    pattern: "{config}_FC{fc_number:03d}_Strut{strut_number}_{type}.csv"
    types:
      scaled_tension: "scaled_tension"
      rainflow_counts: "rainflow"
      stress_ranges: "stress"
      damage_calc: "damage"
      combined: "combined"
      
  # Output file format
  file_format: "csv"
  csv_settings:
    delimiter: ","
    include_header: true
    decimal_places: 6
    
  # Intermediate results
  save_intermediate: true
  intermediate_outputs:
    - "scaled_tensions"
    - "rainflow_results"
    - "stress_conversions"
    - "damage_calculations"
    
  # Summary reports
  generate_summary: true
  summary_outputs:
    - "fatigue_life_summary.csv"
    - "damage_by_seastate.csv"
    - "scaling_factors_applied.csv"
    
  # Visualization outputs
  generate_plots: true
  plot_formats: ["png", "pdf"]
  plots:
    - "damage_histogram"
    - "sn_curve"
    - "scaling_factors"
    
# ============================================================================
# EXECUTION SETTINGS
# ============================================================================
execution:
  # Processing options
  parallel_processing: true
  num_workers: 4
  batch_size: 10
  
  # Error handling
  error_handling:
    continue_on_error: false
    save_error_log: true
    error_log_file: "error_log.txt"
    
  # Logging
  logging:
    level: "INFO"  # DEBUG, INFO, WARNING, ERROR
    log_file: "load_scaling.log"
    console_output: true
    
  # Progress tracking
  show_progress: true
  progress_update_interval: 10  # Update every N iterations
  
# ============================================================================
# VALIDATION AND QC
# ============================================================================
validation:
  # Pre-processing validation
  pre_processing:
    check_file_existence: true
    validate_column_names: true
    check_data_ranges: true
    verify_occurrence_sum: true  # Should sum to 100%
    
  # Post-processing validation
  post_processing:
    min_fatigue_life_years: 20
    max_damage_per_year: 0.05
    check_output_completeness: true
    
  # Data quality checks
  quality_checks:
    max_missing_data_percent: 5.0
    min_data_points: 900
    check_monotonicity: false
    
# ============================================================================
# METADATA
# ============================================================================
metadata:
  created_date: "2025-01-23"
  created_by: "Load Scaling Specification Tool"
  last_modified: "2025-01-23"
  config_version: "1.0.0"
  notes: |
    This configuration file defines all parameters for the load scaling
    fatigue analysis program. It specifies:
    - Input data sources and formats
    - Load scaling methodology
    - Processing parameters
    - Output specifications
    
    The program will:
    1. Read reference seastate data and fatigue seastate definitions
    2. For each fatigue seastate, select appropriate reference conditions
    3. Apply wind and wave scaling factors
    4. Generate scaled tension time series
    5. Perform fatigue damage calculations
    6. Output results in specified format