# Input Parameters for Parametric Analysis
# Source: M01 Pipeline walking.yml
# Generated: 2026-01-18 22:19:27

wind_speed: 0
water_density: 1.025
stage_durations:
- 3200
- 3200
hs: 0
tp: 8
wave_direction: 180

