# Input Parameters for Parametric Analysis
# Source: A01 Lazy wave riser.yml
# Generated: 2026-01-18 21:50:04

water_depth: 100
current_speed: 0.7
wind_speed: 0
water_density: 1.025
stage_durations:
- 7
- 35
hs: 6
tp: 7
wave_direction: 90

