# Batch Meshing Workflow
# Processes multiple geometry files in parallel

name: batch_meshing
description: Process multiple geometry files with consistent meshing parameters
version: 1.0.0

# Global configuration
global_config:
  max_workers: 4
  element_size: 1.0
  algorithm: frontal-delaunay
  output_format: msh
  save_intermediate: true
  error_handling: continue  # continue, stop, or retry

# Input configuration
input:
  directory: ./geometries
  patterns:
    - "*.step"
    - "*.stp"
    - "*.iges"
    - "*.igs"
    - "*.stl"
  recursive: true
  exclude:
    - "*_backup*"
    - "*_old*"

# Mesh generation stages
stages:
  - name: geometry_import
    description: Import and heal geometries
    operations:
      - type: import
        heal_geometry: true
        tolerance: 1e-6
      - type: validate
        check_manifold: true
        check_self_intersections: true
    
  - name: mesh_generation
    description: Generate meshes with specified parameters
    operations:
      - type: generate_mesh
        dimension: auto  # auto, 1d, 2d, or 3d
        element_types:
          2d: triangle
          3d: tetrahedron
        mesh_algorithm:
          2d: frontal-delaunay
          3d: frontal-delaunay
        element_size:
          min: 0.1
          max: 10.0
          default: 1.0
        
  - name: quality_check
    description: Assess mesh quality
    operations:
      - type: quality_assessment
        metrics:
          - jacobian
          - aspect_ratio
          - skewness
          - volume_ratio
        thresholds:
          min_quality_score: 70
          max_aspect_ratio: 10.0
          max_skewness: 0.5
        
  - name: optimization
    description: Optimize meshes that don't meet quality criteria
    operations:
      - type: conditional
        condition: quality_score < 80
        actions:
          - type: optimize
            algorithm: netgen
            max_iterations: 5
            target_quality: 85
            
  - name: export
    description: Export meshes in required formats
    operations:
      - type: export
        formats:
          - msh
          - vtk
        include_quality_report: true

# Output configuration
output:
  directory: ./meshes
  structure: preserve  # preserve, flat, or custom
  naming:
    pattern: "{basename}_mesh.{extension}"
    include_timestamp: false
  reports:
    generate: true
    format: html
    include_charts: true

# Error handling
error_handling:
  max_retries: 3
  retry_delay: 5  # seconds
  failed_jobs_file: failed_jobs.json
  continue_on_error: true
  
# Notifications (optional)
notifications:
  on_start: true
  on_complete: true
  on_error: true
  methods:
    - type: console
      verbose: true
    - type: log
      file: batch_meshing.log
      level: INFO

# Resource limits
resources:
  max_memory_per_job: 2048  # MB
  timeout_per_job: 300  # seconds
  cpu_affinity: null  # null or list of CPU indices

# Post-processing hooks (optional)
post_processing:
  - name: aggregate_reports
    type: script
    command: python aggregate_quality_reports.py
  - name: cleanup
    type: delete_intermediates
    keep_failed: true