# Input Parameters for Parametric Analysis
# Source: calm_floating_hose.yml
# Generated: 2026-01-18 21:53:21

current_speed: 1
wind_speed: 14.5
water_density: 1.025
stage_durations:
- 11
- 65
hs: 5.1
tp: 6.5
wave_direction: 270

