"""Abstract base class for OrcaFlex section builders."""

from abc import ABC, abstractmethod
from typing import Dict, Any, TYPE_CHECKING

if TYPE_CHECKING:
    from ..schema import ProjectInputSpec


class BaseBuilder(ABC):
    """Abstract base class for OrcaFlex section builders.

    Each builder is responsible for generating one section of the modular model.
    Builders receive the validated spec and a context dict containing entities
    generated by previous builders for cross-references.
    """

    def __init__(self, spec: 'ProjectInputSpec', context: Dict[str, Any]):
        """Initialize builder with spec and context.

        Args:
            spec: Validated project input specification
            context: Shared context with entities from previous builders
        """
        self.spec = spec
        self.context = context
        self._generated_entities: Dict[str, Any] = {}

    @abstractmethod
    def build(self) -> Dict[str, Any]:
        """Build and return the section data for YAML output.

        Returns:
            Dictionary representing OrcaFlex YAML section
        """
        pass

    def get_generated_entities(self) -> Dict[str, Any]:
        """Return entities generated by this builder for cross-references.

        Returns:
            Dictionary with entity names/references for other builders
        """
        return self._generated_entities

    def _register_entity(self, key: str, value: Any) -> None:
        """Register an entity for cross-builder sharing.

        Args:
            key: Entity key (e.g., 'line_types', 'buoy_names')
            value: Entity value (e.g., list of names)
        """
        self._generated_entities[key] = value
