"""Abstract base class for OrcaFlex section builders."""

from abc import ABC, abstractmethod
from typing import Any, Dict, TYPE_CHECKING

if TYPE_CHECKING:
    from ..schema import ProjectInputSpec
    from .context import BuilderContext


class BaseBuilder(ABC):
    """Abstract base class for OrcaFlex section builders.

    Each builder is responsible for generating one section of the modular model.
    Builders receive the validated spec and a typed BuilderContext for
    cross-builder entity sharing.
    """

    # Set by @BuilderRegistry.register decorator
    _output_file: str = ""
    _order: int = 0

    def __init__(self, spec: 'ProjectInputSpec', context: 'BuilderContext'):
        """Initialize builder with spec and context.

        Args:
            spec: Validated project input specification
            context: Typed BuilderContext for cross-builder entity sharing
        """
        self.spec = spec
        self.context = context
        self._generated_entities: Dict[str, Any] = {}

    @abstractmethod
    def build(self) -> Dict[str, Any]:
        """Build and return the section data for YAML output.

        Returns:
            Dictionary representing OrcaFlex YAML section
        """
        pass

    def should_generate(self) -> bool:
        """Check if this builder should generate output.

        Override in subclasses to conditionally skip generation
        when no relevant data exists in the spec.

        Returns:
            True if this builder should generate output (default).
        """
        return True

    def get_generated_entities(self) -> Dict[str, Any]:
        """Return entities generated by this builder for cross-references.

        Returns:
            Dictionary with entity names/references for other builders
        """
        return self._generated_entities

    def _register_entity(self, key: str, value: Any) -> None:
        """Register an entity for cross-builder sharing.

        Updates both the internal dict and the typed context.

        Args:
            key: Entity key (e.g., 'line_types', 'buoy_names')
            value: Entity value (e.g., list of names)
        """
        self._generated_entities[key] = value
        if hasattr(self.context, key):
            setattr(self.context, key, value)
