import OrcFxAPI
model = OrcFxAPI.Model()
environment = model.environment
environment.WaterDepth = 1000
vessel = model.CreateObject(OrcFxAPI.otVessel)
line = model.CreateObject(OrcFxAPI.otLine)
line.EndAConnection = vessel.Name
line.EndBConnection = 'Anchored'
line.EndAX, line.EndAY, line.EndAZ = 40.0, 30.0, 5.0
line.EndAAzimuth, line.EndADeclination, line.EndAGamma = 0.0, 0.0, 0.0
line.EndBX, line.EndBY, line.EndBZ = 70.0, 0.0, -25.0
line.EndBAzimuth, line.EndBDeclination, line.EndBGamma = 0.0, 0.0, 0.0  
line.Name = 'MLine1'
line = model.CreateObject(OrcFxAPI.otLine)
line.EndAConnection = vessel.Name
line.EndBConnection = 'Anchored'
line.EndAX, line.EndAY, line.EndAZ = 38.0, 30.0, 5.0
line.EndAAzimuth, line.EndADeclination, line.EndAGamma = 0.0, 0.0, 0.0
line.EndBX, line.EndBY, line.EndBZ = 70.0, 0.0, -25.0
line.EndBAzimuth, line.EndBDeclination, line.EndBGamma = 0.0, 0.0, 0.0  
line.Name = 'MLine2'
line = model.CreateObject(OrcFxAPI.otLine)
line.EndAConnection = vessel.Name
line.EndBConnection = 'Anchored'
line.EndAX, line.EndAY, line.EndAZ = -38.0, 30.0, 5.0
line.EndAAzimuth, line.EndADeclination, line.EndAGamma = 0.0, 0.0, 0.0
line.EndBX, line.EndBY, line.EndBZ = 70.0, 0.0, -25.0
line.EndBAzimuth, line.EndBDeclination, line.EndBGamma = 0.0, 0.0, 0.0  
line.Name = 'MLine3'
line = model.CreateObject(OrcFxAPI.otLine)
line.EndAConnection = vessel.Name
line.EndBConnection = 'Anchored'
line.EndAX, line.EndAY, line.EndAZ = -40.0, 30.0, 5.0
line.EndAAzimuth, line.EndADeclination, line.EndAGamma = 0.0, 0.0, 0.0
line.EndBX, line.EndBY, line.EndBZ = 70.0, 0.0, -25.0
line.EndBAzimuth, line.EndBDeclination, line.EndBGamma = 0.0, 0.0, 0.0  
line.Name = 'MLine4'
line = model.CreateObject(OrcFxAPI.otLine)
line.EndAConnection = vessel.Name
line.EndBConnection = 'Anchored'
line.EndAX, line.EndAY, line.EndAZ = -40.0, -30.0, 5.0
line.EndAAzimuth, line.EndADeclination, line.EndAGamma = 0.0, 0.0, 0.0
line.EndBX, line.EndBY, line.EndBZ = 70.0, 0.0, -25.0
line.EndBAzimuth, line.EndBDeclination, line.EndBGamma = 0.0, 0.0, 0.0  
line.Name = 'MLine5'
line = model.CreateObject(OrcFxAPI.otLine)
line.EndAConnection = vessel.Name
line.EndBConnection = 'Anchored'
line.EndAX, line.EndAY, line.EndAZ = -38.0, -30.0, 5.0
line.EndAAzimuth, line.EndADeclination, line.EndAGamma = 0.0, 0.0, 0.0
line.EndBX, line.EndBY, line.EndBZ = 70.0, 0.0, -25.0
line.EndBAzimuth, line.EndBDeclination, line.EndBGamma = 0.0, 0.0, 0.0  
line.Name = 'MLine6'
line = model.CreateObject(OrcFxAPI.otLine)
line.EndAConnection = vessel.Name
line.EndBConnection = 'Anchored'
line.EndAX, line.EndAY, line.EndAZ = 38.0, -30.0, 5.0
line.EndAAzimuth, line.EndADeclination, line.EndAGamma = 0.0, 0.0, 0.0
line.EndBX, line.EndBY, line.EndBZ = 70.0, 0.0, -25.0
line.EndBAzimuth, line.EndBDeclination, line.EndBGamma = 0.0, 0.0, 0.0  
line.Name = 'MLine7'
line = model.CreateObject(OrcFxAPI.otLine)
line.EndAConnection = vessel.Name
line.EndBConnection = 'Anchored'
line.EndAX, line.EndAY, line.EndAZ = 40.0, -30.0, 5.0
line.EndAAzimuth, line.EndADeclination, line.EndAGamma = 0.0, 0.0, 0.0
line.EndBX, line.EndBY, line.EndBZ = 70.0, 0.0, -25.0
line.EndBAzimuth, line.EndBDeclination, line.EndBGamma = 0.0, 0.0, 0.0  
line.Name = 'MLine8'
model.SaveData('model11.dat')
