@startuml global_analysis_methodology

scale 2
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Tomato


title Global Motion Analysis | Model Development \n Weighted Average Method



package Geometries {
component "**FST Geometry** \nLight, Full, 90% etc." as FST_Gometries
component "**LNG**" as LNG
component "**Other Structures** \nStruts, Dampener, Jacket etc" as Other_Structures

}

note right
    Notes:
        1a/ FST1 and FST2 geometries
        1b/ 2 LNG sizes
        1c/ Other structures, Fixed objects etc.
        1d/ Marine growth weight?
end note

package "Model Data" as md {
agent "**FSTs/LNG** \n 1st order Load RAOs, 2nd wave drift load, \n Wind coeffs, current coeffs" as FST_model_data
agent "**Strut** \n Using a rigid link" as Strut
agent "**Jacket** \n As Fixed Structure" as Jacket
agent "**Dampener** \n Using non-linear Curve" as Dampener
}

note right
    Notes:
        1a/ Design data spreadsheet to drive key dimensions, weights and parameters
        1b/ Key coordinates
        1c/ Key inputs for both all analysis etc.
end note

FST_Gometries --> FST_model_data
LNG --> FST_model_data
Other_Structures --> Strut 
Other_Structures --> Dampener 
Other_Structures --> Jacket 


footer
%date("yyyy.MM.dd' at 'HH:mm")
%filename()
end footer

@enduml