"""
ABOUTME: Extract RAO data and hydrodynamic coefficients from OrcaWave .xlsx
sidecar files and populate the RAODatabase.

Supports two xlsx formats:
  1. "Pipeline" format — generated by process-queue.py on licensed-win-1.
     Sheets: Summary, RAOs, AddedMass, Damping, Discretization.
  2. "Native" format — exported by OrcaWave GUI on Windows.
     Sheets: Displacement RAOs, Added mass, Damping, etc.

This module does NOT require OrcFxAPI — it reads only xlsx files,
making it usable on dev-primary without a solver license.

Traceability: #1765, #1597
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import numpy as np
import openpyxl

from digitalmodel.hydrodynamics.models import RAOData
from digitalmodel.hydrodynamics.hull_library.rao_database import (
    RAODatabase,
    RAODatabaseEntry,
)

# DOF ordering used throughout — matches OrcaWave convention
DOF_NAMES = ["Surge", "Sway", "Heave", "Roll", "Pitch", "Yaw"]


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------


@dataclass
class HydroCoefficients:
    """Added mass and damping coefficient matrices.

    Attributes
    ----------
    frequencies : np.ndarray
        Frequencies in rad/s, shape (n_freq,), ascending.
    added_mass : np.ndarray
        Added mass matrices, shape (n_freq, 6, 6).
    damping : np.ndarray
        Damping matrices, shape (n_freq, 6, 6).
    """

    frequencies: np.ndarray
    added_mass: np.ndarray
    damping: np.ndarray


# ---------------------------------------------------------------------------
# Format detector
# ---------------------------------------------------------------------------


class XlsxFormatDetector:
    """Detect whether an xlsx file uses pipeline or native OrcaWave format."""

    @staticmethod
    def detect(xlsx_path: Path) -> str:
        """Return 'pipeline' or 'native'.

        Pipeline format has sheets: Summary, RAOs, AddedMass, Damping, Discretization.
        Native format has sheets like: Displacement RAOs, Added mass, Damping, etc.

        Raises
        ------
        FileNotFoundError
            If the file does not exist.
        ValueError
            If the format cannot be determined.
        """
        xlsx_path = Path(xlsx_path)
        if not xlsx_path.exists():
            raise FileNotFoundError(f"File not found: {xlsx_path}")

        wb = openpyxl.load_workbook(xlsx_path, read_only=True, data_only=True)
        sheet_names = set(wb.sheetnames)
        wb.close()

        # Pipeline format markers
        if "RAOs" in sheet_names and "AddedMass" in sheet_names:
            return "pipeline"

        # Native format markers
        if "Displacement RAOs" in sheet_names or "Added mass" in sheet_names:
            return "native"

        raise ValueError(
            f"Cannot determine xlsx format. Sheets: {sorted(sheet_names)}"
        )


# ---------------------------------------------------------------------------
# Pipeline format reader
# ---------------------------------------------------------------------------


class PipelineXlsxReader:
    """Read RAO data from pipeline-format xlsx files.

    Pipeline format (generated by process-queue.py):
      - Summary sheet: job metadata
      - RAOs sheet: columns = [Frequency (rad/s), Period (s),
        {DOF}_Mag_H{heading}, {DOF}_Phase_H{heading}, ...]
      - AddedMass sheet: columns = [Frequency (rad/s), Period (s),
        {DOFi}_{DOFj}, ...]
      - Damping sheet: same layout as AddedMass
      - Discretization sheet: frequency/period table
    """

    def __init__(self, xlsx_path: Path) -> None:
        self._path = Path(xlsx_path)
        self._wb = openpyxl.load_workbook(self._path, data_only=True)

    def read_rao_data(self, vessel_name: str | None = None) -> RAOData:
        """Extract 6-DOF RAO amplitude + phase arrays.

        Returns
        -------
        RAOData
            With frequencies in rad/s (ascending), directions in degrees,
            amplitudes shape (n_freq, n_dir, 6), phases shape (n_freq, n_dir, 6).
        """
        ws = self._wb["RAOs"]
        headers = [cell.value for cell in ws[1]]
        data_rows = list(ws.iter_rows(min_row=2, values_only=True))

        # Extract frequencies (already in rad/s, ascending from row order)
        frequencies = np.array([row[0] for row in data_rows], dtype=np.float64)

        # Parse headings from column names: {DOF}_Mag_H{heading}
        heading_set: list[float] = []
        heading_pattern = re.compile(r"_Mag_H([\d.]+)$")
        seen_headings: set[float] = set()
        for h in headers:
            if h is None:
                continue
            m = heading_pattern.search(h)
            if m:
                hdg = float(m.group(1))
                if hdg not in seen_headings:
                    seen_headings.add(hdg)
                    heading_set.append(hdg)

        directions = np.array(heading_set, dtype=np.float64)
        n_freq = len(frequencies)
        n_dir = len(directions)

        # Build column index map: (dof_idx, heading_idx) → (mag_col, phase_col)
        col_map: dict[tuple[int, int], tuple[int, int]] = {}
        for dof_idx, dof_name in enumerate(DOF_NAMES):
            for dir_idx, hdg in enumerate(directions):
                mag_col_name = f"{dof_name}_Mag_H{hdg}"
                phase_col_name = f"{dof_name}_Phase_H{hdg}"
                mag_col = headers.index(mag_col_name)
                phase_col = headers.index(phase_col_name)
                col_map[(dof_idx, dir_idx)] = (mag_col, phase_col)

        # Fill arrays
        amplitudes = np.zeros((n_freq, n_dir, 6), dtype=np.float64)
        phases = np.zeros((n_freq, n_dir, 6), dtype=np.float64)

        for freq_idx, row in enumerate(data_rows):
            for (dof_idx, dir_idx), (mag_col, phase_col) in col_map.items():
                amplitudes[freq_idx, dir_idx, dof_idx] = abs(float(row[mag_col] or 0.0))
                phases[freq_idx, dir_idx, dof_idx] = float(row[phase_col] or 0.0)

        # Ensure frequencies are ascending
        if len(frequencies) > 1 and frequencies[0] > frequencies[-1]:
            sort_idx = np.argsort(frequencies)
            frequencies = frequencies[sort_idx]
            amplitudes = amplitudes[sort_idx, :, :]
            phases = phases[sort_idx, :, :]

        name = vessel_name or self._path.stem
        return RAOData(
            frequencies=frequencies,
            directions=directions,
            amplitudes=amplitudes,
            phases=phases,
            vessel_name=name,
        )

    def read_hydro_coefficients(self) -> HydroCoefficients:
        """Extract 6x6 added mass and damping matrices per frequency.

        Returns
        -------
        HydroCoefficients
            With frequencies ascending, matrices shape (n_freq, 6, 6).
        """
        am_data = self._read_matrix_sheet("AddedMass")
        damp_data = self._read_matrix_sheet("Damping")
        return HydroCoefficients(
            frequencies=am_data[0],
            added_mass=am_data[1],
            damping=damp_data[1],
        )

    def _read_matrix_sheet(
        self, sheet_name: str
    ) -> tuple[np.ndarray, np.ndarray]:
        """Read a 6x6 matrix sheet (AddedMass or Damping).

        Returns (frequencies, matrices) where matrices has shape (n_freq, 6, 6).
        """
        ws = self._wb[sheet_name]
        headers = [cell.value for cell in ws[1]]
        data_rows = list(ws.iter_rows(min_row=2, values_only=True))

        frequencies = np.array([row[0] for row in data_rows], dtype=np.float64)
        n_freq = len(frequencies)

        # Build column index map: (i, j) → col_idx
        col_map: dict[tuple[int, int], int] = {}
        for i, dof_i in enumerate(DOF_NAMES):
            for j, dof_j in enumerate(DOF_NAMES):
                col_name = f"{dof_i}_{dof_j}"
                col_map[(i, j)] = headers.index(col_name)

        matrices = np.zeros((n_freq, 6, 6), dtype=np.float64)
        for freq_idx, row in enumerate(data_rows):
            for (i, j), col_idx in col_map.items():
                matrices[freq_idx, i, j] = float(row[col_idx] or 0.0)

        # Ensure ascending
        if n_freq > 1 and frequencies[0] > frequencies[-1]:
            sort_idx = np.argsort(frequencies)
            frequencies = frequencies[sort_idx]
            matrices = matrices[sort_idx, :, :]

        return frequencies, matrices


# ---------------------------------------------------------------------------
# Native OrcaWave format reader
# ---------------------------------------------------------------------------


class NativeXlsxReader:
    """Read RAO data from native OrcaWave xlsx export files.

    Native format has sheets with 2-3 header rows, then structured tables.
    Key sheets:
      - 'Displacement RAOs': per-heading blocks of (freq, surge_amp, surge_phase, ...)
      - 'Added mass': per-frequency 6x6 matrix blocks
      - 'Damping': per-frequency 6x6 matrix blocks
    """

    def __init__(self, xlsx_path: Path) -> None:
        self._path = Path(xlsx_path)
        self._wb = openpyxl.load_workbook(self._path, data_only=True)

    def read_rao_data(self, vessel_name: str | None = None) -> RAOData:
        """Extract displacement RAOs from native OrcaWave format.

        The 'Displacement RAOs' sheet layout:
          - Rows 1-9: headers (sheet title, version, DOF labels, unit labels)
          - Data rows: [heading_deg, frequency_rad_s, surge_amp, surge_phase,
            sway_amp, sway_phase, heave_amp, heave_phase, roll_amp, roll_phase,
            pitch_amp, pitch_phase, yaw_amp, yaw_phase]
          - The heading value in column 0 groups data into heading blocks.
        """
        ws = self._wb["Displacement RAOs"]
        all_rows = list(ws.iter_rows(values_only=True))

        # Parse data rows — skip header/label rows
        # Data rows have numeric values in columns 0 and 1
        data_by_heading: dict[float, list[tuple[float, list[float]]]] = {}

        for row in all_rows:
            if row[0] is None or row[1] is None:
                continue
            try:
                heading = float(row[0])
                freq_rad_s = float(row[1])
            except (ValueError, TypeError):
                continue

            # Extract 12 data values (6 DOFs × 2: amp + phase)
            vals = []
            for v in row[2:14]:
                try:
                    vals.append(float(v) if v is not None else 0.0)
                except (ValueError, TypeError):
                    vals.append(0.0)

            if len(vals) >= 12:
                if heading not in data_by_heading:
                    data_by_heading[heading] = []
                data_by_heading[heading].append((freq_rad_s, vals))

        if not data_by_heading:
            raise ValueError(
                f"No displacement RAO data found in {self._path}"
            )

        # Sort headings to get consistent ordering
        sorted_headings = sorted(data_by_heading.keys())
        directions = np.array(sorted_headings, dtype=np.float64)

        # Get frequencies from the first heading block
        first_block = data_by_heading[sorted_headings[0]]
        frequencies = np.array([f for f, _ in first_block], dtype=np.float64)
        n_freq = len(frequencies)
        n_dir = len(directions)

        # Build arrays
        amplitudes = np.zeros((n_freq, n_dir, 6), dtype=np.float64)
        phases = np.zeros((n_freq, n_dir, 6), dtype=np.float64)

        for dir_idx, heading in enumerate(sorted_headings):
            block = data_by_heading[heading]
            for freq_idx, (_, vals) in enumerate(block):
                for dof_idx in range(6):
                    amp_col = dof_idx * 2       # 0, 2, 4, 6, 8, 10
                    phase_col = dof_idx * 2 + 1  # 1, 3, 5, 7, 9, 11
                    amplitudes[freq_idx, dir_idx, dof_idx] = abs(vals[amp_col])
                    phases[freq_idx, dir_idx, dof_idx] = vals[phase_col]

        # Sort by frequency ascending
        sort_idx = np.argsort(frequencies)
        frequencies = frequencies[sort_idx]
        amplitudes = amplitudes[sort_idx, :, :]
        phases = phases[sort_idx, :, :]

        name = vessel_name or self._path.stem

        return RAOData(
            frequencies=frequencies,
            directions=directions,
            amplitudes=amplitudes,
            phases=phases,
            vessel_name=name,
        )

    def read_hydro_coefficients(self) -> HydroCoefficients:
        """Extract added mass and damping from native format.

        Native format has these sheets with per-frequency 6x6 blocks.
        """
        am = self._read_native_matrix_sheet("Added mass")
        damp = self._read_native_matrix_sheet("Damping")
        return HydroCoefficients(
            frequencies=am[0],
            added_mass=am[1],
            damping=damp[1],
        )

    def _read_native_matrix_sheet(
        self, sheet_name: str
    ) -> tuple[np.ndarray, np.ndarray]:
        """Parse a native-format 6x6 matrix sheet.

        Each frequency block is structured as:
          [blank row]
          [None, '{sheet_name} for frequency X.Xrad/s', ...]
          [None, 'DOF', ...]
          [None, body_name, ...]
          [None, 'Surge', 'Sway', 'Heave', 'Roll', 'Pitch', 'Yaw']
          [None, '1', '2', '3', '4', '5', '6']
          ['1', val, val, val, val, val, val]
          ['2', val, val, val, val, val, val]
          ... 6 data rows
        """
        ws = self._wb[sheet_name]
        all_rows = list(ws.iter_rows(values_only=True))

        freq_pattern = re.compile(
            r"frequency\s+([\d.eE+-]+)\s*rad",
            re.IGNORECASE,
        )

        frequencies: list[float] = []
        matrices: list[np.ndarray] = []

        i = 0
        while i < len(all_rows):
            row = all_rows[i]
            # Look for frequency marker in column 1
            if row[1] is not None and isinstance(row[1], str):
                m = freq_pattern.search(row[1])
                if m:
                    freq_rad_s = float(m.group(1))

                    # Skip to the data rows (after DOF label, body name,
                    # Surge/Sway header, and 1/2/3 numbering rows)
                    i += 1
                    # Find the numbered column header row (1, 2, 3, 4, 5, 6)
                    while i < len(all_rows):
                        check = all_rows[i]
                        if (check[1] is not None
                                and str(check[1]).strip() == "1"
                                and check[2] is not None
                                and str(check[2]).strip() == "2"):
                            i += 1  # skip to first data row
                            break
                        i += 1

                    # Read 6 data rows — each starts with row number in col 0
                    matrix = np.zeros((6, 6), dtype=np.float64)
                    for row_idx in range(6):
                        if i + row_idx >= len(all_rows):
                            break
                        data_row = all_rows[i + row_idx]
                        for col_idx in range(6):
                            val = data_row[col_idx + 1] if col_idx + 1 < len(data_row) else 0.0
                            try:
                                matrix[row_idx, col_idx] = float(val) if val is not None else 0.0
                            except (ValueError, TypeError):
                                matrix[row_idx, col_idx] = 0.0

                    frequencies.append(freq_rad_s)
                    matrices.append(matrix)
                    i += 6
                    continue
            i += 1

        if not frequencies:
            raise ValueError(
                f"No matrix data found in sheet '{sheet_name}' of {self._path}"
            )

        freq_arr = np.array(frequencies, dtype=np.float64)
        mat_arr = np.stack(matrices)

        # Sort ascending
        sort_idx = np.argsort(freq_arr)
        freq_arr = freq_arr[sort_idx]
        mat_arr = mat_arr[sort_idx, :, :]

        return freq_arr, mat_arr


# ---------------------------------------------------------------------------
# Convenience functions
# ---------------------------------------------------------------------------


def xlsx_to_rao_data(
    xlsx_path: Path, vessel_name: str | None = None
) -> RAOData:
    """Auto-detect format and extract RAO data from an OrcaWave xlsx file.

    Parameters
    ----------
    xlsx_path : Path
        Path to .xlsx file (pipeline or native format).
    vessel_name : str, optional
        Override the vessel name. Defaults to filename stem.

    Returns
    -------
    RAOData
        With frequencies in rad/s, directions in degrees,
        amplitudes and phases shape (n_freq, n_dir, 6).
    """
    xlsx_path = Path(xlsx_path)
    fmt = XlsxFormatDetector.detect(xlsx_path)
    if fmt == "pipeline":
        reader = PipelineXlsxReader(xlsx_path)
    else:
        reader = NativeXlsxReader(xlsx_path)
    return reader.read_rao_data(vessel_name=vessel_name)


def xlsx_to_hydro_coefficients(xlsx_path: Path) -> HydroCoefficients:
    """Auto-detect format and extract hydrodynamic coefficients.

    Parameters
    ----------
    xlsx_path : Path
        Path to .xlsx file (pipeline or native format).

    Returns
    -------
    HydroCoefficients
        Added mass and damping matrices, shape (n_freq, 6, 6).
    """
    xlsx_path = Path(xlsx_path)
    fmt = XlsxFormatDetector.detect(xlsx_path)
    if fmt == "pipeline":
        reader = PipelineXlsxReader(xlsx_path)
    else:
        reader = NativeXlsxReader(xlsx_path)
    return reader.read_hydro_coefficients()


def populate_database_from_xlsx(
    db: RAODatabase,
    xlsx_path: Path,
    variation_id: str,
    hull_params: dict[str, float],
    metadata: dict[str, Any] | None = None,
    vessel_name: str | None = None,
) -> RAODatabaseEntry:
    """Extract RAO data from xlsx and store in the RAODatabase.

    Parameters
    ----------
    db : RAODatabase
        Target database.
    xlsx_path : Path
        Path to .xlsx file.
    variation_id : str
        Unique ID for this hull variation.
    hull_params : dict
        Hull parametric scaling values.
    metadata : dict, optional
        Extra metadata (solver version, case name, etc.).
    vessel_name : str, optional
        Override vessel name.

    Returns
    -------
    RAODatabaseEntry
        The entry that was stored.
    """
    xlsx_path = Path(xlsx_path)
    rao_data = xlsx_to_rao_data(xlsx_path, vessel_name=vessel_name)

    entry_metadata = metadata.copy() if metadata else {}
    entry_metadata.setdefault("source_file", str(xlsx_path))

    entry = RAODatabaseEntry(
        variation_id=variation_id,
        hull_params=hull_params,
        rao_data=rao_data,
        metadata=entry_metadata,
    )
    db.store(entry)
    return entry


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

__all__ = [
    "HydroCoefficients",
    "NativeXlsxReader",
    "PipelineXlsxReader",
    "XlsxFormatDetector",
    "populate_database_from_xlsx",
    "xlsx_to_hydro_coefficients",
    "xlsx_to_rao_data",
]
