# Input Parameters for Parametric Analysis
# Source: F01 Lowered cone.yml
# Generated: 2026-01-18 22:18:14

water_depth: 100
current_speed: 0
wind_speed: 0
water_density: 1.025
stage_durations:
- 10
- 40
hs: 0
tp: 10
wave_direction: 180

