# Mooring Systems Data Procurement Configuration Example
# Version: 1.0.0
# Reference: @specs/modules/data-procurement/mooring-systems/spec.md

version: "1.0"

# Reference common components framework
# extends: "@specs/modules/data-procurement/common-components/spec.md"  # Documentation reference only

# Data source category
data_source:
  category: "mooring_systems"
  description: "Mooring components, configurations, and system data"

# Mooring system configuration
mooring_system:
  # System type
  type: "catenary"  # catenary, taut_leg, spread, calm_buoy, salm

  # Number of mooring lines
  line_count: 6

  # Line arrangement
  arrangement: "radial"  # radial, symmetrical, asymmetrical

  # Anchor spacing (degrees between lines)
  anchor_spacing: 60  # degrees (360/6 for 6-point)

# Mooring line configuration
lines:
  - name: "Line1"
    # Line components (from vessel to anchor)
    components:
      # Fairlead chain segment
      - type: "chain"
        grade: "R4S"          # R3, R3S, R4, R4S, R5, R6
        diameter: 127         # mm
        length: 200           # m
        manufacturer: "Vicinay"

      # Mid-section wire rope
      - type: "wire_rope"
        construction: "6x36 IWRC"
        diameter: 76          # mm
        length: 1000          # m
        grade: "improved_plow_steel"

      # Anchor chain segment
      - type: "chain"
        grade: "R4S"
        diameter: 127         # mm
        length: 100           # m

    # Line properties (auto-calculated from components if not specified)
    properties:
      total_length: 1300     # m
      pretension: 2000       # kN

  # Additional lines (2-6 for typical systems)
  # - name: "Line2"
  #   components: [...]

# Anchor configuration
anchors:
  - line: "Line1"
    type: "stevpris_mk6"    # stevpris, vryhof, bruce, suction_pile, driven_pile

    # Anchor properties
    properties:
      weight: 20000         # kg (dry weight)
      submerged_weight: 17400  # kg

    # Holding capacity (depends on soil)
    holding_capacity:
      sand: 2400            # kN (capacity_factor × submerged_weight)
      clay: 1600            # kN
      design: 1500          # kN (conservative, with safety factor)

    # Installation
    installation:
      method: "drag_embedment"
      penetration_depth: 6  # m
      line_angle: 30        # degrees at mudline

# Mooring connectors
connectors:
  # Fairlead shackles
  - location: "fairlead"
    type: "bow_shackle"
    size: "120mm"           # pin diameter
    wll: 850                # kN (working load limit)
    mbl: 1700               # kN (minimum breaking load)

  # Chain-to-wire connection
  - location: "chain_wire_junction"
    type: "h_link"
    size: "127mm"
    wll: 5000               # kN

  # Anchor shackle
  - location: "anchor"
    type: "anchor_shackle"
    size: "120mm"
    wll: 850                # kN

# Component database sources
data_sources:
  # Chains
  chains:
    source: "generic_database"  # generic_database, manufacturer_catalog, repository
    database_path: "@specs/modules/data-procurement/mooring-systems/data/chains/"

  # Wire ropes
  wire_ropes:
    source: "generic_database"
    database_path: "@specs/modules/data-procurement/mooring-systems/data/wire_ropes/"

  # Synthetic ropes
  synthetic_ropes:
    source: "generic_database"
    database_path: "@specs/modules/data-procurement/mooring-systems/data/synthetic_ropes/"

  # Anchors
  anchors:
    source: "generic_database"
    database_path: "@specs/modules/data-procurement/mooring-systems/data/anchors/"

  # Connectors
  connectors:
    source: "generic_database"
    database_path: "@specs/modules/data-procurement/mooring-systems/data/connectors/"

# Design standards and safety factors
standards:
  # Primary design standard
  design_standard: "API_RP_2SK"  # API_RP_2SK, DNV_OS_E301, ISO_19901_7

  # Safety factors
  safety_factors:
    intact_condition: 1.67        # All lines intact
    damaged_condition: 1.25       # One line failed
    transient_condition: 1.15     # Installation, hook-up

  # Load cases
  load_cases:
    operating:
      return_period: 1    # year
      wave_height: 5.0    # m (Hs)
      wind_speed: 25.0    # m/s
    survival:
      return_period: 100  # year
      wave_height: 15.0   # m (Hs)
      wind_speed: 45.0    # m/s

# Component properties auto-calculation
properties:
  # Calculate component properties from dimensions
  auto_calculate: true

  # Calculation methods
  methods:
    # Chain mass: 7.86 × diameter² / 1000 (kg/m)
    chain_mass: "standard_formula"

    # Chain MBL: grade_factor × diameter² (kN)
    chain_mbl: "api_formula"

    # Wire rope mass and MBL from construction
    wire_rope: "api_spec_9a"

    # Synthetic rope from fiber type
    synthetic_rope: "api_rp_2sm"

# Soil parameters (for anchor design)
soil:
  type: "clay"  # sand, clay, mixed, rock

  # Clay properties
  clay:
    undrained_shear_strength: 50  # kPa
    submerged_unit_weight: 8      # kN/m³

  # Sand properties
  sand:
    friction_angle: 35            # degrees
    submerged_unit_weight: 10     # kN/m³

# Output configuration
output:
  format: "orcaflex_yml"  # orcaflex_yml, moses, aqwa, json, csv
  path: "./data/moorings/"
  filename_pattern: "mooring_{system_type}_{line_count}lines.yml"

  # Include in output
  include_component_properties: true
  include_standards_validation: true
  include_anchor_design: true
  include_line_profiles: true

  # OrcaFlex-specific settings
  orcaflex:
    create_line_types: true
    create_environment: false  # Use metocean spec separately
    include_fairlead: true
    include_anchor: true

  # MOSES-specific settings
  moses:
    format: "segment_based"
    include_pretension: true

# Validation settings
validation:
  # Component compatibility checks
  check_compatibility: true

  # Range checks
  check_ranges:
    chain_diameter: [50, 200]      # mm
    wire_diameter: [40, 150]       # mm
    synthetic_diameter: [100, 400] # mm
    anchor_weight: [5000, 100000]  # kg

  # Standards compliance
  check_standards: true

  # Safety factor compliance
  check_safety_factors: true

  # Warn on issues
  warnings:
    mixed_grades: true        # Mixing chain grades in one line
    oversized_connectors: true # Connector much larger than line
    short_chain_segments: true # Chain segments < 20m

# Optimization settings
optimization:
  # Component sizing optimization
  enabled: false

  # Objective
  objective: "minimize_cost"  # minimize_cost, minimize_weight, maximize_capacity

  # Constraints
  constraints:
    max_line_tension: 5000   # kN
    min_safety_factor: 1.67
    max_anchor_weight: 25000 # kg

# Material properties database
materials:
  # Steel properties for chains/wire rope
  steel:
    density: 7850            # kg/m³
    youngs_modulus: 210      # GPa
    yield_strength: 690      # MPa (R4 grade)

  # Synthetic rope properties
  polyester:
    density: 1380            # kg/m³
    specific_gravity: 1.38
    mbl_per_diameter: 0.15   # kN/mm² (approximate)

# Environmental loading (reference to metocean)
environment:
  # Reference metocean configuration
  metocean_config: "@specs/modules/data-procurement/metocean-data/configs/example_config.yml"

  # Or specify key parameters
  design_conditions:
    wave_height: 15.0        # m (Hs)
    wave_period: 12.0        # s (Tp)
    current_speed: 1.5       # m/s
    wind_speed: 45.0         # m/s

# Caching configuration
caching:
  enabled: true
  ttl_days: 365  # Component data rarely changes
  tier: "L3"     # Disk cache
  cache_directory: "./cache/moorings/"

# Analysis settings
analysis:
  # Static analysis
  static:
    include_pretension: true
    include_current: true
    include_offset: true

  # Dynamic analysis
  dynamic:
    time_domain: true
    frequency_domain: false

  # Fatigue analysis
  fatigue:
    enabled: true
    design_life: 25          # years
    t_curve: "API_T_curve"   # T-N curve for fatigue

# Reporting
reporting:
  # Generate design report
  generate_report: true
  report_format: "pdf"       # pdf, html, markdown

  # Include in report
  include:
    - system_summary
    - component_list
    - safety_factor_table
    - anchor_design
    - standards_compliance
    - drawings

# Logging
logging:
  level: "INFO"
  format: "json"
  output:
    - type: "file"
      path: "./logs/mooring_systems.log"
    - type: "console"

# Pre-configured system types (presets)
presets:
  # CALM buoy 6-point catenary
  calm_buoy_catenary:
    type: "catenary"
    line_count: 6
    components:
      - {type: "chain", grade: "R4S", diameter: 127, length: 1200}
    anchors:
      type: "stevpris_mk6"
      weight: 20000

  # Floating wind taut-leg
  floating_wind_taut_leg:
    type: "taut_leg"
    line_count: 3
    components:
      - {type: "chain", grade: "R4", diameter: 150, length: 100}
      - {type: "synthetic_rope", fiber: "polyester", diameter: 220, length: 800}
      - {type: "chain", grade: "R4", diameter: 150, length: 100}
    anchors:
      type: "suction_pile"
      diameter: 5.0  # m

  # Semi-submersible spread mooring
  semi_spread_mooring:
    type: "spread"
    line_count: 12
    components:
      - {type: "chain", grade: "R3S", diameter: 127, length: 500}
      - {type: "wire_rope", construction: "6x36 IWRC", diameter: 76, length: 1500}
      - {type: "chain", grade: "R3S", diameter: 127, length: 300}

# Current preset (comment out to use manual config)
# active_preset: "calm_buoy_catenary"
