# Input Parameters for Parametric Analysis
# Source: C08 Fish farm.yml
# Generated: 2026-01-18 22:18:06

water_depth: 40
current_speed: 0
wind_speed: 0
water_density: 1.025
stage_durations:
- 10
- 20
wave_direction: 180

