@startuml ffs_methodology_local_metal
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Tomato

title FFS Methodology \n Corrosion/Erosion \n Localized Metal Loss
        note right
            Performed when Average Wall Thickness is closer
            to minimum wall (tmin) than nominal wall (tnom)
        end note

(*) --> Review Design Data
        note right
            Pipe data
            Operating Pressure
            Design Code, tmin
                See pyprespipe library
            FCA (Future Corrosion Allowance)
            etc.
        end note

    --> Review Measured Wall Thickness Data
        note right
            Methods used
            Critical thickness profile
            Data resolution
            Data accuracy
            etc.
        end note

    --> Perform Level 1, Part 5
        if "FCA not Acceptable" then
        --> Adjust FCA (or) Perform Level 2, Part 5
        if "FCA not Acceptable" then
            --> Adjust FCA or Perform Level 3, Part 5

    --> Analysis Results
        note right
            Future Corrosion Allowance (FCA)
            Recommendations: 
                Repairs and remediations inline with FCA
                Next inspection
                Future monitoring requirements
        end note

footer
%date("yyyy.MM.dd' at 'HH:mm")
%filename()
end footer

@enduml
