"""
Reporting and I/O helpers for the seed equivalence benchmark.

Handles:
  - YAML inventory export
  - Per-model JSON result persistence
  - Baseline JSON save/load
  - HTML consolidated report generation
"""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path
from typing import List, Optional

from digitalmodel.benchmarks.example_model_benchmark import (
    BenchmarkPassFail,
    BenchmarkSummary,
    ModelCategory,
    ModelInventoryEntry,
    RAO_AMP_TOLERANCE_PCT,
    SEED_COV_THRESHOLD,
    TENSION_TOLERANCE_PCT,
)

# ---------------------------------------------------------------------------
# Output paths (callers may override by reassigning these module-level vars)
# ---------------------------------------------------------------------------
OUTPUT_ROOT = Path(__file__).resolve().parent.parent / "benchmark_output"
SEED_DIR = OUTPUT_ROOT / "seed_equivalence"
INVENTORY_PATH = OUTPUT_ROOT / "model_inventory.yaml"
REPORT_PATH = OUTPUT_ROOT / "seed_equivalence_report.html"
BASELINES_PATH = OUTPUT_ROOT / "seed_equivalence_baselines.json"

# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------
def _flush(*args) -> None:
    print(*args)
    sys.stdout.flush()


# ---------------------------------------------------------------------------
# Inventory YAML export
# ---------------------------------------------------------------------------
def export_inventory_yaml(inventory: List[ModelInventoryEntry]) -> None:
    """Write model inventory to YAML (stdlib-only, no pyyaml dep)."""
    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Model Inventory — generated by scripts/seed_equivalence.py",
        f"# Total models: {len(inventory)}",
        "models:",
    ]
    for entry in inventory:
        lines += [
            f"  - name: {entry.name}",
            f"    category: {entry.category.value}",
            f"    path: {entry.path}",
            f"    description: >-",
            f"      {entry.description}",
            f"    has_time_domain: {str(entry.has_time_domain).lower()}",
            f"    has_frequency_domain: {str(entry.has_frequency_domain).lower()}",
            f"    tags: [{', '.join(entry.tags)}]",
        ]
    INVENTORY_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    _flush(f"Inventory: {INVENTORY_PATH} ({len(inventory)} models)")


# ---------------------------------------------------------------------------
# Per-model JSON result
# ---------------------------------------------------------------------------
def save_model_result(summary: BenchmarkSummary) -> None:
    """Persist one model's benchmark summary as JSON."""
    SEED_DIR.mkdir(parents=True, exist_ok=True)
    out = SEED_DIR / f"{summary.model_name}.json"
    data = {
        "model_name": summary.model_name,
        "category": summary.category.value,
        "statics_pass": summary.statics_pass,
        "time_domain_status": summary.time_domain_status.value,
        "frequency_domain_status": summary.frequency_domain_status.value,
        "seed_equivalence_status": summary.seed_equivalence_status.value,
        "overall_status": summary.overall_status.value,
        "seed_cov": summary.seed_cov,
        "freq_max_diff_pct": summary.freq_max_diff_pct,
        "notes": summary.notes,
    }
    out.write_text(json.dumps(data, indent=2), encoding="utf-8")


# ---------------------------------------------------------------------------
# Baseline JSON
# ---------------------------------------------------------------------------
def save_baselines(summaries: List[BenchmarkSummary]) -> None:
    """Save regression baseline JSON for future comparison."""
    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
    baseline = {
        "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "models": [
            {
                "name": s.model_name,
                "category": s.category.value,
                "overall_status": s.overall_status.value,
                "seed_cov": s.seed_cov,
                "freq_max_diff_pct": s.freq_max_diff_pct,
            }
            for s in summaries
        ],
    }
    BASELINES_PATH.write_text(json.dumps(baseline, indent=2), encoding="utf-8")
    _flush(f"Baselines: {BASELINES_PATH}")


def load_existing_summaries() -> List[BenchmarkSummary]:
    """Load existing per-model JSON results from SEED_DIR."""
    summaries: List[BenchmarkSummary] = []
    if not SEED_DIR.exists():
        return summaries
    for json_path in sorted(SEED_DIR.glob("*.json")):
        try:
            data = json.loads(json_path.read_text(encoding="utf-8"))
            summaries.append(BenchmarkSummary(
                model_name=data["model_name"],
                category=ModelCategory(data["category"]),
                statics_pass=data["statics_pass"],
                time_domain_status=BenchmarkPassFail(data["time_domain_status"]),
                frequency_domain_status=BenchmarkPassFail(
                    data["frequency_domain_status"]),
                seed_equivalence_status=BenchmarkPassFail(
                    data["seed_equivalence_status"]),
                overall_status=BenchmarkPassFail(data["overall_status"]),
                seed_cov=data.get("seed_cov"),
                freq_max_diff_pct=data.get("freq_max_diff_pct"),
                notes=data.get("notes"),
            ))
        except Exception as exc:
            _flush(f"  Warning: could not load {json_path.name}: {exc}")
    return summaries


# ---------------------------------------------------------------------------
# HTML Report
# ---------------------------------------------------------------------------
_BADGE_CLASS = {
    BenchmarkPassFail.PASS: "badge-pass",
    BenchmarkPassFail.WARN: "badge-warn",
    BenchmarkPassFail.FAIL: "badge-fail",
    BenchmarkPassFail.SKIP: "badge-skip",
}
_LABEL = {
    BenchmarkPassFail.PASS: "PASS",
    BenchmarkPassFail.WARN: "WARN",
    BenchmarkPassFail.FAIL: "FAIL",
    BenchmarkPassFail.SKIP: "SKIP",
}
_CSS = (
    "*{box-sizing:border-box}"
    "body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Arial,"
    "sans-serif;margin:0;padding:0;background:#f8f9fa;font-size:14px;color:#333}"
    ".container{max-width:1400px;margin:0 auto;padding:1.5em 2em}"
    ".hdr{background:#2c3e50;color:#fff;padding:1.2em 2em;margin-bottom:1.5em;"
    "border-radius:6px}"
    ".hdr h1{margin:0 0 .3em;font-size:1.6em}"
    ".hdr .meta{font-size:.9em;opacity:.85}"
    ".section{background:#fff;border-radius:6px;box-shadow:0 1px 3px "
    "rgba(0,0,0,.08);margin-bottom:1.5em;padding:1.2em 1.5em}"
    ".section h2{margin:0 0 .8em;font-size:1.2em;color:#2c3e50;"
    "border-bottom:2px solid #3498db;padding-bottom:.3em}"
    "table{border-collapse:collapse;margin:.5em 0 1em;font-size:.85em;width:100%}"
    "th,td{border:1px solid #ddd;padding:.45em .7em;text-align:left}"
    "th{background:#34495e;color:#fff;font-weight:600;font-size:.85em;"
    "text-transform:uppercase;letter-spacing:.3px}"
    "tbody tr:nth-child(even){background:#f8f9fa}"
    "tbody tr.pass{background:#eafaf1!important}"
    "tbody tr.fail{background:#fdedec!important}"
    "tbody tr.warn{background:#fef9e7!important}"
    ".badge{display:inline-block;padding:3px 10px;border-radius:3px;color:#fff;"
    "font-size:.8em;font-weight:700}"
    ".badge-pass{background:#27ae60}.badge-fail{background:#e74c3c}"
    ".badge-warn{background:#f39c12}.badge-skip{background:#95a5a6}"
    ".summary-grid{display:grid;grid-template-columns:repeat(auto-fit,"
    "minmax(160px,1fr));gap:1em;margin:1em 0 1.5em}"
    ".card{background:#fff;border:1px solid #ddd;border-radius:6px;padding:1em;"
    "text-align:center;box-shadow:0 1px 3px rgba(0,0,0,.08)}"
    ".card .lbl{color:#888;font-size:.8em}"
    ".card .val{font-size:1.4em;font-weight:700;margin:.3em 0;color:#2c3e50}"
    ".footer{margin-top:2em;padding-top:1em;border-top:1px solid #ddd;"
    "color:#999;font-size:.75em;text-align:center}"
    "@media(max-width:700px){.summary-grid{grid-template-columns:1fr}}"
)


def _badge(status: BenchmarkPassFail) -> str:
    return f'<span class="badge {_BADGE_CLASS[status]}">{_LABEL[status]}</span>'


def _fmt_opt(val: Optional[float], fmt: str = ".3f") -> str:
    return format(val, fmt) if val is not None else "—"


def generate_html_report(summaries: List[BenchmarkSummary], mock: bool) -> None:
    """Generate and write the consolidated HTML report to REPORT_PATH."""
    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
    ts = time.strftime("%Y-%m-%d %H:%M UTC", time.gmtime())
    n = len(summaries)
    n_pass = sum(1 for s in summaries if s.overall_status == BenchmarkPassFail.PASS)
    n_warn = sum(1 for s in summaries if s.overall_status == BenchmarkPassFail.WARN)
    n_fail = sum(1 for s in summaries if s.overall_status == BenchmarkPassFail.FAIL)
    n_skip = sum(1 for s in summaries if s.overall_status == BenchmarkPassFail.SKIP)
    tier = "Mock (unit tier — no solver)" if mock else "Solver (OrcFxAPI)"

    body_parts: List[str] = []

    # Summary cards
    body_parts.append('<div class="summary-grid">')
    for lbl, val, col in [
        ("Total Models", n, "#2c3e50"),
        ("Pass", n_pass, "#27ae60"),
        ("Warn", n_warn, "#f39c12"),
        ("Fail", n_fail, "#e74c3c" if n_fail else "#27ae60"),
        ("Skip", n_skip, "#95a5a6"),
    ]:
        body_parts.append(
            f'<div class="card"><div class="lbl">{lbl}</div>'
            f'<div class="val" style="color:{col}">{val}</div></div>'
        )
    body_parts.append("</div>")

    # Tolerance reference table
    body_parts.append(
        '<div class="section"><h2>Acceptance Criteria</h2>'
        '<table><thead><tr><th>Gate</th><th>Metric</th><th>Threshold</th>'
        "</tr></thead><tbody>"
        f"<tr><td>Seed equivalence</td><td>Max CoV across seeds</td>"
        f"<td>&lt; {SEED_COV_THRESHOLD:.0%}</td></tr>"
        f"<tr><td>RAO amplitude</td><td>Max % diff vs reference</td>"
        f"<td>&lt; {RAO_AMP_TOLERANCE_PCT:.1f}%</td></tr>"
        f"<tr><td>Static tension</td><td>Max % diff</td>"
        f"<td>&lt; {TENSION_TOLERANCE_PCT:.1f}%</td></tr>"
        "</tbody></table></div>"
    )

    # Per-model results table
    body_parts.append(
        '<div class="section"><h2>Per-Model Benchmark Results</h2>'
        "<table><thead><tr>"
        "<th>#</th><th>Model</th><th>Category</th>"
        "<th>Time Domain</th><th>Freq Domain</th>"
        "<th>Seed Equiv</th><th>Seed CoV</th>"
        "<th>RAO Diff %</th><th>Overall</th>"
        "</tr></thead><tbody>"
    )
    for i, s in enumerate(summaries, 1):
        rc = s.overall_status.value
        body_parts.append(
            f'<tr class="{rc}">'
            f"<td>{i}</td>"
            f"<td>{s.model_name}</td>"
            f"<td>{s.category.value}</td>"
            f"<td>{_badge(s.time_domain_status)}</td>"
            f"<td>{_badge(s.frequency_domain_status)}</td>"
            f"<td>{_badge(s.seed_equivalence_status)}</td>"
            f'<td style="text-align:right">{_fmt_opt(s.seed_cov, ".4f")}</td>'
            f'<td style="text-align:right">'
            f'{_fmt_opt(s.freq_max_diff_pct, ".2f")}</td>'
            f"<td>{_badge(s.overall_status)}</td>"
            "</tr>"
        )
    body_parts.append("</tbody></table></div>")

    html_out = (
        "<!DOCTYPE html>\n<html lang='en'>\n<head>\n"
        "<meta charset='utf-8'>\n"
        "<meta name='viewport' content='width=device-width,initial-scale=1.0'>\n"
        "<title>Seed Equivalence Benchmark — Example Models</title>\n"
        f"<style>{_CSS}</style>\n"
        "</head>\n<body>\n<div class='container'>\n"
        "<div class='hdr'>\n"
        "<h1>Seed Equivalence Benchmark — All Example Models</h1>\n"
        "<div class='meta'>"
        f"<strong>Models:</strong> {n} &nbsp;|&nbsp; "
        f"<strong>Pass:</strong> {n_pass} &nbsp;|&nbsp; "
        f"<strong>Warn:</strong> {n_warn} &nbsp;|&nbsp; "
        f"<strong>Fail:</strong> {n_fail} &nbsp;|&nbsp; "
        f"<strong>Tier:</strong> {tier} &nbsp;|&nbsp; "
        f"<strong>Date:</strong> {ts}"
        "</div>\n</div>\n"
        + "\n".join(body_parts)
        + "\n<div class='footer'>Generated "
        f"{ts} &mdash; scripts/seed_equivalence.py &mdash; digitalmodel"
        "</div>\n</div>\n</body>\n</html>"
    )
    REPORT_PATH.write_text(html_out, encoding="utf-8")
    _flush(f"Report: {REPORT_PATH} ({REPORT_PATH.stat().st_size:,} bytes)")
