"""Deterministic HTML report for the response_spectrum workflow."""

from __future__ import annotations

import html
from pathlib import Path
from typing import Any

import plotly.graph_objects as go
import plotly.io as pio

from digitalmodel.common.assumption_ledger import (
    AssumptionLedger,
    AssumptionSource,
    Confidence,
)
from digitalmodel.reporting import (
    DataSource,
    Provenance,
    ReportSection,
    SectionMode,
    assemble_report,
)
from digitalmodel.seismic.response_spectrum.calculations import KinematicResult

DEFAULT_GENERATED_LABEL = "(generated by response_spectrum workflow)"


def render_report(
    result: KinematicResult,
    *,
    output_path: str | Path | None = None,
    data_source: DataSource | None,
    generated_label: str | None = None,
) -> str | Path:
    """Render a provenance-gated, deterministic PR1 report."""

    provenance = Provenance(sources=[] if data_source is None else [data_source])
    label = generated_label or DEFAULT_GENERATED_LABEL
    sections = [
        ReportSection("summary", "Summary", SectionMode.ALWAYS, _summary_section),
        ReportSection("timeseries", "Time Series", SectionMode.ALWAYS, _timeseries_section),
        ReportSection("processing", "Processing", SectionMode.ALWAYS, _processing_section),
    ]
    return assemble_report(
        "Response Spectrum Preprocessing",
        provenance=provenance,
        sections=sections,
        data={"result": result, "generated_label": label},
        ledger=_ledger(result),
        output_path=output_path,
        css=_css(),
    )


def _summary_section(data: dict[str, Any], **_: Any) -> str:
    result = data["result"]
    summary = result.summary
    rows = [
        ("Samples", summary["npts"]),
        ("dt (s)", f"{summary['dt_s']:.6g}"),
        ("PGA (m/s^2)", f"{summary['pga_m_s2']:.6g}"),
        ("PGA (g)", f"{summary['pga_g']:.6g}"),
    ]
    return (
        '<div class="section" id="summary">'
        "<h2>Kinematic acceleration integration</h2>"
        f"<p>{html.escape(data['generated_label'])}</p>"
        "<table><tbody>"
        + "".join(f"<tr><th>{html.escape(k)}</th><td>{v}</td></tr>" for k, v in rows)
        + "</tbody></table>"
        "</div>"
    )


def _processing_section(data: dict[str, Any], **_: Any) -> str:
    result = data["result"]
    rows = []
    for step in result.processing_chain:
        rows.append(
            "<tr>"
            f"<td>{html.escape(str(step.get('step', '')))}</td>"
            f"<td>{html.escape(str(step.get('method', '')))}</td>"
            f"<td><code>{html.escape(str(step))}</code></td>"
            "</tr>"
        )
    return (
        '<div class="section" id="processing">'
        "<h2>Processing chain</h2>"
        "<p>PR1 performs baseline correction, optional filtering, and kinematic "
        "cumtrapz integration only. SDOF/Newmark spectra are deliberately out of scope.</p>"
        "<table><thead><tr><th>Step</th><th>Method</th><th>Parameters</th></tr></thead>"
        f"<tbody>{''.join(rows)}</tbody></table></div>"
    )


def _timeseries_section(data: dict[str, Any], **_: Any) -> str:
    result = data["result"]
    frame = result.timeseries
    fig = go.Figure()
    for column, label in [
        ("filtered_acceleration_m_s2", "Acceleration (m/s^2)"),
        ("velocity_m_s", "Velocity (m/s)"),
        ("displacement_m", "Displacement (m)"),
    ]:
        fig.add_scatter(
            x=frame["time_s"],
            y=frame[column],
            mode="lines",
            name=label,
        )
    fig.update_layout(
        title="Acceleration, velocity, and displacement",
        xaxis_title="Time (s)",
        margin={"l": 50, "r": 20, "t": 50, "b": 45},
        template="plotly_white",
    )
    plot_html = pio.to_html(
        fig,
        include_plotlyjs=True,
        full_html=False,
        div_id="response-spectrum-timeseries",
    )
    plot_html = plot_html.replace("https://cdn.plot.ly/", "")
    return (
        '<div class="section" id="timeseries">'
        "<h2>Time series</h2>"
        f"{plot_html}</div>"
    )


def _ledger(result: KinematicResult) -> AssumptionLedger:
    ledger = AssumptionLedger()
    for step in result.processing_chain:
        ledger.record(
            f"response_spectrum.{step['step']}",
            step.get("method"),
            AssumptionSource.ASSUMED_DEFAULT,
            "PR1 preprocessing configuration",
            Confidence.HIGH,
        )
    return ledger


def _css() -> str:
    return """
body { font-family: Arial, sans-serif; color: #17202a; background: #f7f9fb; }
.container { max-width: 980px; margin: 0 auto; padding: 24px; background: #fff; }
.section { border-top: 1px solid #dce3ea; padding: 18px 0; }
table { border-collapse: collapse; width: 100%; margin-top: 8px; }
th, td { border: 1px solid #dce3ea; padding: 7px 9px; text-align: left; }
th { background: #eef3f8; }
code { white-space: pre-wrap; }
"""
