@startuml  strength_workflow

scale 2
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Tomato

title Hull | Strength | Workflow

start
:Sesam Genie Assessment;

:Inputs for buckling assessments
from analysis output;

note right
Options:
  - 32 bit GeniE Excel program (or)
  - data extraction program (or)
  - others
end note

partition Structure {
if (Non-complex structures) then

note right
  - Plate and stiffener structues 
    are considered non-complex
  - Complex structures such as 
    deep girders etc. are performed 
    by hand calculations
end note

-> YES;
:Continue in Sesam Genie;

else
-> NO;
:Hand calculations per ABS CSR;

:Acceptable;
stop

endif
}

partition PULS {
if (utilization <= 0.9 \n and dimensiosn within code limits) then

note right
  w/ 0.8 utilization per ABS CSR Code
end note

-> Yes;
:Acceptable;

else

-> No;
:Hand calculations per ABS CSR;
:Acceptable;

endif
}

stop
@enduml