@startwbs strength_methodology_wbs

scale 2
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Tomato

title Hull | Strength Analysis \n Available Workflows

* Hull Structure

** Plate - UnStiffened
*** Sesam PULS \n(DnV-RP-C201, Part 2)
*** Hand Calc.: python \n(DnV CN 30.1 exists; \nTo be updated for C201 Part 2)

** Panel - Stiffened, Reg. Geom.
*** Sesam PULS \n(DnV-RP-C201, Part 2)
*** Hand Calc.: Excel \n(ABS CSR?)

** Panel - Stiffened, Non-Reg. Geom.
*** Sesam PULS \n(DnV-RP-C201, Part 2)
*** Hand Calc. Excel \n(ABS CSR?)

** Deep Girders
*** Hand Calc.: python \n(To be developed \nusing ABS CSR?)
*** TBA

** Curved Shell
*** Sesam PULS? \n(DnV-RP-C202)
*** TBA

footer
%date("yyyy.MM.dd' at 'HH:mm")
%filename()
end footer

@endwbs
