# Input Parameters for Parametric Analysis
# Source: D02 Pull in analysis.yml
# Generated: 2026-01-18 21:51:54

water_depth: 137
current_speed: 0
wind_speed: 0
water_density: 1.025
stage_durations:
- 1
- 46
- 40
- 5
hs: 0
tp: 10
wave_direction: 180

