capabilities:
- query
- explain
- guide
context_optimization:
  cross_references: []
  focused_domain: aqwa
  max_context_size: 16000
created: '2025-08-10T23:01:50.291156'
module_path: .
name: aqwa
refresh_config:
  auto_refresh: true
  priority: low
  refresh_interval: 7_days
specialization: general-purpose
version: 1.0.0
