# Input Parameters for Parametric Analysis
# Source: BaseModel.yml
# Generated: 2026-01-18 22:20:08

water_depth: 32.8
current_speed: 0
wind_speed: 0
water_density: 1.025
stage_durations:
- 10
- 100
hs: 5.1
tp: 6.5
wave_direction: 0

