@startuml modular_analysis_basefile
scale 3
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Tomato

title Modular Model Building \n OrcaWave

start

    note right
        Objective: modular file management and 
        analysis for easy updates/maintenance/reruns
    end note

    note right
        All files in .yml format
        Each partition box is a group of .yml files with related content
    end note

    partition "01.yml Analysis Parameters" {

        :Model;
            note right
                Units
            end note

    }

    partition "Calculation & output" {

        :Calculation;
            note right
                Solution type
                Tolerance
                Control surface
                Convergence criteria
                Warning Levels
            end note

        :Output;
            note right
                Pressures
                Velocities
                Intermediate Results
            end note


    }


    partition "03.yml Environment" {

        :Environment;
            note right
                Water Depth
                Water Density
                Output Settings:
                 - Period or Frequency
                 - Direction(s)
                QTF Crossing Angle Range
            end note
    }

    partition "04.yml Vessel/Bodies Data" {

    note right
        Bodies 
        Multiple bodies possible
    end note

        :Vessel Data;
            note right
                Vessel Data:
                  - Mesh
                    - data and format
                    - Location
                  - Mass
                  - Inertia
                  - Stiffness
                  - Damping
                Control Surface 
                  - Mesh and format
            end note


    }

    partition "05.yml Field Points and Drawing" {

        :TBA;
            note right
                Color of bodies
            end note

    }

stop

footer
%date("yyyy.MM.dd' at 'HH:mm")
%filename()
end footer

@enduml
