@startuml pipe_architecture
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Tomato

title Pipe Capacity

start

    partition "Load Data" {

        :Define data;

    }

    partition "Perform Analysis" {
        
        :Perform Analysis;
            note right
                Perform analysis for all methods
                Perform sensitivity analysis if required
            end note

    }

    partition "Results" {

        :Results;
            note right
                Display detailed results
                Compare results between methods
            end note

    }



stop

footer
%date("yyyy.MM.dd' at 'HH:mm")
%filename()
end footer

@enduml