# Input Parameters for Parametric Analysis
# Source: I01 Streamer array.yml
# Generated: 2026-01-18 21:52:08

water_depth: 100
current_speed: 2
wind_speed: 0
water_density: 1.025
stage_durations:
- 6
- 30
hs: 2
tp: 6
wave_direction: 180

