@startuml digitalmodel_running
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Tomato

title Digital Model | Quick Start

start

    note right
        Objective: Different Ways to Run 
    end note

    partition "Quick Start" {

        :Command line using .yml file;
            note right
                **yaml**
                In python digitalmodel environment
                Utilizes __init.py__ to run
            end note

        :using .py file;
            note right
                **yaml**
                In python digitalmodel environment
                Utilizes filename or args to run
            end note

    }

    partition "Results" {
        :Visual model;
            note right
                input file location
                Results folder
            end note

    }


stop

footer
%date("yyyy.MM.dd' at 'HH:mm")
%filename()
end footer

@enduml
