@startuml digital_model_architecure
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Tomato

title Lifecycle Digital Model

start

    note right
        Objective: Digital model for lifecycle analysis.
    end note

    partition "Input Data" {

        :Prepare yaml Data (yml);
            note right
                physical dimensions,
                interface(s), structural system data
                fabrication or manufacturing steps
                comissioning steps
                Operational steps
                decomissioning steps
            end note

    }

    partition "Analytical model" {
        :Visual model;
            note right
                For visual representation
                i.e. CAD, Blender etc.
            end note

        :Analytical model;
            note right
                Analytical representation
                i.e. equations etc.
            end note

        :Strength models;
            note right
                Theoretical strength calculations
            end note

        :Integrity/FFS models;
            note right
                fitness for service (FFS) assessments etc.
            end note

    }

    partition "Computational models" {
        :Finite or discrete models;
            note right
                Finite element, finite volume etc.
                i.e. models for open source
                or proprietary package (ANSYS, Orcaflex etc.)
            end note
    }

    partition "Analysis" {
        :Perform analysis;
            note right
                operational analysis
                i.e. strength, fatigue, dynamic etc.
            end note
    }

    partition "Visualizations" {
        :Generate visuals;
            note right
                animations, results etc.
            end note
    }

stop

footer
%date("yyyy.MM.dd' at 'HH:mm")
%filename()
end footer

@enduml
