# ABOUTME: Tubular design sub-package — design envelopes, connection ratings, wear
# ABOUTME: Public API for casing/tubing string design checks (WRK-376)

"""Tubular design tools — triaxial stress envelope, VME checks, API limits."""

from digitalmodel.well.tubulars.design_envelope import (
    AnisotropicVmeEnvelope,
    ApiEllipseEnvelope,
    IsotropicVmeEnvelope,
    TubularGeometry,
    compute_hoop_stress,
    compute_vme_stress,
    design_envelope_points,
)
from digitalmodel.well.tubulars.casing import (
    API_5CT_GRADES,
    CASING_SIZES,
    TUBING_SIZES,
    Casing,
    CasingGrade,
    casing,
    casing_grade,
    collapse_pressure,
    internal_yield_pressure,
    list_sizes,
    list_tubing_sizes,
    pipe_body_yield_strength,
    tubing,
    tubing_wall_for_size,
    wall_for_size,
)
from digitalmodel.well.tubulars.casing_design import (
    CONNECTION_CLASSES,
    NACE_MIN_SERVICE_TEMP_F,
    ConnectionClass,
    DesignFactors,
    ModeCheckResult,
    PressureProfile,
    ProductionCasingWell,
    SourServiceAssessment,
    api_round_force_lbf,
    api_round_pressure_psi,
    ballooning_tension_delta_lbf,
    burst_external_profile,
    check_burst,
    check_collapse,
    check_production_casing,
    check_tension,
    check_triaxial,
    collapse_pressure_under_tension,
    connection_class,
    cooling_tension_delta_lbf,
    fluid_column_profile,
    grade_sour_ok,
    h2s_partial_pressure_psia,
    injection_internal_profile,
    max_frac_surface_pressure,
    reduced_yield_under_tension,
    sour_service_screen,
    tubing_leak_internal_profile,
)
from digitalmodel.well.tubulars.tubing_design import (
    TubingWell,
    check_production_tubing,
    packer_fluid_annulus_profile,
    shut_in_piston_force_lbf,
    shut_in_tubing_profile,
)
from digitalmodel.well.tubulars.sucker_rod import (
    API_11B_ROD_GRADES,
    ROD_SIZES_IN,
    RodGrade,
    RodTaperSection,
    SuckerRod,
    modified_goodman_allowable,
    rod_area,
    rod_grade,
    rod_string_goodman,
    sucker_rod,
)

__all__ = [
    "AnisotropicVmeEnvelope",
    "ApiEllipseEnvelope",
    "IsotropicVmeEnvelope",
    "TubularGeometry",
    "compute_hoop_stress",
    "compute_vme_stress",
    "design_envelope_points",
    # casing + tubing catalog (API 5CT / API 5C3)
    "API_5CT_GRADES",
    "CASING_SIZES",
    "TUBING_SIZES",
    "Casing",
    "CasingGrade",
    "casing",
    "casing_grade",
    "collapse_pressure",
    "internal_yield_pressure",
    "list_sizes",
    "list_tubing_sizes",
    "pipe_body_yield_strength",
    "tubing",
    "tubing_wall_for_size",
    "wall_for_size",
    # casing design checks (Hansen/Devon EPA workshop; API 5C3, NACE MR0175)
    "CONNECTION_CLASSES",
    "NACE_MIN_SERVICE_TEMP_F",
    "ConnectionClass",
    "DesignFactors",
    "ModeCheckResult",
    "PressureProfile",
    "ProductionCasingWell",
    "SourServiceAssessment",
    "api_round_force_lbf",
    "api_round_pressure_psi",
    "ballooning_tension_delta_lbf",
    "burst_external_profile",
    "check_burst",
    "check_collapse",
    "check_production_casing",
    "check_tension",
    "check_triaxial",
    "collapse_pressure_under_tension",
    "connection_class",
    "cooling_tension_delta_lbf",
    "fluid_column_profile",
    "grade_sour_ok",
    "h2s_partial_pressure_psia",
    "injection_internal_profile",
    "max_frac_surface_pressure",
    "reduced_yield_under_tension",
    "sour_service_screen",
    "tubing_leak_internal_profile",
    # production tubing design checks
    "TubingWell",
    "check_production_tubing",
    "packer_fluid_annulus_profile",
    "shut_in_piston_force_lbf",
    "shut_in_tubing_profile",
    # sucker rod (API 11B / modified Goodman)
    "API_11B_ROD_GRADES",
    "ROD_SIZES_IN",
    "RodGrade",
    "RodTaperSection",
    "SuckerRod",
    "modified_goodman_allowable",
    "rod_area",
    "rod_grade",
    "rod_string_goodman",
    "sucker_rod",
]
