@startuml  cp_highlevel_workflow

scale 2
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Tomato

title CP Design | Typical Workflow

start
:CP Design;

:Identify Governing Code (ABS and/or DNV);

  note right
    Examples
    - ABS Cathodic Protection of Ships 
      see docs\cathodic_protection\codes\cathodic-protection-gn-dec17.pdf
    - DNV RP B401 Cathodic Protection Design , 2010, 2021 etc
      see docs\cathodic_protection\codes\DNV-RP-B401.pdf
    - others
  end note

partition CP Design (Typ.){
:Sacrificial vs. ICCP;
  note right
    - Choose between sacrifical anode or ICCP
    - Design can be hybrid (i.e. both)
    - Existing CP system (If any)
  end note

:Perform CP calculations;
  note right
    - Sacrificial Anode material & weight
    - ICCP voltage and current requirements
  end note

}

partition CP Specification {

  partition Fabrication {

  :Sacrificial Anode;
    note right
      - Anode material & weight
      - How many anodes?
      - Anode locations
      - distance between locations to protect entire structure
      - Connection to structure
      - Manufacture: NACE RP0387
      - Chemical analysis: NACE RP0387
      - weight and dimensions : NACE RP0387
      - cracks and other surface irregularities: NACE RP0387
    end note

  :ICCP;
    note right
      - ICCP stations required
      - Station locations 
      - distance between locations to protect entire structure
      - Connection to structure
    end note

  }

  partition Installation {

  :Installation method;
    note right
      - At dry-dock/Fab yard
      - Diver-assisted
      - Hot-tap work?
      - port-side or starboard-side or both based on berthing?
      - other?
    end note

  :Anode installation;
    note right
    Requirements:
      - Welding,clamping etc.  electrical continuity
      - mechanical integrity of fastening devices
      - no welding/brazing in pressure containing components
    Avoid anodes at:
      - Areas where they can cause problems in the normal operation of the ship
      - High stress areas or areas subject to high fatigue loads
      - Areas where they could be damaged (by craft coming alongside, anchor chains or cables)
    end note

  }

  partition IMMR {

  :Inspection;
    note right
      - Inspection frequency
      - Any cleaning required to inspect?
      - etc.
    end note

  :Monitor;
    note right
      - Desgn during installation
    end note

  :Maintenance;
    note right
      - Any cleaning required to maintain anode efficiency?
      - etc.
    end note

  :Repair/Replace;
    note right
      - Provision for repair/replace if required?
      - etc.
    end note

  }

  partition Project-Specific {

  :Any project specific details;
    note right
      - No-zones
      - corrosive fluids
      - etc.
    end note

  }

}

  partition Vendor Evaluation {

  :Collect vendors;
  :Get product Specs;
  :Evaluate;
  :Previous failures and learnings (if any);
  }

  partition Integrity Assessment {

  :Previous failures study;
  :Integrity management plan;

  :Probabilistic Risk Assessment (PRA);
  note right
      - Bad design
      - Poor manufacturing/installation
      - Change in design/operating conditions
      - Deferred maintenance & repairs
      - Risk Management
    end note


  }


stop
@enduml