# Input Parameters for Parametric Analysis
# Source: B01 Drilling riser.yml
# Generated: 2026-01-18 22:18:02

water_depth: 1020
current_speed: 0
wind_speed: 0
water_density: 1.025
stage_durations:
- 8
- 42
hs: 1.5
tp: 8
wave_direction: 180

