"""
Main entry point for generating OrcaFlex HTML reports.
"""
import html
from pathlib import Path
from typing import Union

from .models import OrcaFlexAnalysisReport
from .renderers import (
    BaseRenderer, 
    RiserRenderer, 
    PipelineRenderer, 
    JumperRenderer, 
    MooringRenderer, 
    InstallationRenderer
)
from .css import REPORT_CSS
from .section_builders.utils import _escape


def generate_orcaflex_report(
    report_data: OrcaFlexAnalysisReport,
    output_path: Union[str, Path],
    include_plotlyjs: Union[str, bool] = "cdn"
) -> Path:
    """
    Generates a single-file HTML report for an OrcaFlex analysis.
    
    Args:
        report_data: Populated OrcaFlexAnalysisReport model
        output_path: Where to save the resulting .html file
        include_plotlyjs: "cdn" (default), "inline", or True (inline). 
                         Set to True or "inline" for fully offline/air-gapped operation 
                         by embedding the ~3 MB Plotly JS bundle inline.
    
    Returns:
        Path to the generated report
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    # CDN security requirements (v1.9 spec)
    # Pinned Plotly.js version corresponding to plotly python package 5.17.0
    # IMPORTANT: Update PLOTLY_JS_VERSION and PLOTLY_JS_SRI when upgrading the plotly package
    PLOTLY_JS_VERSION = "2.26.0"
    PLOTLY_JS_SRI = "sha384-xuh4dD2xC9BZ4qOrUrLt8psbgevXF2v+K+FrXxV4MlJHnWKgnaKoh74vd/6Ik8uF"
    
    plotly_script = ""
    renderer_plotly_flag = include_plotlyjs
    
    if include_plotlyjs == "cdn":
        plotly_script = f'<script src="https://cdn.plot.ly/plotly-{PLOTLY_JS_VERSION}.min.js" integrity="{PLOTLY_JS_SRI}" crossorigin="anonymous"></script>'
        # Tell renderer/builders NOT to include plotlyjs in each div as we have it in head
        renderer_plotly_flag = False
    elif include_plotlyjs in (True, "inline"):
        import plotly.offline
        plotly_script = f'<script type="text/javascript">{plotly.offline.get_plotlyjs()}</script>'
        renderer_plotly_flag = False
    
    # Select renderer strategy
    stype = report_data.structure_type.lower()
    if stype == "riser":
        renderer = RiserRenderer(include_plotlyjs=renderer_plotly_flag)
    elif stype == "pipeline":
        renderer = PipelineRenderer(include_plotlyjs=renderer_plotly_flag)
    elif stype == "jumper":
        renderer = JumperRenderer(include_plotlyjs=renderer_plotly_flag)
    elif stype == "mooring":
        renderer = MooringRenderer(include_plotlyjs=renderer_plotly_flag)
    elif stype == "installation":
        renderer = InstallationRenderer(include_plotlyjs=renderer_plotly_flag)
    else:
        # Fallback to base renderer for generic or missing types
        renderer = BaseRenderer(include_plotlyjs=renderer_plotly_flag)
    
    # Render content
    report_html_content = renderer.render(report_data)
    
    # Escape user-supplied title fields for safety via shared helper
    escaped_project = _escape(report_data.project_name)
    escaped_id = _escape(report_data.structure_id)
    
    # Wrap in full HTML document
    full_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{escaped_project} - {escaped_id}</title>
    {plotly_script}
    <style>
        {REPORT_CSS}
    </style>
</head>
<body>
    {report_html_content}
    <footer>
        <p>&copy; {report_data.date.year} OrcaFlex Analysis Report. Generated by digitalmodel.solvers.orcaflex.reporting.</p>
    </footer>
</body>
</html>
"""

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(full_html)
        
    return output_path
