"""Deterministic HTML renderer for the installation-vessel pamphlet.

``render_pamphlet_html(result, generated_label)`` returns byte-identical HTML for
identical inputs. It never calls ``datetime.now`` — the ``generated_label`` is
supplied by the caller. The static sections + embedded JSON form the deterministic
artifact.

The live Open-Meteo weather-window monitor is kept, but it is an OPTIONAL
CLIENT-SIDE widget (the ``LIVE_WEATHER_MONITOR_WIDGET`` constant below). Its only
runtime non-determinism (``fetch`` / ``Date.now``) executes in the browser, not at
generation time, so the generated file bytes remain deterministic.
"""

from __future__ import annotations

import json
import re
from typing import Any

from digitalmodel.installation.installation_pamphlet.risk_reference import RISK_DATA

DEFAULT_GENERATED_LABEL = "(generated by installation_pamphlet workflow)"

PROV = {  # status -> (label, css class)
    "actual": ("ACTUAL", "pv-act"),
    "ship_proxy": ("SHIP-PROXY", "pv-ship"),
    "proxy": ("PROXY", "pv-prox"),
    "pending": ("PENDING", "pv-pend"),
}
RISKCLS = {"Low": "rk-low", "Medium": "rk-med", "High": "rk-high", "Critical": "rk-crit"}

# ---------------------------------------------------------------------------
# OPTIONAL CLIENT-SIDE WIDGET — live Open-Meteo weather-window monitor.
# This is a constant string, NOT part of the deterministic data payload. The
# three __TOKENS__ are replaced with deterministic embedded data at render time;
# fetch()/Date.now() only run later, in the browser.
# ---------------------------------------------------------------------------
LIVE_WEATHER_MONITOR_WIDGET = """<script>
const ENV = __ENV_JS__;
const TPGRID = __TP_JS__;
// interpolate limiting Hs at a given Tp for an operation
function hsLimitAt(op, tp){
  const e = ENV[op].hs_by_tp; const ks = TPGRID;
  if(tp<=ks[0]) return e[ks[0].toFixed(1)];
  if(tp>=ks[ks.length-1]) return e[ks[ks.length-1].toFixed(1)];
  for(let i=0;i<ks.length-1;i++){ if(tp>=ks[i]&&tp<=ks[i+1]){
    const a=e[ks[i].toFixed(1)], b=e[ks[i+1].toFixed(1)];
    return a+(b-a)*(tp-ks[i])/(ks[i+1]-ks[i]); } }
  return e[ks[0].toFixed(1)];
}
const SAMPLE = { // 48h demo forecast (calm-ish window mid-series)
  hours: Array.from({length:48},(_,i)=>i),
  hs: [1.9,1.8,1.7,1.5,1.3,1.1,0.9,0.7,0.6,0.5,0.45,0.4,0.38,0.35,0.34,0.33,0.35,0.4,0.5,0.65,0.8,1.0,1.2,1.4,
       1.5,1.6,1.6,1.5,1.3,1.1,0.9,0.8,0.7,0.65,0.6,0.62,0.7,0.85,1.0,1.2,1.4,1.6,1.8,1.9,2.0,2.1,2.0,1.9],
  tp: Array.from({length:48},()=>9.0),
  wind: [14,13,12,11,10,9,8,7,6.5,6,5.5,5,5,5,5,5,6,7,8,9,11,12,13,14,15,15,14,13,11,10,9,8,7,7,6.5,7,8,9,11,12,13,14,15,16,16,15,14,13]
};
function levelDot(l){return {low:'lvl-low',mod:'lvl-mod',high:'lvl-high',sev:'lvl-sev'}[l];}
function dpRisk(wind, cur){ // wind m/s, current m/s -> level + note (DP2 screening)
  const c = cur||0.4; let l='low', n='Within comfortable DP envelope.';
  if(wind>=21||c>=1.2){l='sev';n='Approaching/over DP capability — high drive-/drift-off risk.';}
  else if(wind>=15||c>=0.9){l='high';n='Reduced DP margin; verify capability plot &amp; thruster reserve.';}
  else if(wind>=10||c>=0.6){l='mod';n='Moderate environmental load on DP; monitor footprint.';}
  return {l,n};
}
function moorRisk(hs, wind){ let l='low', n='Line tensions low; watch-circle nominal.';
  if(hs>=3.0||wind>=21){l='sev';n='High dynamic line tension — risk of line failure / excursion.';}
  else if(hs>=2.0||wind>=15){l='high';n='Elevated tension cycling; check most-loaded line &amp; fatigue.';}
  else if(hs>=1.2||wind>=10){l='mod';n='Tension build-up; monitor watch-circle.';}
  return {l,n};
}
function verdict(hs, lim){ if(hs<=lim) return 'GO'; if(hs<=lim*1.25) return 'MARGINAL'; return 'NOGO'; }
function nearestIdx(times){ const now=Date.now(); let bi=0,bd=1e18;
  times.forEach((t,i)=>{const dd=Math.abs(new Date(t).getTime()-now); if(dd<bd){bd=dd;bi=i;}}); return bi; }

async function fetchLive(lat, lon){
  const m = `https://marine-api.open-meteo.com/v1/marine?latitude=${lat}&longitude=${lon}&hourly=wave_height,wave_period&forecast_days=3`;
  const a = `https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&hourly=wind_speed_10m&wind_speed_unit=ms&forecast_days=3`;
  const [mr,ar] = await Promise.all([fetch(m),fetch(a)]);
  const mj = await mr.json(), aj = await ar.json();
  const t = mj.hourly.time;
  return { times:t, hs:mj.hourly.wave_height, tp:mj.hourly.wave_period, wind:aj.hourly.wind_speed_10m };
}
function render(cur){ // cur = {hs,tp,wind,cur,times?,series?}
  const lims = { heavy_lift:+document.getElementById('limHL').value,
    dp_station_keeping:+document.getElementById('limDP').value, transit:+document.getElementById('limTR').value };
  const hs=cur.hs, tp=cur.tp, wind=cur.wind, ccur=cur.cur||0.4;
  document.getElementById('now').innerHTML = [
    ['Wave Hs',hs.toFixed(2),'m'],['Peak Tp',tp.toFixed(1),'s'],['Wind (10 m)',wind.toFixed(1),'m/s'],['Current*',ccur.toFixed(2),'m/s']
  ].map(x=>`<div class="m"><div class="k">${x[0]}</div><div class="vv">${x[1]}</div><div class="u">${x[2]}</div></div>`).join('');
  const ops=[['Heavy lift','heavy_lift'],['DP station-keep','dp_station_keeping'],['Transit','transit']];
  document.getElementById('golist').innerHTML = ops.map(([nm,op])=>{
    const lim=lims[op]; const vd=verdict(hs,lim);
    return `<div class="go ${vd}"><div class="t">${nm}</div>
      <div class="verdict v${vd}">${vd==='NOGO'?'NO-GO':vd}</div>
      <div class="lim">Hs ${hs.toFixed(2)} vs limit ${lim.toFixed(2)} m</div></div>`;
  }).join('');
  // next window vs heavy-lift limit (from forecast series if available)
  let winHtml='';
  if(cur.series){ const lim=lims.heavy_lift; const s=cur.series;
    let i0=nearestIdx(cur.times); let start=-1,len=0,best=0,bestStart=-1;
    for(let i=i0;i<s.hs.length;i++){ if(s.hs[i]<=lim){ if(start<0)start=i; len++; if(len>best){best=len;bestStart=start;} } else {start=-1;len=0;} }
    if(best>0){ const hrs=best; const startsIn=Math.max(0,bestStart-i0);
      winHtml=`<b>Next heavy-lift window</b> (Hs &le; ${lim.toFixed(2)} m): ~${hrs} h long, starting in ~${startsIn} h.`; }
    else winHtml=`<b>No heavy-lift window</b> in forecast horizon at Hs &le; ${lim.toFixed(2)} m — raise the limit with vessel-specific RAO.`;
  } else { winHtml='<span class="mut2">Load live or demo data to compute the next weather window.</span>'; }
  document.getElementById('win').innerHTML = winHtml;
  // risk panels
  const dp=dpRisk(wind,ccur), mo=moorRisk(hs,wind);
  document.getElementById('risk').innerHTML = `
   <div class="r"><h4>DP station-keeping risk (__DPCLASS__)</h4>
     <div class="rrow"><span class="dot ${levelDot(dp.l)}"></span><b>${dp.l.toUpperCase()}</b> &mdash; ${dp.n}</div>
     <div class="rrow mut2">Drivers: wind ${wind.toFixed(1)} m/s, current ${ccur.toFixed(2)} m/s. Single-fault tolerant — a worst-case failure must still hold position.</div></div>
   <div class="r"><h4>Mooring / line-tension risk</h4>
     <div class="rrow"><span class="dot ${levelDot(mo.l)}"></span><b>${mo.l.toUpperCase()}</b> &mdash; ${mo.n}</div>
     <div class="rrow mut2">Drivers: Hs ${hs.toFixed(2)} m, wind ${wind.toFixed(1)} m/s. Applies if rigged on the 8-point spread instead of DP.</div></div>`;
}
async function refresh(){
  const lat=document.getElementById('lat').value, lon=document.getElementById('lon').value;
  document.getElementById('stamp').textContent='loading…';
  try{ const f=await fetchLive(lat,lon); const i=nearestIdx(f.times);
    render({hs:f.hs[i],tp:f.tp[i]||9,wind:f.wind[i],cur:0.4,times:f.times,series:{hs:f.hs}});
    document.getElementById('stamp').textContent='live · '+new Date(f.times[i]).toUTCString().slice(5,22)+' UTC';
  }catch(e){ document.getElementById('stamp').textContent='live feed unavailable — using demo data';
    useSample(); }
}
function useSample(){
  const i=12; // calm point
  const times=SAMPLE.hours.map(h=>new Date(Date.now()+(h-6)*3600e3).toISOString());
  render({hs:SAMPLE.hs[i],tp:SAMPLE.tp[i],wind:SAMPLE.wind[i],cur:0.4,times,series:{hs:SAMPLE.hs}});
  document.getElementById('stamp').textContent='demo data';
}
refresh(); setInterval(refresh, 600000); // auto-refresh every 10 min
</script>"""


def _live_monitor_script(envelopes: dict[str, Any], tp_grid: list[float], dpclass: str) -> str:
    """Inject the deterministic embedded data into the client-side widget."""
    return (
        LIVE_WEATHER_MONITOR_WIDGET
        .replace("__ENV_JS__", json.dumps(envelopes))
        .replace("__TP_JS__", json.dumps(tp_grid))
        .replace("__DPCLASS__", str(dpclass))
    )


def render_pamphlet_html(result: dict[str, Any], generated_label: str | None = None) -> str:
    """Render the full self-contained pamphlet HTML. Deterministic."""
    GEN = generated_label if generated_label is not None else DEFAULT_GENERATED_LABEL
    d = result
    v = d["vessel"]
    TP = [float(t) for t in d["tp_grid_s"]]
    op_table = d["op_table"]
    rk = RISK_DATA
    st = d.get("provenance") or {
        "tasks": [],
        "rao_basis": d.get("rao_basis", "barge"),
        "n_completed_runs": 0,
        "basis_run_id": None,
    }
    DPCLASS = v["dp_class"]

    def prov_badge(status):
        lab, cls = PROV.get(status, ("?", "pv-prox"))
        return f'<span class="pv {cls}">{lab}</span>'

    def section_status(secnum):
        sts = [t["status"] for t in st["tasks"] if t["section"] == secnum]
        if not sts:
            return "actual"
        order = ["pending", "proxy", "ship_proxy", "actual"]  # weakest wins
        return min(sts, key=lambda s: order.index(s) if s in order else 0)

    def crane_svg():
        R = v["crane_radii_m"]
        C = v["crane_caps_te"]
        W, H, ml, mr, mt, mb = 460, 230, 52, 14, 16, 34
        rmax = max(R) * 1.05
        cmax = max(C) * 1.08

        def X(r):
            return ml + r / rmax * (W - ml - mr)

        def Y(c):
            return H - mb - c / cmax * (H - mt - mb)

        pts = " ".join(f"{X(r):.1f},{Y(c):.1f}" for r, c in zip(R, C))
        dots = "".join(
            f'<circle cx="{X(r):.1f}" cy="{Y(c):.1f}" r="3.5" fill="#0a6cbf"/>'
            f'<text x="{X(r):.1f}" y="{Y(c)-7:.1f}" font-size="10" text-anchor="middle" fill="#0f2233">{c:,.0f} te</text>'
            for r, c in zip(R, C)
        )
        xt = "".join(
            f'<text x="{X(r):.1f}" y="{H-mb+14:.1f}" font-size="10" text-anchor="middle" fill="#5a6b7a">{r:.0f}</text>'
            for r in R
        )
        yt = "".join(
            f'<line x1="{ml}" y1="{Y(c):.1f}" x2="{W-mr}" y2="{Y(c):.1f}" stroke="#eef2f6"/>'
            f'<text x="{ml-6}" y="{Y(c)+3:.1f}" font-size="9" text-anchor="end" fill="#5a6b7a">{c:,}</text>'
            for c in [0, 1000, 2000, 3000, 4000]
        )
        return (
            f'<svg viewBox="0 0 {W} {H}" width="100%" role="img" aria-label="Crane SWL vs radius">\n'
            f'{yt}<polyline points="{pts}" fill="none" stroke="#0a6cbf" stroke-width="2.2"/>{dots}{xt}\n'
            f'<text x="{W//2}" y="{H-3}" font-size="10" text-anchor="middle" fill="#5a6b7a">Crane radius (m)</text>\n'
            f'<text x="12" y="{H//2}" font-size="10" text-anchor="middle" fill="#5a6b7a" transform="rotate(-90 12 {H//2})">SWL (te)</text></svg>'
        )

    def env_svg():
        W, H, ml, mr, mt, mb = 460, 250, 46, 112, 16, 34
        colors = {"transit": "#0a8f4f", "dp_station_keeping": "#d98b00", "heavy_lift": "#c0392b"}
        labels = {"transit": "Transit", "dp_station_keeping": "DP station-keep", "heavy_lift": "Heavy lift"}
        tmin, tmax = min(TP), max(TP)
        hmax = 1.2

        def X(t):
            return ml + (t - tmin) / (tmax - tmin) * (W - ml - mr)

        def Y(h):
            return H - mb - h / hmax * (H - mt - mb)

        grid = "".join(
            f'<line x1="{ml}" y1="{Y(h):.1f}" x2="{W-mr}" y2="{Y(h):.1f}" stroke="#eef2f6"/>'
            f'<text x="{ml-6}" y="{Y(h)+3:.1f}" font-size="9" text-anchor="end" fill="#5a6b7a">{h:.1f}</text>'
            for h in [0, 0.3, 0.6, 0.9, 1.2]
        )
        grid += "".join(
            f'<text x="{X(t):.1f}" y="{H-mb+14:.1f}" font-size="10" text-anchor="middle" fill="#5a6b7a">{t:.0f}</text>'
            for t in TP
        )
        series = ""
        leg = ""
        for i, (op, e) in enumerate(d["envelopes"].items()):
            col = colors.get(op, "#0a6cbf")
            pts = " ".join(f"{X(t):.1f},{Y(e['hs_by_tp'][str(float(t))]):.1f}" for t in TP)
            series += f'<polyline points="{pts}" fill="none" stroke="{col}" stroke-width="2.2"/>'
            series += "".join(
                f'<circle cx="{X(t):.1f}" cy="{Y(e["hs_by_tp"][str(float(t))]):.1f}" r="2.6" fill="{col}"/>'
                for t in TP
            )
            ly = mt + 4 + i * 16
            leg += (
                f'<line x1="{W-mr+6}" y1="{ly}" x2="{W-mr+24}" y2="{ly}" stroke="{col}" stroke-width="2.6"/>'
                f'<text x="{W-mr+28}" y="{ly+3}" font-size="10" fill="#0f2233">{labels.get(op, op)} (&alpha;={e["alpha"]})</text>'
            )
        return (
            f'<svg viewBox="0 0 {W} {H}" width="100%" role="img" aria-label="Operational Hs limit vs Tp">\n'
            f'{grid}{series}{leg}\n'
            f'<text x="{(ml+W-mr)//2}" y="{H-3}" font-size="10" text-anchor="middle" fill="#5a6b7a">Peak period Tp (s)</text>\n'
            f'<text x="12" y="{H//2}" font-size="10" text-anchor="middle" fill="#5a6b7a" transform="rotate(-90 12 {H//2})">Limiting Hs (m)</text></svg>'
        )

    def lift_rows():
        out = ""
        for r in d["lifts"]:
            bar = min(100, max(r["utilization_pct"], 1))
            out += (
                f"<tr><td class='l'>{r['item']}</td><td>{r['mass_air_te']:.2f}</td>"
                f"<td>{r['hook_load_te']:.1f}</td><td>{r['swl_at_radius_te']:,.0f}</td>"
                f"<td><div class='ut'><span style='width:{bar:.0f}%'></span></div>{r['utilization_pct']:.1f}%</td>"
                f"<td><span class='b ok'>PASS</span></td></tr>"
            )
        return out

    def env_rows():
        labels = {
            "transit": "Transit / sail-away",
            "dp_station_keeping": "DP station-keeping",
            "heavy_lift": "Heavy lift (splash zone)",
        }
        return "".join(
            f"<tr><td class='l'>{labels.get(op, op)} <small>&alpha;={e['alpha']}</small></td>"
            + "".join(f"<td>{e['hs_by_tp'][str(float(t))]:.2f}</td>" for t in TP)
            + "</tr>"
            for op, e in d["envelopes"].items()
        )

    def optbl_rows():
        return "".join(
            f"<tr><td>&le; {r['hs_limit_m']:.1f}</td><td>{r['operability_pct']:.1f}%</td>"
            f"<td><div class='ut wide'><span style='width:{r['operability_pct']:.0f}%'></span></div></td></tr>"
            for r in op_table
        )

    ehead = "".join(f"<th>{t:.0f}</th>" for t in TP)

    def _basis_h(b):
        return {
            "barge": "100 m barge proxy",
            "drillship": "ship-shaped (drillship) proxy",
            "fpso": "ship-shaped (FPSO) proxy",
            "vessel": "vessel-specific OrcaWave RAO",
        }.get(b, b)

    def progress_panel():
        tasks = st["tasks"]
        if not tasks:
            return ""
        wt = {"actual": 1.0, "ship_proxy": 0.6, "proxy": 0.35, "pending": 0.0}
        pct = round(100 * sum(wt.get(t["status"], 0) for t in tasks) / len(tasks))
        rows = "".join(
            f"<tr><td>{t['id']}</td><td>{t['title']}</td><td>{prov_badge(t['status'])}</td>"
            f"<td>{t['basis']}</td><td class='runid'>{t['run_id'] or '—'}</td></tr>"
            for t in tasks
        )
        basis_run = (
            (' &middot; from <span class="runid">' + st["basis_run_id"] + "</span>")
            if st.get("basis_run_id")
            else ""
        )
        return (
            '<div class="prog">\n'
            "<h3>Analysis progress &amp; data provenance</h3>\n"
            f'<div style="font-size:12px;color:#9fbcd0">Maturity {pct}% &middot; {st["n_completed_runs"]} licensed run(s) completed &middot;\n'
            f'current RAO basis: <b style="color:#dfe9f1">{_basis_h(st["rao_basis"])}</b>{basis_run}</div>\n'
            f'<div class="meter"><span style="width:{pct}%"></span></div>\n'
            f"<table><tr><th>Task</th><th>Analysis</th><th>Status</th><th>Basis</th><th>Licensed run</th></tr>{rows}</table>\n"
            '<div style="font-size:11px;color:#7fa0b8;margin-top:7px">Auto-upgrades as licensed runs land: <b>PENDING</b> &rarr; <b>PROXY</b> &rarr; <b>SHIP-PROXY</b> &rarr; <b>ACTUAL</b>.\n'
            "Next upgrade: a vessel-specific BokaLift mesh diffraction (T3&rarr;ACTUAL) and per-structure OrcaFlex splash-zone runs (T5).</div></div>"
        )

    def cause_bars(rows):
        out = ""
        for r in rows:
            nums = re.findall(r"\d+", r["approx_share_pct"])
            pct = int(nums[-1]) if nums else 0
            out += (
                f"<tr><td class='l'>{r['cause']}</td><td>{r['approx_share_pct']}</td>"
                f"<td><div class='ut wide'><span style='width:{pct}%'></span></div></td>"
                f"<td><small>{r['source']}</small></td></tr>"
            )
        return out

    def risk_op_blocks():
        blocks = ""
        for op in rk["operations"]:
            rows = "".join(
                f"<tr><td class='l'>{m['mode']}</td><td class='l'>{m['cause']}</td><td class='l'>{m['effect']}</td>"
                f"<td>{m['likelihood']}</td><td>{m['severity']}</td>"
                f"<td><span class='rk {RISKCLS[m['risk']]}'>{m['risk']}</span></td>"
                f"<td class='l'><small>{m['mitigation']}</small></td></tr>"
                for m in op["failure_modes"]
            )
            blocks += (
                f"<h3 class='oph'>{op['operation']}</h3>"
                f"<table class='rt'><tr><th class='l'>Failure mode</th><th class='l'>Cause</th>"
                f"<th class='l'>Effect</th><th>Likelihood</th><th>Severity</th><th>Risk</th><th class='l'>Mitigation</th></tr>"
                f"{rows}</table>"
            )
        return blocks

    envelope_note_tail = (
        "These are still parametric — the vessel-specific BokaLift mesh diffraction (when that licensed run completes) replaces them and is expected to widen the limits further."
        if d["rao_provenance"] != "actual"
        else "Computed from the vessel-specific OrcaWave RAO solve."
    )

    script = _live_monitor_script(d["envelopes"], TP, DPCLASS)

    html = f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Installation Vessel Pamphlet — {v['name']}</title>
<style>
:root{{--ink:#0f2233;--ac:#0a6cbf;--mut:#5a6b7a;--ln:#dce3ea;--ok:#0a8f4f;--amber:#d98b00;--red:#c0392b;--bg:#eef2f6}}
*{{box-sizing:border-box}}
body{{font:14px/1.55 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:var(--ink);margin:0;background:var(--bg)}}
.wrap{{max-width:920px;margin:22px auto;background:#fff;box-shadow:0 1px 8px rgba(20,40,60,.10);border-radius:8px;overflow:hidden}}
header{{background:linear-gradient(135deg,#0a6cbf,#0c4d80);color:#fff;padding:24px 30px}}
header h1{{margin:0;font-size:23px}} header .s{{opacity:.92;font-size:13.5px;margin-top:4px}}
.tag{{display:inline-block;background:rgba(255,255,255,.18);border:1px solid rgba(255,255,255,.35);border-radius:20px;padding:2px 11px;font-size:11.5px;margin-top:10px}}
main{{padding:8px 30px 26px}}
h2{{font-size:15px;color:var(--ac);margin:24px 0 8px;border-left:4px solid var(--ac);padding-left:9px}}
.sub{{color:var(--mut);font-size:12.5px;margin:-2px 0 8px}}
.grid{{display:grid;grid-template-columns:1fr 1fr;gap:18px;align-items:start}}
.card{{border:1px solid var(--ln);border-radius:7px;padding:12px 14px;background:#fbfdff}}
.card h3{{margin:0 0 8px;font-size:12.5px;color:var(--mut);font-weight:600;text-transform:uppercase;letter-spacing:.4px}}
table{{border-collapse:collapse;width:100%;font-size:12.7px}}
th,td{{border-bottom:1px solid var(--ln);padding:6px 8px;text-align:center}}
th{{background:#f3f7fb;font-weight:600;color:#33485a}} td.l,th.l{{text-align:left}}
.kv td{{border:none;padding:4px 2px;text-align:left}} .kv td:first-child{{color:var(--mut);width:52%}} .kv td:last-child{{font-weight:600}}
.b{{padding:1px 8px;border-radius:9px;color:#fff;font-size:10.5px;font-weight:700}}
.b.ok{{background:var(--ok)}} .b.warn{{background:var(--amber)}} .b.no{{background:var(--red)}} .b.mut{{background:#90a4b4}}
.ut{{display:inline-block;width:62px;height:7px;background:#e3eaf0;border-radius:4px;overflow:hidden;vertical-align:middle;margin-right:6px}}
.ut.wide{{width:120px}} .ut span{{display:block;height:100%;background:var(--ac)}}
.note{{background:#fff6e6;border:1px solid #f0d9a0;border-radius:7px;padding:10px 13px;font-size:12.3px;margin-top:12px}}
.note.g{{background:#eafaf1;border-color:#bfe6cf}}
.banner{{background:#fbe9e7;border-left:4px solid var(--red);padding:8px 13px;font-size:12.2px;color:#7a1f15;margin:14px 30px 0}}
footer{{padding:14px 30px 22px;color:var(--mut);font-size:11.3px;border-top:1px solid var(--ln);margin-top:22px}}
small{{color:var(--mut)}}
/* live monitor */
.mon{{border:1px solid var(--ln);border-radius:8px;background:#0e1f2e;color:#dfe9f1;padding:0;overflow:hidden}}
.mon .bar{{display:flex;flex-wrap:wrap;gap:8px;align-items:center;background:#0a1722;padding:10px 14px;font-size:12.5px}}
.mon input{{background:#1b3346;border:1px solid #2e526e;color:#eaf2f8;border-radius:5px;padding:4px 7px;font-size:12px;width:92px}}
.mon button{{background:var(--ac);color:#fff;border:0;border-radius:5px;padding:5px 12px;font-size:12px;cursor:pointer}}
.mon button.alt{{background:#2e526e}}
.mon .body{{padding:14px}}
.now{{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:12px}}
.now .m{{background:#13283a;border:1px solid #1f3d54;border-radius:7px;padding:9px 11px}}
.now .m .k{{font-size:10.5px;color:#7fa0b8;text-transform:uppercase;letter-spacing:.4px}}
.now .m .vv{{font-size:21px;font-weight:700;margin-top:2px}} .now .m .u{{font-size:11px;color:#90a9bd}}
.golist{{display:grid;grid-template-columns:1fr 1fr 1fr;gap:10px}}
.go{{border-radius:7px;padding:10px 12px;border:1px solid #1f3d54;background:#13283a}}
.go .t{{font-size:11.5px;color:#9fbcd0}} .go .verdict{{font-size:16px;font-weight:800;margin-top:3px}}
.go .lim{{font-size:11px;color:#84a2b8;margin-top:3px}}
.go.GO{{box-shadow:inset 0 0 0 2px var(--ok)}} .go.MARGINAL{{box-shadow:inset 0 0 0 2px var(--amber)}} .go.NOGO{{box-shadow:inset 0 0 0 2px var(--red)}}
.vGO{{color:#4cd28a}} .vMARGINAL{{color:#f0b34d}} .vNOGO{{color:#ef7468}}
.risk{{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px}}
.risk .r{{background:#13283a;border:1px solid #1f3d54;border-radius:7px;padding:10px 12px}}
.risk .r h4{{margin:0 0 6px;font-size:12px;color:#bcd4e6}}
.dot{{display:inline-block;width:9px;height:9px;border-radius:50%;margin-right:6px}}
.lvl-low{{background:#4cd28a}} .lvl-mod{{background:#f0b34d}} .lvl-high{{background:#ef8a5a}} .lvl-sev{{background:#ef5350}}
.rrow{{font-size:12px;margin:4px 0;color:#cfe0ec}}
.mut2{{color:#8aa6ba;font-size:11px}}
.win{{margin-top:12px;font-size:12.5px;background:#13283a;border:1px solid #1f3d54;border-radius:7px;padding:9px 12px}}
/* risk section */
.oph{{font-size:13px;color:var(--ink);margin:16px 0 4px;font-weight:700}}
.rt{{font-size:12px}} .rt td,.rt th{{padding:5px 7px}} .rt td.l{{font-size:11.6px}}
.rk{{padding:1px 8px;border-radius:9px;color:#fff;font-size:10.5px;font-weight:700;white-space:nowrap}}
.rk-low{{background:#0a8f4f}} .rk-med{{background:#d98b00}} .rk-high{{background:#e2622c}} .rk-crit{{background:#c0392b}}
.statgrid{{display:grid;grid-template-columns:1fr 1fr;gap:18px;align-items:start}}
.dp3{{background:#eef4fb;border:1px solid #cfe0f1;border-radius:7px;padding:10px 13px;font-size:12.3px;margin-top:10px}}
.legend{{font-size:11px;color:var(--mut);margin-top:6px}}
.legend .rk{{margin:0 3px}}
/* provenance / progress */
.pv{{padding:1px 7px;border-radius:9px;color:#fff;font-size:9.5px;font-weight:700;letter-spacing:.3px;vertical-align:middle;margin-left:7px}}
.pv-act{{background:#0a8f4f}} .pv-ship{{background:#0a6cbf}} .pv-prox{{background:#d98b00}} .pv-pend{{background:#90a4b4}}
.prog{{background:#0e1f2e;color:#dfe9f1;border-radius:8px;padding:14px 16px;margin:14px 30px 0}}
.prog h3{{margin:0 0 4px;font-size:13px;color:#cfe2f0}}
.prog .meter{{height:9px;background:#1b3346;border-radius:5px;overflow:hidden;margin:8px 0}}
.prog .meter span{{display:block;height:100%;background:linear-gradient(90deg,#0a8f4f,#0a6cbf)}}
.prog table{{margin-top:8px}} .prog td,.prog th{{border-color:#1f3d54;color:#dfe9f1;text-align:left;padding:4px 8px;font-size:11.7px}}
.prog th{{background:#13283a;color:#9fbcd0}} .prog tr td:first-child{{color:#9fbcd0;width:42px}}
.prog .runid{{font-family:ui-monospace,Menlo,monospace;font-size:10.5px;color:#7fa0b8}}
@media print{{body{{background:#fff}} .wrap{{box-shadow:none;margin:0}} .mon{{background:#fff;color:#0f2233}}}}
@media(max-width:680px){{.grid,.now,.golist,.risk{{grid-template-columns:1fr}}}}
</style></head><body><div class="wrap">

<header>
<h1>Installation Vessel Pamphlet</h1>
<div class="s"><b>{v['name']}</b> &middot; {v['type']} &middot; {v['owner']}</div>
<span class="tag">Desktop screening + live weather-window monitor &middot; {GEN}</span>
</header>

<div class="banner"><b>DRAFT — not for marine-warranty issue.</b> Seakeeping envelopes use a conservative proxy RAO
pending the vessel-specific OrcaWave solve (parallel licensed run). Live monitor is decision-support only;
confirm against vessel RAO, MWS approval and the bridge/DP &amp; mooring teams before execution.</div>

{progress_panel()}

<main>

<h2>1 &nbsp;Vessel Characteristics</h2>
<div class="grid">
<div class="card"><h3>Particulars</h3><table class="kv">
<tr><td>Vessel type</td><td>{v['type']}</td></tr>
<tr><td>Owner / operator</td><td>{v['owner']}</td></tr>
<tr><td>Max hook load</td><td>{v['max_hook_te']:,.0f} te</td></tr>
<tr><td>Free deck area</td><td>{v['deck_area_m2']:,.0f} m&sup2;</td></tr>
<tr><td>Deck strength</td><td>{v['deck_strength_t_per_m2'] or '— (TBC)'}</td></tr>
<tr><td>Station-keeping</td><td>{DPCLASS}</td></tr>
</table></div>
<div class="card"><h3>Main crane — SWL vs radius</h3>{crane_svg()}</div>
</div>

<h2>2 &nbsp;Lift Suitability — Structures &amp; Jumpers</h2>
<div class="sub">Hook load = air mass &times; DAF {d['daf']} (DNV-ST-N001); SWL interpolated at {d['lift_radius_m']:.0f} m radius.</div>
<table><tr><th class="l">Item</th><th>Air mass (te)</th><th>Hook load (te)</th><th>SWL @ {d['lift_radius_m']:.0f} m (te)</th><th>Utilisation</th><th>Verdict</th></tr>
{lift_rows()}</table>
<div class="note g"><b>Lift capacity is not the constraint</b> — heaviest item (250 te &rarr; 325 te hook) uses ~10% of SWL.
Governing limits are <b>seakeeping</b> and <b>station-keeping</b> (&sect;5–6), not crane capacity.</div>

<h2>3 &nbsp;Operational Envelopes — Limiting Hs vs Tp {prov_badge(section_status(3))}</h2>
<div class="sub">Closed-form JONSWAP &times; RAO motion-criteria screen (DNV-RP-H103 / ST-N001), &gamma;=3.3.</div>
<div class="grid">
<div class="card"><h3>Limiting Hs (m)</h3>{env_svg()}</div>
<div class="card"><h3>Tabulated Hs (m) by Tp (s)</h3>
<table><tr><th class="l">Operation</th>{ehead}</tr>{env_rows()}</table>
<p class="sub" style="margin-top:8px">Header row = Tp (s).</p></div>
</div>
<div class="note"><b>Envelope basis:</b> {d['envelope_proxy']}. {envelope_note_tail}</div>

<h2>4 &nbsp;Lift Items (reference catalogs)</h2>
<table><tr><th class="l">Item</th><th>Footprint L&times;W&times;H (m)</th><th>Air mass (te)</th><th>Source</th></tr>
<tr><td class="l">Mudmat — small</td><td>6 &times; 6 &times; 1.5</td><td>50</td><td>mudmat_structures.json</td></tr>
<tr><td class="l">Mudmat — medium</td><td>8 &times; 10 &times; 2.0</td><td>100</td><td>mudmat_structures.json</td></tr>
<tr><td class="l">Subsea template — large</td><td>12 &times; 14 &times; 2.5</td><td>200</td><td>mudmat_structures.json</td></tr>
<tr><td class="l">Manifold / PLET <small>(proxy)</small></td><td>14 &times; 12 &times; 6</td><td>250</td><td>proxy — catalog gap</td></tr>
<tr><td class="l">Rigid jumper — 20 m</td><td>8&Prime; X65, M-shape</td><td>1.85</td><td>rigid_jumpers.json</td></tr>
<tr><td class="l">Rigid jumper — 100 m</td><td>8&Prime; X65, W-shape</td><td>9.24</td><td>rigid_jumpers.json</td></tr>
</table>

<h2>5 &nbsp;Weather-Window Operability (site scatter) {prov_badge(section_status(5))}</h2>
<div class="sub">% of time Hs is below a limit, from the weather_window engine on a generic scatter diagram.</div>
<table><tr><th>Hs limit (m)</th><th>Operability</th><th></th></tr>{optbl_rows()}</table>
<div class="note"><b>Why the real RAO matters.</b> At the proxy heavy-lift limit (~0.2 m Hs) operability is ~0% — unworkable.
A realistic vessel RAO lifts the heavy-lift limit toward 2–2.5 m Hs, where operability is <b>~57–74%</b>. The RAO solve is the single biggest lever on workable days.</div>

<h2>6 &nbsp;Live Weather-Window Monitor</h2>
<div class="sub">Live marine + wind forecast (Open-Meteo, no key) checked against the operation limits above, with DP / mooring failure-risk screening. Editable Hs limits — overwrite with vessel-specific values once available.</div>
<div class="mon">
 <div class="bar">
  <span>Site</span>
  <label>Lat <input id="lat" value="28.74"></label>
  <label>Lon <input id="lon" value="-88.36"></label>
  <label>HL Hs<input id="limHL" value="0.20" style="width:60px"></label>
  <label>DP Hs<input id="limDP" value="0.30" style="width:60px"></label>
  <label>Transit Hs<input id="limTR" value="0.45" style="width:60px"></label>
  <button onclick="refresh()">Update</button>
  <button class="alt" onclick="useSample()">Demo data</button>
  <span id="stamp" class="mut2"></span>
 </div>
 <div class="body">
  <div class="now" id="now"></div>
  <div class="golist" id="golist"></div>
  <div class="win" id="win"></div>
  <div class="risk" id="risk"></div>
  <div class="mut2" style="margin-top:10px">Risk gradings are screening heuristics for a {DPCLASS} unit (single-fault-tolerant DP; no DP3 redundancy).
  DP = drive-off / drift-off on wind &amp; current; Mooring = line-tension / watch-circle on Hs &amp; wind. Not a substitute for a DP/mooring FMEA or capability plot.</div>
 </div>
</div>

<h2>7 &nbsp;Statistical Failure-Risk Analysis — DP &amp; Mooring</h2>
<div class="note" style="background:#eef4fb;border-color:#cfe0f1">{rk['exec_summary']}</div>

<div class="statgrid" style="margin-top:14px">
<div class="card"><h3>DP incident causes (initiating event)</h3>
<table class="rt"><tr><th class="l">Cause category</th><th>Share</th><th></th><th>Source</th></tr>
{cause_bars(rk['cause_stats']['dp_incident_causes'])}</table>
<div class="legend">IMCA annual DP reviews — shares vary year-to-year; no single category dominates every year.</div></div>
<div class="card"><h3>Mooring-line failure causes</h3>
<table class="rt"><tr><th class="l">Cause category</th><th>Share</th><th></th><th>Source</th></tr>
{cause_bars(rk['cause_stats']['mooring_failure_causes'])}</table>
<div class="legend">HSE RR444: ~1 FPSO line failure per ~5–9 operating-years; failures concentrate at terminations / touchdown / connectors.</div></div>
</div>

<div class="dp3"><b>DP2 vs DP3 — why it matters here.</b> {rk['dp2_vs_dp3_note']}</div>

<div class="sub" style="margin-top:16px">Cause &rarr; Effect &rarr; Risk rating (Likelihood &times; Severity) per operation.
<span class="legend">Risk:<span class="rk rk-low">Low</span><span class="rk rk-med">Medium</span><span class="rk rk-high">High</span><span class="rk rk-crit">Critical</span></span></div>
{risk_op_blocks()}

<div class="note"><b>Headline.</b> The single <span class="rk rk-crit">Critical</span> rating is <b>DP loss-of-position during a suspended splash-zone lift</b> —
a powered/drifting excursion that drags the load into the hull or an adjacent structure. It is controlled by a verified DP FMEA,
a pre-lift reference check, a defined abort/lay-down plan and a hard Hs go/no-go gate (§3, §6). Mooring failures are lower-likelihood
but the cascade case is high-consequence; design for intact + one-line-damaged (DNV-OS-E301).</div>

<div class="legend" style="margin-top:8px"><b>Sources:</b> {" · ".join(rk['sources'])}</div>

</main>
<footer>
Generated {GEN} from digitalmodel tables (vessel_db, mudmat_structures, rigid_jumpers) + engines (vessel_suitability,
operation_envelope, weather_window). Envelope proxy: {d['envelope_proxy']}. Live feed: Open-Meteo marine &amp; forecast APIs.
Lookup + decision-support screening — verify against vessel RAO, DP/mooring FMEA and MWS approval before offshore execution.
</footer>
</div>

{script}
</body></html>"""
    return html
