# Input Parameters for Parametric Analysis
# Source: A05 Lazy wave with FPSO.yml
# Generated: 2026-01-18 22:18:01

water_depth: 2950
current_speed: 1
wind_speed: 0
water_density: 64
stage_durations:
- 18
- 144
hs: 25
tp: 18
wave_direction: 180

