# Input Parameters for Parametric Analysis
# Source: G04 Anchor-last deployment.yml
# Generated: 2026-01-18 21:52:06

water_depth: 500
current_speed: 0
wind_speed: 0
water_density: 1.024
stage_durations:
- 10
- 250
hs: 0
tp: 8
wave_direction: 180

