# Input Parameters for Parametric Analysis
# Source: H02 Jacket to semisub.yml
# Generated: 2026-01-18 21:52:07

water_depth: 80
wind_speed: 0
water_density: 1.025
stage_durations:
- 10
- 60
wave_direction: 177.5

