# OrcaWave MCP Server Configuration
# Default configuration - copy and modify as needed

server:
  name: "orcawave-mcp-server"
  version: "1.0.0"
  description: "MCP server for OrcaWave hydrodynamic analysis"
  host: "localhost"
  port: 3100

orcawave:
  installation_path: "C:/Program Files/Orcina/OrcaWave"
  com_timeout: 30000
  auto_connect: false  # Set to true when OrcaWave is installed
  license_server: "localhost:5053"

analysis:
  default_type: "diffraction"
  convergence_tolerance: 0.01
  max_iterations: 100
  parallel_frequencies: true
  default_frequencies:
    start: 0.1
    end: 2.0
    steps: 50
  default_directions: [0, 45, 90, 135, 180, 225, 270, 315]
  default_water_depth: 200.0

mesh:
  target_quality: 0.85
  max_aspect_ratio: 3.0
  waterline_refinement: 2.0
  auto_optimize: true

integration:
  orcaflex:
    export_format: "vessel_type"
    include_qtf: true
    output_directory: "./results/orcaflex"
  excel:
    auto_charts: true
    output_directory: "./results/excel"

performance:
  cache_results: true
  cache_ttl: 3600
  max_parallel_analyses: 3

validation:
  reciprocity_check: true
  energy_check: true
  benchmark_comparison: true