# Input Parameters for Parametric Analysis
# Source: A01 Steep wave riser.yml
# Generated: 2026-01-18 22:17:57

water_depth: 100
current_speed: 0.5
wind_speed: 0
water_density: 1.025
stage_durations:
- 17
- 85
hs: 3.5
tp: 17
wave_direction: 105

